---
title: "Baseline Survey Response Analysis by Email Attempts for Time Period January to October 2023"
author: "Kelsey Dowling"
date: "`r Sys.Date()`"
header-includes:  
    \usepackage[labelformat=empty]{caption}
    \usepackage{placeins}
    \usepackage{booktabs}
    \usepackage{pdflscape}


output:
  pdf_document:
    extra_dependencies: ["float"]
    toc: false
    keep_tex: yes
    fig_width: 7
    fig_height: 5
    fig_caption: true
    df_print: paged 
---




```{r libraries, include=FALSE, warning=FALSE}

#Load Libraries
#old.packages()
#update.packages()


library(bigrquery)
library(dplyr)
library(gmodels)
library(epiDisplay)
library(lubridate)
library(tidyverse)
library(gt)
library(knitr)
library(gtsummary)
#install_tinytex()
library(tinytex)
library(vtable)
library(kableExtra)
currentdate <- Sys.Date()



bq_auth()
```

```{r, include=FALSE, warning=FALSE}

##Load Data from BQ
#Not all 4 Basline Modules are Completed--- removed AND d_100767870=104430631
#active
#verified
#no opt outs, withdrawals or refusals---- asked me to remove for first review 

project <- "nih-nci-dceg-connect-prod-6d04"
notif <- "SELECT notif.category, notif.attempt, notif.email, parts.d_869588347, greatest(d_517311251, d_832139544, d_770257102, d_264644252) as latest_module_date,
Connect_ID, d_512820379, d_821247024, d_914594314, d_832139544, d_949302066 , d_205553981, d_536735468 , d_976570371, d_663265240, d_265193023, d_222161762,d_770257102, d_264644252, d_265193023, d_541836531, d_386488297, d_452942800, d_517311251 , d_822499427, d_827220437, d_878865966, d_684635302, d_167958071, d_747006172, d_906417725, d_100767870, d_878865966, d_684635302, d_167958071
FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.notifications_JP` notif
inner join `nih-nci-dceg-connect-prod-6d04.Connect.participants`  parts
on notif.token = parts.token
where parts.d_821247024=197316935 and category LIKE '%BL Survey Reminders%' and d_512820379=486306141 and d_430551721 >= '2023-01-01T00:00:00Z' and d_430551721 <= '2023-10-01T00:00:00Z'"

#notif.email = parts.d_869588347

#notif.attempt is not null and notif.email !='email@email.com' and parts.d_821247024=197316935 and Connect_ID IS NOT NULL  AND d_906417725=104430631  AND d_747006172=104430631 and d_512820379=486306141 and

#category LIKE '%BL Survey Reminders%' and notif.category is not null-- removed so we could include those who completed module(s) before verification

#category LIKE '%BL Survey Reminders%' ----  with is 38,706 unique people, without is 89,718 unique people
#(d_517311251 < d_914594314) & (d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (d_264644252 < d_914594314) without category is 41,762
#with both 32,140

# 
# As far combining the people that received BL survey reminder emails with those who did not because they finished all BL surveys before completion, I'm having difficulty figuring out what the right base denominator would be. There are 4 different methods (for those matching the basic requirements listed above):
# 1. All participants, not limited to BL Survey Reminder Emails: 89,718 participants <----- thinking this is it
# 2. All participants, not limited to BL Survey Reminder Emails,  who have completed at least one module before verification: 41,762 participants
# 3. Participants who have received at least one BL survey reminder email: 38,706 participants
# 4. Participants who have received at least one BL survey reminder email and who have completed at least one module before verification:  32,140

#Would it be number 1? And then any tables referencing emails would have to look only at BL Survey reminders, and then any before contact 1 would include th

notif_cc <- bq_project_query(project, notif)
reminders <- bq_table_download(notif_cc, bigint = 'integer64')


```








\FloatBarrier
```{r, echo=FALSE, warning=FALSE, message=FALSE}


reminders <- reminders %>%  mutate(Site=case_when(d_827220437==531629870 ~ "HealthPartners",
                                                 d_827220437==548392715 ~ "Henry Ford Health System",
                                                 d_827220437==303349821 ~ "Marshfield Clinical Health System",
                                                 d_827220437==657167265 ~ "Sanford Health",
                                                 d_827220437==809703864 ~ "University of Chicago Medicine",
                                                d_827220437==125001209 ~ "Kaiser Permanente Colorado",
                                                 d_827220437==327912200 ~ "Kaiser Permanente Georgia",
                                                 d_827220437==300267574 ~ "Kaiser Permanente Hawaii",
                                                 d_827220437==452412599 ~ "Kaiser Permanente Northwest"),
                                   Mod1_completion_status=case_when(d_949302066==972455046 ~ "Not Started",
                                                                    d_949302066==615768760 ~ "Started",
                                                                    d_949302066==231311385 ~ "Submitted"),
                                    Mod2_completion_status=case_when(d_536735468==972455046 ~ "Not Started",
                                                                    d_536735468==615768760 ~ "Started",
                                                                    d_536735468==231311385 ~ "Submitted"),
                                    Mod3_completion_status=case_when(d_976570371==972455046 ~ "Not Started",
                                                                    d_976570371==615768760 ~ "Started",
                                                                    d_976570371==231311385 ~ "Submitted"),
                                    Mod4_completion_status=case_when(d_663265240==972455046 ~ "Not Started",
                                                                    d_663265240==615768760 ~ "Started",
                                                                    d_663265240==231311385 ~ "Submitted"),
                                   All_Completed_Status=case_when(d_949302066==231311385 & d_536735468==231311385 & 
                                                                    d_976570371==231311385 & d_663265240==231311385 ~ "All Surveys Completed",
                                                                  d_949302066==972455046 & d_536735468==972455046 & 
                                                                    d_976570371==972455046 & d_663265240==972455046 ~ "No Surveys Completed",
                                                                  TRUE ~ "Some Surveys Completed"),
                                   Number_Completed= case_when( (d_949302066==231311385 & d_536735468==231311385 & 
                                                                    d_976570371==231311385 & d_663265240==231311385) ~ "Four",
                                                               (d_949302066==972455046 & d_536735468==972455046 & 
                                                                    d_976570371==972455046 & d_663265240==972455046) ~ "Zero",
                                                                (d_949302066==231311385 & d_536735468!=231311385 & 
                                                                    d_976570371!=231311385 & d_663265240!=231311385) ~ "One",
                                                               ((d_949302066==231311385 & d_536735468==231311385 & 
                                                                    d_976570371!=231311385 & d_663265240!=231311385) | #mod2
                                                                 (d_949302066==231311385 & d_536735468!=231311385 & 
                                                                    d_976570371==231311385 & d_663265240!=231311385) | #mod3
                                                                 (d_949302066==231311385 & d_536735468!=231311385 & 
                                                                    d_976570371!=231311385 & d_663265240==231311385)) ~ "Two",  #mod4
                                                                 TRUE ~"Three"),
                                   #attempt = ifelse(attempt=="6th contact" | attempt=="7th Contact" | attempt=="8th Contact" | attempt=="9th contact", "6th contact or higher", attempt),
                                   buckets=case_when(Number_Completed=="Zero" ~ "None",
                                                     Number_Completed=="One" ~ "One",
                                                     Number_Completed=="Two" | Number_Completed=="Three" ~ "Some",
                                                     Number_Completed=="Four" ~ "All"))
reminders <- reminders %>%  mutate(contacts= case_when(attempt=="1st contact" & grepl("BL Survey Reminder", category) ~ "1st contact",
                                                      attempt=="2nd contact" & grepl("BL Survey Reminder", category) ~ "2nd contact",
                                                      attempt=="3rd contact" & grepl("BL Survey Reminder", category) ~ "3rd contact",
                                                      attempt=="4th contact" & grepl("BL Survey Reminder", category) ~ "4th contact",
                                                      attempt=="5th contact" & grepl("BL Survey Reminder", category) ~ "5th contact",
                                                      attempt=="6th contact" & grepl("BL Survey Reminder", category) ~ "6th contact",
                                                      TRUE ~ "Exclude"),
                                                      #(attempt=="7th Contact" | attempt=="7th contact" | attempt=="8th Contact" | attempt=="8th contact" | attempt=="9th contact"  | attempt=="10th contact")
                                                      #& grepl("BL Survey Reminders", category) ~ "Over 6 contacts",
                                                      #TRUE ~ "0 Contacts"),
                                   contacts_number= str_sub(contacts,1,1),
                                   last_attempt_max= contacts_number)




# 
reminders <- reminders %>% filter(contacts!="Exclude")

#Removing reminders 7+
reminders <- reminders %>%
  mutate(completed_before= case_when(last_attempt_max==0 ~ "Completed Before Verification",
                                     last_attempt_max==1 ~ "Completed Between Reminders 1 and 2",
                                     last_attempt_max==2 ~ "Completed Between Reminders 2 and 3",
                                     last_attempt_max==3 ~ "Completed Between Reminders 3 and 4",
                                     last_attempt_max==4 ~ "Completed Between Reminders 4 and 5",
                                     last_attempt_max==5 ~ "Completed Between Reminders 5 and 6",
                                     last_attempt_max==6 ~ "Completed After 6 Reminders",
                                     TRUE ~ "Error?"))







 reminders$completed_before <- factor(reminders$completed_before,levels=c("Completed Before Verification",  "Completed Between Reminders 1 and 2", "Completed Between Reminders 2 and 3", 
                                                                          "Completed Between Reminders 3 and 4","Completed Between Reminders 4 and 5", "Completed Between Reminders 5 and 6",
                                                                          "Completed After 6 Reminders" ))
reminders$All_Completed_Status <- factor(reminders$All_Completed_Status,levels=c("All Surveys Completed", "Some Surveys Completed", "No Surveys Completed"))
reminders$buckets <- factor(reminders$buckets,levels=c("None", "One", "Some", "All"))
reminders$Number_Completed <- factor(reminders$Number_Completed,levels=c("Zero", "One", "Two", "Three", "Four"))


#removing duplicate rows for participants with multiple reminders so they're not counted more than once
CID_reminders <- reminders %>% distinct(Connect_ID, .keep_all = TRUE)

                                
```



```{r, echo=FALSE, warning=FALSE, message=FALSE}


 all_participants <-  CID_reminders %>%
  group_by(Site) %>% tally() 


 table1<- all_participants %>% 
  gt() %>%
  tab_header(
    title = "Table 1: Total Participants Included in this Report, by Site"
  ) %>%
  fmt_number(columns = everything(), decimals = 0) %>%
  grand_summary_rows(columns=c(n),fns = ~sum(.,na.rm = T)) %>% 
tab_footnote(
  footnote=("The participants included in this report are active, verified, and have completed their User Profile between January 1, 2023 and October 1, 2023."),
  locations = cells_column_labels(columns = n)
)

 table1
 
 
#Removed this footnote- Note: Those who have refused baseline surveys or who have withdrawn from the cohort are excluded


```


\FloatBarrier
\newpage



```{r, echo=FALSE, include=FALSE}

## Eligible for reminder 4

check1 <- reminders %>%
  filter(reminders$d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & ifelse((as.Date(reminders$d_914594314) > "2023-03-11" & as.Date(reminders$d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days"))))

check1_filtered <- check1 %>% filter(days_difference>14) %>%  select(Connect_ID, verification_date, module_completion_date, days_difference)
dim(check1_filtered) #890 with & attempt=="4th contact"
length(check1_filtered$Connect_ID) #4630 without



check2 <- reminders %>%
  filter(reminders$d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & ifelse((as.Date(reminders$d_914594314) > "2023-03-11" & as.Date(reminders$d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days"))))

check2_filtered <- check2 %>% filter(days_difference>15) %>%  select(Connect_ID, verification_date, module_completion_date, days_difference)
dim(check2_filtered) #855, 4424 without attempt 4




check3 <- reminders %>% filter(d_100767870 == '104430631' & attempt=="4th contact") %>%  select(Connect_ID)
length(unique(check3$Connect_ID)) #3142 without contact 4, 3014 with


#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.

### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 









#sent3 <- CID_reminders %>% filter(attempt=="3rd contact") %>%  select(Connect_ID)
#sent_4 <- CID_reminders %>% filter(attempt=="4th contact") %>%  select(Connect_ID)
sent3 <- reminders %>% filter(attempt=="3rd contact") %>%  select(Connect_ID)
sent_4 <- reminders %>% filter(attempt=="4th contact") %>%  select(Connect_ID)


## Eligible for reminder 4

check1 <- reminders %>%
  filter(reminders$d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & ifelse((as.Date(reminders$d_914594314) > "2023-03-11" & as.Date(reminders$d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  ))

check1_filtered <- check1 %>% filter(time_frame=="Survey Completed after Contact 3, before Contact 4")  %>%  select(Connect_ID) %>%  distinct()
dim(check1_filtered) #1537
length(unique(check1_filtered$Connect_ID)) #530



check2 <- reminders %>%
  filter(reminders$d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & as.numeric(str_sub(d_914594314,12,13)) >=19) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  ))

check2_filtered <- check2 %>% filter(time_frame=="Survey Completed after Contact 3, before Contact 4") %>%  select(Connect_ID) %>%  distinct()
dim(check2_filtered) #1398
length(unique(check2_filtered$Connect_ID)) #671




check3 <- reminders %>% filter(d_100767870 == '104430631' & attempt=="4th contact") %>%  select(Connect_ID)
length(unique(check3$Connect_ID)) #3142 without contact 4, 3014 with


connect_ids_not_in_df2 <- anti_join(sent_4, check1_filtered, by = "Connect_ID")
connect_ids_not_in_df3 <- anti_join(connect_ids_not_in_df2, check2_filtered, by = "Connect_ID")
antijoin18 <- anti_join(sent_4, connect_ids_not_in_df3, by = "Connect_ID")







#comp_time <- reminders %>% mutate(timezone= case_when())



comp_time <- reminders %>%
  filter(reminders$d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & ifelse((as.Date(reminders$d_914594314) > "2023-03-11" & as.Date(reminders$d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- reminders %>%
  filter(reminders$d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & as.numeric(str_sub(d_914594314,12,13)) >=19) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")


```




```{r, echo=FALSE, warning=FALSE, message=FALSE}

#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.
### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 

## Easiest way to do this was to split the data into before 3pm verification and after 3pm verification and then combine them
#Also need to add daylight savings time. If verified between march and October, verification is 19:00UTC, if verified between November and February,  verification is 20:00UTC

comp_time <- reminders %>%
  filter(reminders$d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(reminders$d_914594314) > "2023-03-11" & as.Date(reminders$d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- reminders %>%
  filter(reminders$d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & #as.numeric(str_sub(d_914594314,12,13)) >=19) %>%
           ifelse((as.Date(reminders$d_914594314) > "2023-03-11" & as.Date(reminders$d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) >=19, as.numeric(str_sub(d_914594314,12,13)) >=20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")







reminders_ct <- reminders %>% mutate(cnt_number=case_when(attempt=="1st contact" ~ "Sent reminder email Contact 1",
                                                          attempt=="2nd contact" ~ "Sent reminder email Contact 2",
                                                          attempt=="3rd contact" ~ "Sent reminder email Contact 3",
                                                          attempt=="4th contact" ~ "Sent reminder email Contact 4",
                                                          attempt=="5th contact" ~ "Sent reminder email Contact 5",
                                                          attempt=="6th contact" ~ "Sent reminder email Contact 6"))
 attempt_counts <- reminders_ct %>%
     group_by(Connect_ID, cnt_number) %>%
     slice_head() %>%  # Keep only the first row for each unique Connect_ID and contacts_number- that way the case_when doesn't eliminate participants with each case
     group_by(cnt_number) %>%
     summarise(Count = n_distinct(Connect_ID))

Sent_rows <- data.frame(Column1 = attempt_counts$cnt_number, Column2 = attempt_counts$Count)
colnames(Sent_rows) <- c("All Reminders", "n")



#Sent previous contact - people who finished
EligibleList <- c("Eligible for reminder email Contact 2","Eligible for reminder email Contact 3", "Eligible for reminder email Contact 4", "Eligible for reminder email Contact 5", "Eligible for reminder email Contact 6")
EligibleNumb <- c(sum(all_participants$n)- (sum(comp_time_combined[1,2]) + sum(comp_time_combined[2,2])), #eligible2= all participants-those who completed before contact 2
                  Sent_rows[2,2] - sum(comp_time_combined[3,2]) , #eligible for 3= sent contact 2- completed before contact 3
                  Sent_rows[3,2] - sum(comp_time_combined[4,2]), #eligible for 4= sent contact3-completed before contact 4
                  Sent_rows[4,2] - sum(comp_time_combined[5,2]), #eligible for 5= sent contact4- completed before contact 5
                  Sent_rows[5,2] - sum(comp_time_combined[6,2])) #eligible for 6 =sent contact5-completed before contact 6


Eligible_rows <- data.frame(Column1 = EligibleList, Column2 = EligibleNumb)
colnames(Eligible_rows) <- c("All Reminders", "n")





final_notif_emails <- bind_rows(comp_time_combined, Sent_rows, Eligible_rows)
final_notif_emails <- final_notif_emails[c(8,1,2,14,9,3,15,10,4,16,11,5,17,12,6,18,13,7), ]



final_notif_emails$'%' <- c(paste(100*round(final_notif_emails[1,2]/sum(all_participants$n), digits=4), "%"),
                            paste(100*round(final_notif_emails[2,2]/sum(all_participants$n), digits=3), "%"), 
                            paste(100*round(final_notif_emails[3,2]/sum(all_participants$n), digits=3), "%"), 
                            paste(100*round(final_notif_emails[4,2]/sum(all_participants$n), digits=3), "%"), 
                            paste(100*round(final_notif_emails[5,2]/final_notif_emails[4,2], digits=3), "%"), 
                            paste(100*round(final_notif_emails[6,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[7,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[8,2]/final_notif_emails[7,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[9,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[10,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[11,2]/final_notif_emails[10,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[12,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[13,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[14,2]/final_notif_emails[13,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[15,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[16,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[17,2]/final_notif_emails[16,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[18,2]/final_notif_emails[17,2], digits=3), "%")) #b12




# Specify the rows to be bolded
bold_rows <- c(1,4,5,7,8,10,11,13,14,16,17)

final_notif_emails_gt <- as_tibble(final_notif_emails)

# Create a gt table and use text_transform to apply formatting
email_reminders <- final_notif_emails_gt %>% gt(rowname_col = "row_lab") %>%
  cols_label("All Reminders"= md(" "), n = md("**n**"), "%" = md("**%**")) %>% 
   tab_header(title = md("Table 2. Baseline Survey Email Reminders Evaluation, All Sites")) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "All Reminders",
      rows = bold_rows
    )) %>% 
#   tab_spanner(
#     label = "Footnote 1",
#     locations = cells_footnote(groups = "footnote1"),
#     value = "aseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted.."
#   ) %>%
#   tab_spanner(
#     label = "Footnote 2",
#     locations = cells_footnote(groups = "footnote2"),
#     value = "** Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."
#   )
# 
# email_reminders


tab_footnote(
  footnote=("Baseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."),
  locations = cells_column_labels(columns = "All Reminders")
)%>% 
 tab_footnote(
  footnote=("
'Eligible for reminder' is calculated as those sent the previous reminder minus those who completed the survey after the previous reminder."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
'Sent reminder' does not take into account whether email was successfully delivered or opened. A small percentage of Connect emails are undeliverable and the percent opened is unknown."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
' Email reminder schedule: Contact 1 is sent on day of verification or next day if verified after 3pm eastern; Contact 2 on day 3 post verification; Contact 3 on day 6 post verification; Contact 4 on day 15 post verification; Contact 5 on day 24 post verification; and Contact 6 on day 39 post verification."),
  locations = cells_column_labels(columns = "All Reminders")
) 

email_reminders
  
```





\newpage



```{r HealthPartners, echo=FALSE, warning=FALSE, message=FALSE}

## Same thing but by site 

HP_reminders <- reminders %>% filter(d_827220437=="452412599")


#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.
### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 

## Easiest way to do this was to say use the date of verification if they were verified before 3pm, use the day before if they were verified after 3pm, that way we don't need to add 1 to each case.
# Essentially we're ading a day to verification, so take that away and the post-verification dates should allign

comp_time <- HP_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- HP_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) >=19, as.numeric(str_sub(d_914594314,12,13)) >=20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")






reminders_ct <- HP_reminders %>% mutate(cnt_number=case_when(attempt=="1st contact" ~ "Sent reminder email Contact 1",
                                                          attempt=="2nd contact" ~ "Sent reminder email Contact 2",
                                                          attempt=="3rd contact" ~ "Sent reminder email Contact 3",
                                                          attempt=="4th contact" ~ "Sent reminder email Contact 4",
                                                          attempt=="5th contact" ~ "Sent reminder email Contact 5",
                                                          attempt=="6th contact" ~ "Sent reminder email Contact 6"))
 attempt_counts <- reminders_ct %>%
     group_by(Connect_ID, cnt_number) %>%
     slice_head() %>%  # Keep only the first row for each unique Connect_ID and contacts_number- that way the case_when doesn't eliminate participants with each case
     group_by(cnt_number) %>%
     summarise(Count = n_distinct(Connect_ID))

Sent_rows <- data.frame(Column1 = attempt_counts$cnt_number, Column2 = attempt_counts$Count)
colnames(Sent_rows) <- c("All Reminders", "n")



#Sent previous contact - people who finished
EligibleList <- c("Eligible for reminder email Contact 2","Eligible for reminder email Contact 3", "Eligible for reminder email Contact 4", "Eligible for reminder email Contact 5", "Eligible for reminder email Contact 6")
EligibleNumb <- c(length(unique(HP_reminders$Connect_ID))- (sum(comp_time_combined[1,2]) + sum(comp_time_combined[2,2])), #eligible2= all participants-those who completed before contact 2
                  Sent_rows[2,2] - sum(comp_time_combined[3,2]) , #eligible for 3= sent contact 2- completed before contact 3
                  Sent_rows[3,2] - sum(comp_time_combined[4,2]), #eligible for 4= sent contact3-completed before contact 4
                  Sent_rows[4,2] - sum(comp_time_combined[5,2]), #eligible for 5= sent contact4- completed before contact 5
                  Sent_rows[5,2] - sum(comp_time_combined[6,2])) #eligible for 6 =sent contact5-completed before contact 6


Eligible_rows <- data.frame(Column1 = EligibleList, Column2 = EligibleNumb)
colnames(Eligible_rows) <- c("All Reminders", "n")




final_notif_emails <- bind_rows(comp_time_combined, Sent_rows, Eligible_rows)
final_notif_emails <- final_notif_emails[c(8,1,2,14,9,3,15,10,4,16,11,5,17,12,6,18,13,7), ]



final_notif_emails$'%' <- c(paste(100*round(final_notif_emails[1,2]/length(unique(HP_reminders$Connect_ID)), digits=4), "%"),
                            paste(100*round(final_notif_emails[2,2]/length(unique(HP_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[3,2]/length(unique(HP_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[4,2]/length(unique(HP_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[5,2]/final_notif_emails[4,2], digits=3), "%"), 
                            paste(100*round(final_notif_emails[6,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[7,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[8,2]/final_notif_emails[7,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[9,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[10,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[11,2]/final_notif_emails[10,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[12,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[13,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[14,2]/final_notif_emails[13,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[15,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[16,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[17,2]/final_notif_emails[16,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[18,2]/final_notif_emails[17,2], digits=3), "%")) #b12




# Specify the rows to be bolded
bold_rows <- c(1,4,5,7,8,10,11,13,14,16,17)

final_notif_emails_gt <- as_tibble(final_notif_emails)

# Create a gt table and use text_transform to apply formatting
email_reminders <- final_notif_emails_gt %>% gt(rowname_col = "row_lab") %>%
  cols_label("All Reminders"= md(" "), n = md("**n**"), "%" = md("**%**")) %>% 
   tab_header(title = md("Table 2.1 Baseline Survey Email Reminders Evaluation, HealthPartners")) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "All Reminders",
      rows = bold_rows
    )) %>% 
#   tab_spanner(
#     label = "Footnote 1",
#     locations = cells_footnote(groups = "footnote1"),
#     value = "aseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted.."
#   ) %>%
#   tab_spanner(
#     label = "Footnote 2",
#     locations = cells_footnote(groups = "footnote2"),
#     value = "** Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."
#   )
# 
# email_reminders


tab_footnote(
  footnote=("Baseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."),
  locations = cells_column_labels(columns = "All Reminders")
)%>% 
 tab_footnote(
  footnote=("
'Eligible for reminder' is calculated as those sent the previous reminder minus those who completed the survey after the previous reminder."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
'Sent reminder' does not take into account whether email was successfully delivered or opened. A small percentage of Connect emails are undeliverable and the percent opened is unknown."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
' Email reminder schedule: Contact 1 is sent on day of verification or next day if verified after 3pm eastern; Contact 2 on day 3 post verification; Contact 3 on day 6 post verification; Contact 4 on day 15 post verification; Contact 5 on day 24 post verification; and Contact 6 on day 39 post verification."),
  locations = cells_column_labels(columns = "All Reminders")
) 

email_reminders
  
```

\newpage

```{r Henry Ford, echo=FALSE, warning=FALSE, message=FALSE}

## Same thing but by site 

HF_reminders <- reminders %>% filter(d_827220437=="548392715")

#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.
### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 

## Easiest way to do this was to say use the date of verification if they were verified before 3pm, use the day before if they were verified after 3pm, that way we don't need to add 1 to each case.
# Essentially we're ading a day to verification, so take that away and the post-verification dates should allign


comp_time <- HF_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- HF_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) >=19, as.numeric(str_sub(d_914594314,12,13)) >=20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")






reminders_ct <- HF_reminders %>% mutate(cnt_number=case_when(attempt=="1st contact" ~ "Sent reminder email Contact 1",
                                                          attempt=="2nd contact" ~ "Sent reminder email Contact 2",
                                                          attempt=="3rd contact" ~ "Sent reminder email Contact 3",
                                                          attempt=="4th contact" ~ "Sent reminder email Contact 4",
                                                          attempt=="5th contact" ~ "Sent reminder email Contact 5",
                                                          attempt=="6th contact" ~ "Sent reminder email Contact 6"))
 attempt_counts <- reminders_ct %>%
     group_by(Connect_ID, cnt_number) %>%
     slice_head() %>%  # Keep only the first row for each unique Connect_ID and contacts_number- that way the case_when doesn't eliminate participants with each case
     group_by(cnt_number) %>%
     summarise(Count = n_distinct(Connect_ID))

Sent_rows <- data.frame(Column1 = attempt_counts$cnt_number, Column2 = attempt_counts$Count)
colnames(Sent_rows) <- c("All Reminders", "n")



#Sent previous contact - people who finished
EligibleList <- c("Eligible for reminder email Contact 2","Eligible for reminder email Contact 3", "Eligible for reminder email Contact 4", "Eligible for reminder email Contact 5", "Eligible for reminder email Contact 6")
EligibleNumb <- c(length(unique(HF_reminders$Connect_ID))- (sum(comp_time_combined[1,2]) + sum(comp_time_combined[2,2])), #eligible2= all participants-those who completed before contact 2
                  Sent_rows[2,2] - sum(comp_time_combined[3,2]) , #eligible for 3= sent contact 2- completed before contact 3
                  Sent_rows[3,2] - sum(comp_time_combined[4,2]), #eligible for 4= sent contact3-completed before contact 4
                  Sent_rows[4,2] - sum(comp_time_combined[5,2]), #eligible for 5= sent contact4- completed before contact 5
                  Sent_rows[5,2] - sum(comp_time_combined[6,2])) #eligible for 6 =sent contact5-completed before contact 6


Eligible_rows <- data.frame(Column1 = EligibleList, Column2 = EligibleNumb)
colnames(Eligible_rows) <- c("All Reminders", "n")




final_notif_emails <- bind_rows(comp_time_combined, Sent_rows, Eligible_rows)
final_notif_emails <- final_notif_emails[c(8,1,2,14,9,3,15,10,4,16,11,5,17,12,6,18,13,7), ]



final_notif_emails$'%' <- c(paste(100*round(final_notif_emails[1,2]/length(unique(HF_reminders$Connect_ID)), digits=4), "%"),
                            paste(100*round(final_notif_emails[2,2]/length(unique(HF_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[3,2]/length(unique(HF_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[4,2]/length(unique(HF_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[5,2]/final_notif_emails[4,2], digits=3), "%"), 
                            paste(100*round(final_notif_emails[6,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[7,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[8,2]/final_notif_emails[7,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[9,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[10,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[11,2]/final_notif_emails[10,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[12,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[13,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[14,2]/final_notif_emails[13,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[15,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[16,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[17,2]/final_notif_emails[16,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[18,2]/final_notif_emails[17,2], digits=3), "%")) #b12




# Specify the rows to be bolded
bold_rows <- c(1,4,5,7,8,10,11,13,14,16,17)

final_notif_emails_gt <- as_tibble(final_notif_emails)

# Create a gt table and use text_transform to apply formatting
email_reminders <- final_notif_emails_gt %>% gt(rowname_col = "row_lab") %>%
  cols_label("All Reminders"= md(" "), n = md("**n**"), "%" = md("**%**")) %>% 
   tab_header(title = md("Table 2.2 Baseline Survey Email Reminders Evaluation, Henry Ford Health")) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "All Reminders",
      rows = bold_rows
    )) %>% 
#   tab_spanner(
#     label = "Footnote 1",
#     locations = cells_footnote(groups = "footnote1"),
#     value = "aseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted.."
#   ) %>%
#   tab_spanner(
#     label = "Footnote 2",
#     locations = cells_footnote(groups = "footnote2"),
#     value = "** Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."
#   )
# 
# email_reminders


tab_footnote(
  footnote=("Baseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."),
  locations = cells_column_labels(columns = "All Reminders")
)%>% 
 tab_footnote(
  footnote=("
'Eligible for reminder' is calculated as those sent the previous reminder minus those who completed the survey after the previous reminder."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
'Sent reminder' does not take into account whether email was successfully delivered or opened. A small percentage of Connect emails are undeliverable and the percent opened is unknown."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
' Email reminder schedule: Contact 1 is sent on day of verification or next day if verified after 3pm eastern; Contact 2 on day 3 post verification; Contact 3 on day 6 post verification; Contact 4 on day 15 post verification; Contact 5 on day 24 post verification; and Contact 6 on day 39 post verification."),
  locations = cells_column_labels(columns = "All Reminders")
) 

email_reminders
  
```
\newpage

```{r KPCO, echo=FALSE, warning=FALSE, message=FALSE}

## Same thing but by site 

KPCO_reminders <- reminders %>% filter(d_827220437=="125001209")

#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.
### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 

## Easiest way to do this was to say use the date of verification if they were verified before 3pm, use the day before if they were verified after 3pm, that way we don't need to add 1 to each case.
# Essentially we're ading a day to verification, so take that away and the post-verification dates should allign


comp_time <- KPCO_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- KPCO_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) >=19, as.numeric(str_sub(d_914594314,12,13)) >=20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")






reminders_ct <- KPCO_reminders %>% mutate(cnt_number=case_when(attempt=="1st contact" ~ "Sent reminder email Contact 1",
                                                          attempt=="2nd contact" ~ "Sent reminder email Contact 2",
                                                          attempt=="3rd contact" ~ "Sent reminder email Contact 3",
                                                          attempt=="4th contact" ~ "Sent reminder email Contact 4",
                                                          attempt=="5th contact" ~ "Sent reminder email Contact 5",
                                                          attempt=="6th contact" ~ "Sent reminder email Contact 6"))
 attempt_counts <- reminders_ct %>%
     group_by(Connect_ID, cnt_number) %>%
     slice_head() %>%  # Keep only the first row for each unique Connect_ID and contacts_number- that way the case_when doesn't eliminate participants with each case
     group_by(cnt_number) %>%
     summarise(Count = n_distinct(Connect_ID))

Sent_rows <- data.frame(Column1 = attempt_counts$cnt_number, Column2 = attempt_counts$Count)
colnames(Sent_rows) <- c("All Reminders", "n")



#Sent previous contact - people who finished
EligibleList <- c("Eligible for reminder email Contact 2","Eligible for reminder email Contact 3", "Eligible for reminder email Contact 4", "Eligible for reminder email Contact 5", "Eligible for reminder email Contact 6")
EligibleNumb <- c(length(unique(KPCO_reminders$Connect_ID))- (sum(comp_time_combined[1,2]) + sum(comp_time_combined[2,2])), #eligible2= all participants-those who completed before contact 2
                  Sent_rows[2,2] - sum(comp_time_combined[3,2]) , #eligible for 3= sent contact 2- completed before contact 3
                  Sent_rows[3,2] - sum(comp_time_combined[4,2]), #eligible for 4= sent contact3-completed before contact 4
                  Sent_rows[4,2] - sum(comp_time_combined[5,2]), #eligible for 5= sent contact4- completed before contact 5
                  Sent_rows[5,2] - sum(comp_time_combined[6,2])) #eligible for 6 =sent contact5-completed before contact 6


Eligible_rows <- data.frame(Column1 = EligibleList, Column2 = EligibleNumb)
colnames(Eligible_rows) <- c("All Reminders", "n")




final_notif_emails <- bind_rows(comp_time_combined, Sent_rows, Eligible_rows)
final_notif_emails <- final_notif_emails[c(8,1,2,14,9,3,15,10,4,16,11,5,17,12,6,18,13,7), ]



final_notif_emails$'%' <- c(paste(100*round(final_notif_emails[1,2]/length(unique(KPCO_reminders$Connect_ID)), digits=4), "%"),
                            paste(100*round(final_notif_emails[2,2]/length(unique(KPCO_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[3,2]/length(unique(KPCO_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[4,2]/length(unique(KPCO_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[5,2]/final_notif_emails[4,2], digits=3), "%"), 
                            paste(100*round(final_notif_emails[6,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[7,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[8,2]/final_notif_emails[7,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[9,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[10,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[11,2]/final_notif_emails[10,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[12,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[13,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[14,2]/final_notif_emails[13,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[15,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[16,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[17,2]/final_notif_emails[16,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[18,2]/final_notif_emails[17,2], digits=3), "%")) #b12




# Specify the rows to be bolded
bold_rows <- c(1,4,5,7,8,10,11,13,14,16,17)

final_notif_emails_gt <- as_tibble(final_notif_emails)

# Create a gt table and use text_transform to apply formatting
email_reminders <- final_notif_emails_gt %>% gt(rowname_col = "row_lab") %>%
  cols_label("All Reminders"= md(" "), n = md("**n**"), "%" = md("**%**")) %>% 
   tab_header(title = md("Table 2.3 Baseline Survey Email Reminders Evaluation, Kaiser Permanente Colorado")) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "All Reminders",
      rows = bold_rows
    )) %>% 
#   tab_spanner(
#     label = "Footnote 1",
#     locations = cells_footnote(groups = "footnote1"),
#     value = "aseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted.."
#   ) %>%
#   tab_spanner(
#     label = "Footnote 2",
#     locations = cells_footnote(groups = "footnote2"),
#     value = "** Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."
#   )
# 
# email_reminders


tab_footnote(
  footnote=("Baseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."),
  locations = cells_column_labels(columns = "All Reminders")
)%>% 
 tab_footnote(
  footnote=("
'Eligible for reminder' is calculated as those sent the previous reminder minus those who completed the survey after the previous reminder."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
'Sent reminder' does not take into account whether email was successfully delivered or opened. A small percentage of Connect emails are undeliverable and the percent opened is unknown."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
' Email reminder schedule: Contact 1 is sent on day of verification or next day if verified after 3pm eastern; Contact 2 on day 3 post verification; Contact 3 on day 6 post verification; Contact 4 on day 15 post verification; Contact 5 on day 24 post verification; and Contact 6 on day 39 post verification."),
  locations = cells_column_labels(columns = "All Reminders")
) 

email_reminders
  
```

\newpage

```{r KPGA, echo=FALSE, warning=FALSE, message=FALSE}

## Same thing but by site 

KPGA_reminders <- reminders %>% filter(d_827220437=="327912200")

#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.
### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 

## Easiest way to do this was to say use the date of verification if they were verified before 3pm, use the day before if they were verified after 3pm, that way we don't need to add 1 to each case.
# Essentially we're ading a day to verification, so take that away and the post-verification dates should allign


comp_time <- KPGA_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- KPGA_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) >=19, as.numeric(str_sub(d_914594314,12,13)) >=20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")






reminders_ct <- KPGA_reminders %>% mutate(cnt_number=case_when(attempt=="1st contact" ~ "Sent reminder email Contact 1",
                                                          attempt=="2nd contact" ~ "Sent reminder email Contact 2",
                                                          attempt=="3rd contact" ~ "Sent reminder email Contact 3",
                                                          attempt=="4th contact" ~ "Sent reminder email Contact 4",
                                                          attempt=="5th contact" ~ "Sent reminder email Contact 5",
                                                          attempt=="6th contact" ~ "Sent reminder email Contact 6"))
 attempt_counts <- reminders_ct %>%
     group_by(Connect_ID, cnt_number) %>%
     slice_head() %>%  # Keep only the first row for each unique Connect_ID and contacts_number- that way the case_when doesn't eliminate participants with each case
     group_by(cnt_number) %>%
     summarise(Count = n_distinct(Connect_ID))

Sent_rows <- data.frame(Column1 = attempt_counts$cnt_number, Column2 = attempt_counts$Count)
colnames(Sent_rows) <- c("All Reminders", "n")



#Sent previous contact - people who finished
EligibleList <- c("Eligible for reminder email Contact 2","Eligible for reminder email Contact 3", "Eligible for reminder email Contact 4", "Eligible for reminder email Contact 5", "Eligible for reminder email Contact 6")
EligibleNumb <- c(length(unique(KPGA_reminders$Connect_ID))- (sum(comp_time_combined[1,2]) + sum(comp_time_combined[2,2])), #eligible2= all participants-those who completed before contact 2
                  Sent_rows[2,2] - sum(comp_time_combined[3,2]) , #eligible for 3= sent contact 2- completed before contact 3
                  Sent_rows[3,2] - sum(comp_time_combined[4,2]), #eligible for 4= sent contact3-completed before contact 4
                  Sent_rows[4,2] - sum(comp_time_combined[5,2]), #eligible for 5= sent contact4- completed before contact 5
                  Sent_rows[5,2] - sum(comp_time_combined[6,2])) #eligible for 6 =sent contact5-completed before contact 6


Eligible_rows <- data.frame(Column1 = EligibleList, Column2 = EligibleNumb)
colnames(Eligible_rows) <- c("All Reminders", "n")




final_notif_emails <- bind_rows(comp_time_combined, Sent_rows, Eligible_rows)
final_notif_emails <- final_notif_emails[c(8,1,2,14,9,3,15,10,4,16,11,5,17,12,6,18,13,7), ]



final_notif_emails$'%' <- c(paste(100*round(final_notif_emails[1,2]/length(unique(KPGA_reminders$Connect_ID)), digits=4), "%"),
                            paste(100*round(final_notif_emails[2,2]/length(unique(KPGA_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[3,2]/length(unique(KPGA_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[4,2]/length(unique(KPGA_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[5,2]/final_notif_emails[4,2], digits=3), "%"), 
                            paste(100*round(final_notif_emails[6,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[7,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[8,2]/final_notif_emails[7,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[9,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[10,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[11,2]/final_notif_emails[10,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[12,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[13,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[14,2]/final_notif_emails[13,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[15,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[16,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[17,2]/final_notif_emails[16,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[18,2]/final_notif_emails[17,2], digits=3), "%")) #b12




# Specify the rows to be bolded
bold_rows <- c(1,4,5,7,8,10,11,13,14,16,17)

final_notif_emails_gt <- as_tibble(final_notif_emails)

# Create a gt table and use text_transform to apply formatting
email_reminders <- final_notif_emails_gt %>% gt(rowname_col = "row_lab") %>%
  cols_label("All Reminders"= md(" "), n = md("**n**"), "%" = md("**%**")) %>% 
   tab_header(title = md("Table 2.4 Baseline Survey Email Reminders Evaluation, Kaiser Permanente Georgia")) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "All Reminders",
      rows = bold_rows
    )) %>% 
#   tab_spanner(
#     label = "Footnote 1",
#     locations = cells_footnote(groups = "footnote1"),
#     value = "aseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted.."
#   ) %>%
#   tab_spanner(
#     label = "Footnote 2",
#     locations = cells_footnote(groups = "footnote2"),
#     value = "** Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."
#   )
# 
# email_reminders


tab_footnote(
  footnote=("Baseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."),
  locations = cells_column_labels(columns = "All Reminders")
)%>% 
 tab_footnote(
  footnote=("
'Eligible for reminder' is calculated as those sent the previous reminder minus those who completed the survey after the previous reminder."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
'Sent reminder' does not take into account whether email was successfully delivered or opened. A small percentage of Connect emails are undeliverable and the percent opened is unknown."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
' Email reminder schedule: Contact 1 is sent on day of verification or next day if verified after 3pm eastern; Contact 2 on day 3 post verification; Contact 3 on day 6 post verification; Contact 4 on day 15 post verification; Contact 5 on day 24 post verification; and Contact 6 on day 39 post verification."),
  locations = cells_column_labels(columns = "All Reminders")
) 

email_reminders
  
```

\newpage

```{r KPHI, echo=FALSE, warning=FALSE, message=FALSE}

## Same thing but by site 

KPHI_reminders <- reminders %>% filter(d_827220437=="300267574")

#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.
### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 

## Easiest way to do this was to say use the date of verification if they were verified before 3pm, use the day before if they were verified after 3pm, that way we don't need to add 1 to each case.
# Essentially we're ading a day to verification, so take that away and the post-verification dates should allign


comp_time <- KPHI_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- KPHI_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) >=19, as.numeric(str_sub(d_914594314,12,13)) >=20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")






reminders_ct <- KPHI_reminders %>% mutate(cnt_number=case_when(attempt=="1st contact" ~ "Sent reminder email Contact 1",
                                                          attempt=="2nd contact" ~ "Sent reminder email Contact 2",
                                                          attempt=="3rd contact" ~ "Sent reminder email Contact 3",
                                                          attempt=="4th contact" ~ "Sent reminder email Contact 4",
                                                          attempt=="5th contact" ~ "Sent reminder email Contact 5",
                                                          attempt=="6th contact" ~ "Sent reminder email Contact 6"))
 attempt_counts <- reminders_ct %>%
     group_by(Connect_ID, cnt_number) %>%
     slice_head() %>%  # Keep only the first row for each unique Connect_ID and contacts_number- that way the case_when doesn't eliminate participants with each case
     group_by(cnt_number) %>%
     summarise(Count = n_distinct(Connect_ID))

Sent_rows <- data.frame(Column1 = attempt_counts$cnt_number, Column2 = attempt_counts$Count)
colnames(Sent_rows) <- c("All Reminders", "n")



#Sent previous contact - people who finished
EligibleList <- c("Eligible for reminder email Contact 2","Eligible for reminder email Contact 3", "Eligible for reminder email Contact 4", "Eligible for reminder email Contact 5", "Eligible for reminder email Contact 6")
EligibleNumb <- c(length(unique(KPHI_reminders$Connect_ID))- (sum(comp_time_combined[1,2]) + sum(comp_time_combined[2,2])), #eligible2= all participants-those who completed before contact 2
                  Sent_rows[2,2] - sum(comp_time_combined[3,2]) , #eligible for 3= sent contact 2- completed before contact 3
                  Sent_rows[3,2] - sum(comp_time_combined[4,2]), #eligible for 4= sent contact3-completed before contact 4
                  Sent_rows[4,2] - sum(comp_time_combined[5,2]), #eligible for 5= sent contact4- completed before contact 5
                  Sent_rows[5,2] - sum(comp_time_combined[6,2])) #eligible for 6 =sent contact5-completed before contact 6


Eligible_rows <- data.frame(Column1 = EligibleList, Column2 = EligibleNumb)
colnames(Eligible_rows) <- c("All Reminders", "n")




final_notif_emails <- bind_rows(comp_time_combined, Sent_rows, Eligible_rows)
final_notif_emails <- final_notif_emails[c(8,1,2,14,9,3,15,10,4,16,11,5,17,12,6,18,13,7), ]



final_notif_emails$'%' <- c(paste(100*round(final_notif_emails[1,2]/length(unique(KPHI_reminders$Connect_ID)), digits=4), "%"),
                            paste(100*round(final_notif_emails[2,2]/length(unique(KPHI_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[3,2]/length(unique(KPHI_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[4,2]/length(unique(KPHI_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[5,2]/final_notif_emails[4,2], digits=3), "%"), 
                            paste(100*round(final_notif_emails[6,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[7,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[8,2]/final_notif_emails[7,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[9,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[10,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[11,2]/final_notif_emails[10,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[12,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[13,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[14,2]/final_notif_emails[13,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[15,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[16,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[17,2]/final_notif_emails[16,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[18,2]/final_notif_emails[17,2], digits=3), "%")) #b12




# Specify the rows to be bolded
bold_rows <- c(1,4,5,7,8,10,11,13,14,16,17)

final_notif_emails_gt <- as_tibble(final_notif_emails)

# Create a gt table and use text_transform to apply formatting
email_reminders <- final_notif_emails_gt %>% gt(rowname_col = "row_lab") %>%
  cols_label("All Reminders"= md(" "), n = md("**n**"), "%" = md("**%**")) %>% 
   tab_header(title = md("Table 2.5 Baseline Survey Email Reminders Evaluation, Kaiser Permanente Hawaii")) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "All Reminders",
      rows = bold_rows
    )) %>% 
#   tab_spanner(
#     label = "Footnote 1",
#     locations = cells_footnote(groups = "footnote1"),
#     value = "aseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted.."
#   ) %>%
#   tab_spanner(
#     label = "Footnote 2",
#     locations = cells_footnote(groups = "footnote2"),
#     value = "** Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."
#   )
# 
# email_reminders


tab_footnote(
  footnote=("Baseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."),
  locations = cells_column_labels(columns = "All Reminders")
)%>% 
 tab_footnote(
  footnote=("
'Eligible for reminder' is calculated as those sent the previous reminder minus those who completed the survey after the previous reminder."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
'Sent reminder' does not take into account whether email was successfully delivered or opened. A small percentage of Connect emails are undeliverable and the percent opened is unknown."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
' Email reminder schedule: Contact 1 is sent on day of verification or next day if verified after 3pm eastern; Contact 2 on day 3 post verification; Contact 3 on day 6 post verification; Contact 4 on day 15 post verification; Contact 5 on day 24 post verification; and Contact 6 on day 39 post verification."),
  locations = cells_column_labels(columns = "All Reminders")
) 

email_reminders
  
```

\newpage 

```{r KPNW, echo=FALSE, warning=FALSE, message=FALSE}

## Same thing but by site 

KPNW_reminders <- reminders %>% filter(d_827220437=="452412599")

#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.
### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 

## Easiest way to do this was to say use the date of verification if they were verified before 3pm, use the day before if they were verified after 3pm, that way we don't need to add 1 to each case.
# Essentially we're ading a day to verification, so take that away and the post-verification dates should allign


comp_time <- KPNW_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- KPNW_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) >=19, as.numeric(str_sub(d_914594314,12,13)) >=20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")






reminders_ct <- KPNW_reminders %>% mutate(cnt_number=case_when(attempt=="1st contact" ~ "Sent reminder email Contact 1",
                                                          attempt=="2nd contact" ~ "Sent reminder email Contact 2",
                                                          attempt=="3rd contact" ~ "Sent reminder email Contact 3",
                                                          attempt=="4th contact" ~ "Sent reminder email Contact 4",
                                                          attempt=="5th contact" ~ "Sent reminder email Contact 5",
                                                          attempt=="6th contact" ~ "Sent reminder email Contact 6"))
 attempt_counts <- reminders_ct %>%
     group_by(Connect_ID, cnt_number) %>%
     slice_head() %>%  # Keep only the first row for each unique Connect_ID and contacts_number- that way the case_when doesn't eliminate participants with each case
     group_by(cnt_number) %>%
     summarise(Count = n_distinct(Connect_ID))

Sent_rows <- data.frame(Column1 = attempt_counts$cnt_number, Column2 = attempt_counts$Count)
colnames(Sent_rows) <- c("All Reminders", "n")



#Sent previous contact - people who finished
EligibleList <- c("Eligible for reminder email Contact 2","Eligible for reminder email Contact 3", "Eligible for reminder email Contact 4", "Eligible for reminder email Contact 5", "Eligible for reminder email Contact 6")
EligibleNumb <- c(length(unique(KPNW_reminders$Connect_ID))- (sum(comp_time_combined[1,2]) + sum(comp_time_combined[2,2])), #eligible2= all participants-those who completed before contact 2
                  Sent_rows[2,2] - sum(comp_time_combined[3,2]) , #eligible for 3= sent contact 2- completed before contact 3
                  Sent_rows[3,2] - sum(comp_time_combined[4,2]), #eligible for 4= sent contact3-completed before contact 4
                  Sent_rows[4,2] - sum(comp_time_combined[5,2]), #eligible for 5= sent contact4- completed before contact 5
                  Sent_rows[5,2] - sum(comp_time_combined[6,2])) #eligible for 6 =sent contact5-completed before contact 6


Eligible_rows <- data.frame(Column1 = EligibleList, Column2 = EligibleNumb)
colnames(Eligible_rows) <- c("All Reminders", "n")




final_notif_emails <- bind_rows(comp_time_combined, Sent_rows, Eligible_rows)
final_notif_emails <- final_notif_emails[c(8,1,2,14,9,3,15,10,4,16,11,5,17,12,6,18,13,7), ]



final_notif_emails$'%' <- c(paste(100*round(final_notif_emails[1,2]/length(unique(KPNW_reminders$Connect_ID)), digits=4), "%"),
                            paste(100*round(final_notif_emails[2,2]/length(unique(KPNW_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[3,2]/length(unique(KPNW_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[4,2]/length(unique(KPNW_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[5,2]/final_notif_emails[4,2], digits=3), "%"), 
                            paste(100*round(final_notif_emails[6,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[7,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[8,2]/final_notif_emails[7,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[9,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[10,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[11,2]/final_notif_emails[10,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[12,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[13,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[14,2]/final_notif_emails[13,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[15,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[16,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[17,2]/final_notif_emails[16,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[18,2]/final_notif_emails[17,2], digits=3), "%")) #b12




# Specify the rows to be bolded
bold_rows <- c(1,4,5,7,8,10,11,13,14,16,17)

final_notif_emails_gt <- as_tibble(final_notif_emails)

# Create a gt table and use text_transform to apply formatting
email_reminders <- final_notif_emails_gt %>% gt(rowname_col = "row_lab") %>%
  cols_label("All Reminders"= md(" "), n = md("**n**"), "%" = md("**%**")) %>% 
   tab_header(title = md("Table 2.6 Baseline Survey Email Reminders Evaluation, \n Kaiser Permanente Northwest")) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "All Reminders",
      rows = bold_rows
    )) %>% 
#   tab_spanner(
#     label = "Footnote 1",
#     locations = cells_footnote(groups = "footnote1"),
#     value = "aseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted.."
#   ) %>%
#   tab_spanner(
#     label = "Footnote 2",
#     locations = cells_footnote(groups = "footnote2"),
#     value = "** Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."
#   )
# 
# email_reminders


tab_footnote(
  footnote=("Baseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."),
  locations = cells_column_labels(columns = "All Reminders")
)%>% 
 tab_footnote(
  footnote=("
'Eligible for reminder' is calculated as those sent the previous reminder minus those who completed the survey after the previous reminder."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
'Sent reminder' does not take into account whether email was successfully delivered or opened. A small percentage of Connect emails are undeliverable and the percent opened is unknown."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
' Email reminder schedule: Contact 1 is sent on day of verification or next day if verified after 3pm eastern; Contact 2 on day 3 post verification; Contact 3 on day 6 post verification; Contact 4 on day 15 post verification; Contact 5 on day 24 post verification; and Contact 6 on day 39 post verification."),
  locations = cells_column_labels(columns = "All Reminders")
) 

email_reminders
  
```

\newpage

```{r Marshfield, echo=FALSE, warning=FALSE, message=FALSE}

## Same thing but by site 

MF_reminders <- reminders %>% filter(d_827220437=="303349821")

#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.
### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 

## Easiest way to do this was to say use the date of verification if they were verified before 3pm, use the day before if they were verified after 3pm, that way we don't need to add 1 to each case.
# Essentially we're ading a day to verification, so take that away and the post-verification dates should allign


comp_time <- MF_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- MF_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) >=19, as.numeric(str_sub(d_914594314,12,13)) >=20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")






reminders_ct <- MF_reminders %>% mutate(cnt_number=case_when(attempt=="1st contact" ~ "Sent reminder email Contact 1",
                                                          attempt=="2nd contact" ~ "Sent reminder email Contact 2",
                                                          attempt=="3rd contact" ~ "Sent reminder email Contact 3",
                                                          attempt=="4th contact" ~ "Sent reminder email Contact 4",
                                                          attempt=="5th contact" ~ "Sent reminder email Contact 5",
                                                          attempt=="6th contact" ~ "Sent reminder email Contact 6"))
 attempt_counts <- reminders_ct %>%
     group_by(Connect_ID, cnt_number) %>%
     slice_head() %>%  # Keep only the first row for each unique Connect_ID and contacts_number- that way the case_when doesn't eliminate participants with each case
     group_by(cnt_number) %>%
     summarise(Count = n_distinct(Connect_ID))

Sent_rows <- data.frame(Column1 = attempt_counts$cnt_number, Column2 = attempt_counts$Count)
colnames(Sent_rows) <- c("All Reminders", "n")



#Sent previous contact - people who finished
EligibleList <- c("Eligible for reminder email Contact 2","Eligible for reminder email Contact 3", "Eligible for reminder email Contact 4", "Eligible for reminder email Contact 5", "Eligible for reminder email Contact 6")
EligibleNumb <- c(length(unique(MF_reminders$Connect_ID))- (sum(comp_time_combined[1,2]) + sum(comp_time_combined[2,2])), #eligible2= all participants-those who completed before contact 2
                  Sent_rows[2,2] - sum(comp_time_combined[3,2]) , #eligible for 3= sent contact 2- completed before contact 3
                  Sent_rows[3,2] - sum(comp_time_combined[4,2]), #eligible for 4= sent contact3-completed before contact 4
                  Sent_rows[4,2] - sum(comp_time_combined[5,2]), #eligible for 5= sent contact4- completed before contact 5
                  Sent_rows[5,2] - sum(comp_time_combined[6,2])) #eligible for 6 =sent contact5-completed before contact 6


Eligible_rows <- data.frame(Column1 = EligibleList, Column2 = EligibleNumb)
colnames(Eligible_rows) <- c("All Reminders", "n")




final_notif_emails <- bind_rows(comp_time_combined, Sent_rows, Eligible_rows)
final_notif_emails <- final_notif_emails[c(8,1,2,14,9,3,15,10,4,16,11,5,17,12,6,18,13,7), ]



final_notif_emails$'%' <- c(paste(100*round(final_notif_emails[1,2]/length(unique(MF_reminders$Connect_ID)), digits=4), "%"),
                            paste(100*round(final_notif_emails[2,2]/length(unique(MF_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[3,2]/length(unique(MF_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[4,2]/length(unique(MF_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[5,2]/final_notif_emails[4,2], digits=3), "%"), 
                            paste(100*round(final_notif_emails[6,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[7,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[8,2]/final_notif_emails[7,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[9,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[10,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[11,2]/final_notif_emails[10,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[12,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[13,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[14,2]/final_notif_emails[13,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[15,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[16,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[17,2]/final_notif_emails[16,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[18,2]/final_notif_emails[17,2], digits=3), "%")) #b12




# Specify the rows to be bolded
bold_rows <- c(1,4,5,7,8,10,11,13,14,16,17)

final_notif_emails_gt <- as_tibble(final_notif_emails)

# Create a gt table and use text_transform to apply formatting
email_reminders <- final_notif_emails_gt %>% gt(rowname_col = "row_lab") %>%
  cols_label("All Reminders"= md(" "), n = md("**n**"), "%" = md("**%**")) %>% 
   tab_header(title = md("Table 2.7 Baseline Survey Email Reminders Evaluation, Marshfield Clinic")) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "All Reminders",
      rows = bold_rows
    )) %>% 
#   tab_spanner(
#     label = "Footnote 1",
#     locations = cells_footnote(groups = "footnote1"),
#     value = "aseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted.."
#   ) %>%
#   tab_spanner(
#     label = "Footnote 2",
#     locations = cells_footnote(groups = "footnote2"),
#     value = "** Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."
#   )
# 
# email_reminders


tab_footnote(
  footnote=("Baseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."),
  locations = cells_column_labels(columns = "All Reminders")
)%>% 
 tab_footnote(
  footnote=("
'Eligible for reminder' is calculated as those sent the previous reminder minus those who completed the survey after the previous reminder."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
'Sent reminder' does not take into account whether email was successfully delivered or opened. A small percentage of Connect emails are undeliverable and the percent opened is unknown."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
' Email reminder schedule: Contact 1 is sent on day of verification or next day if verified after 3pm eastern; Contact 2 on day 3 post verification; Contact 3 on day 6 post verification; Contact 4 on day 15 post verification; Contact 5 on day 24 post verification; and Contact 6 on day 39 post verification."),
  locations = cells_column_labels(columns = "All Reminders")
) 

email_reminders
  
```

\newpage

```{r Sanford Health, echo=FALSE, warning=FALSE, message=FALSE}

## Same thing but by site 

SF_reminders <- reminders %>% filter(d_827220437=="657167265")

#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.
### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 

## Easiest way to do this was to say use the date of verification if they were verified before 3pm, use the day before if they were verified after 3pm, that way we don't need to add 1 to each case.
# Essentially we're ading a day to verification, so take that away and the post-verification dates should allign


comp_time <- SF_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- SF_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) >=19, as.numeric(str_sub(d_914594314,12,13)) >=20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")






reminders_ct <- SF_reminders %>% mutate(cnt_number=case_when(attempt=="1st contact" ~ "Sent reminder email Contact 1",
                                                          attempt=="2nd contact" ~ "Sent reminder email Contact 2",
                                                          attempt=="3rd contact" ~ "Sent reminder email Contact 3",
                                                          attempt=="4th contact" ~ "Sent reminder email Contact 4",
                                                          attempt=="5th contact" ~ "Sent reminder email Contact 5",
                                                          attempt=="6th contact" ~ "Sent reminder email Contact 6"))
 attempt_counts <- reminders_ct %>%
     group_by(Connect_ID, cnt_number) %>%
     slice_head() %>%  # Keep only the first row for each unique Connect_ID and contacts_number- that way the case_when doesn't eliminate participants with each case
     group_by(cnt_number) %>%
     summarise(Count = n_distinct(Connect_ID))

Sent_rows <- data.frame(Column1 = attempt_counts$cnt_number, Column2 = attempt_counts$Count)
colnames(Sent_rows) <- c("All Reminders", "n")



#Sent previous contact - people who finished
EligibleList <- c("Eligible for reminder email Contact 2","Eligible for reminder email Contact 3", "Eligible for reminder email Contact 4", "Eligible for reminder email Contact 5", "Eligible for reminder email Contact 6")
EligibleNumb <- c(length(unique(SF_reminders$Connect_ID))- (sum(comp_time_combined[1,2]) + sum(comp_time_combined[2,2])), #eligible2= all participants-those who completed before contact 2
                  Sent_rows[2,2] - sum(comp_time_combined[3,2]) , #eligible for 3= sent contact 2- completed before contact 3
                  Sent_rows[3,2] - sum(comp_time_combined[4,2]), #eligible for 4= sent contact3-completed before contact 4
                  Sent_rows[4,2] - sum(comp_time_combined[5,2]), #eligible for 5= sent contact4- completed before contact 5
                  Sent_rows[5,2] - sum(comp_time_combined[6,2])) #eligible for 6 =sent contact5-completed before contact 6


Eligible_rows <- data.frame(Column1 = EligibleList, Column2 = EligibleNumb)
colnames(Eligible_rows) <- c("All Reminders", "n")




final_notif_emails <- bind_rows(comp_time_combined, Sent_rows, Eligible_rows)
final_notif_emails <- final_notif_emails[c(8,1,2,14,9,3,15,10,4,16,11,5,17,12,6,18,13,7), ]



final_notif_emails$'%' <- c(paste(100*round(final_notif_emails[1,2]/length(unique(SF_reminders$Connect_ID)), digits=4), "%"),
                            paste(100*round(final_notif_emails[2,2]/length(unique(SF_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[3,2]/length(unique(SF_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[4,2]/length(unique(SF_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[5,2]/final_notif_emails[4,2], digits=3), "%"), 
                            paste(100*round(final_notif_emails[6,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[7,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[8,2]/final_notif_emails[7,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[9,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[10,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[11,2]/final_notif_emails[10,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[12,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[13,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[14,2]/final_notif_emails[13,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[15,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[16,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[17,2]/final_notif_emails[16,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[18,2]/final_notif_emails[17,2], digits=3), "%")) #b12




# Specify the rows to be bolded
bold_rows <- c(1,4,5,7,8,10,11,13,14,16,17)

final_notif_emails_gt <- as_tibble(final_notif_emails)

# Create a gt table and use text_transform to apply formatting
email_reminders <- final_notif_emails_gt %>% gt(rowname_col = "row_lab") %>%
  cols_label("All Reminders"= md(" "), n = md("**n**"), "%" = md("**%**")) %>% 
   tab_header(title = md("Table 2.8 Baseline Survey Email Reminders Evaluation, Sanford Health")) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "All Reminders",
      rows = bold_rows
    )) %>% 
#   tab_spanner(
#     label = "Footnote 1",
#     locations = cells_footnote(groups = "footnote1"),
#     value = "aseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted.."
#   ) %>%
#   tab_spanner(
#     label = "Footnote 2",
#     locations = cells_footnote(groups = "footnote2"),
#     value = "** Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."
#   )
# 
# email_reminders


tab_footnote(
  footnote=("Baseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."),
  locations = cells_column_labels(columns = "All Reminders")
)%>% 
 tab_footnote(
  footnote=("
'Eligible for reminder' is calculated as those sent the previous reminder minus those who completed the survey after the previous reminder."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
'Sent reminder' does not take into account whether email was successfully delivered or opened. A small percentage of Connect emails are undeliverable and the percent opened is unknown."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
' Email reminder schedule: Contact 1 is sent on day of verification or next day if verified after 3pm eastern; Contact 2 on day 3 post verification; Contact 3 on day 6 post verification; Contact 4 on day 15 post verification; Contact 5 on day 24 post verification; and Contact 6 on day 39 post verification."),
  locations = cells_column_labels(columns = "All Reminders")
) 

email_reminders
  
```

\newpage

```{r UChicago, echo=FALSE, warning=FALSE, message=FALSE}

## Same thing but by site 

UC_reminders <- reminders %>% filter(d_827220437=="809703864")

#From Deanna: To confirm the cadence in prod for the first 6 contacts of the post-verification emails, it is as follows: 0, 3, 6, 15, 24, 39 days post-verification.
### DATA PATTERN FOUND!! IF THEY'RE VERIFIED BEFORE 3 PM USE  0, 3, 6, 15, 24, 39 days post-verification, 
### IF THEY'RE VERIFIED AFTER 3PM THEY GET THE NOTIFICATION EMAIL THE NEXT DAY SO ESSENTIALLY 1th, 4th, 7th, 16th, 25th, 40th days post-verification 

## Easiest way to do this was to say use the date of verification if they were verified before 3pm, use the day before if they were verified after 3pm, that way we don't need to add 1 to each case.
# Essentially we're ading a day to verification, so take that away and the post-verification dates should allign


comp_time <- UC_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) <19, as.numeric(str_sub(d_914594314,12,13)) <20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 0 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 1, 2) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 3, 5) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 6, 14) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 15, 23) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 24, 38) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 39 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))


comp_time1 <- UC_reminders %>%
  filter(d_100767870 == '353358909' & !is.na(d_914594314) & !is.na(latest_module_date) & 
           ifelse((as.Date(d_914594314) > "2023-03-11" & as.Date(d_914594314) < "2023-11-05"), as.numeric(str_sub(d_914594314,12,13)) >=19, as.numeric(str_sub(d_914594314,12,13)) >=20)) %>%
  mutate(verification_date = as.POSIXct(d_914594314),
         module_completion_date = as.POSIXct(latest_module_date), #, origin = "1970-01-01"
         days_difference = round(as.numeric(difftime(module_completion_date, verification_date, units = "days")))) %>%
  mutate(time_frame = case_when(
    days_difference <= 1 ~ "Survey Completed On or Before Date of Contact 1",
    between(days_difference, 2, 3) ~ "Survey Completed after Contact 1, before Contact 2",
    between(days_difference, 4, 6) ~ "Survey Completed after Contact 2, before Contact 3",
    between(days_difference, 7, 15) ~ "Survey Completed after Contact 3, before Contact 4",
    between(days_difference, 16, 24) ~ "Survey Completed after Contact 4, before Contact 5",
    between(days_difference, 25, 39) ~ "Survey Completed after Contact 5, before Contact 6",
    days_difference >= 40 ~ "Survey Completed after Contact 6"
  )) %>% 
  group_by(time_frame) %>%
  summarise(n = n_distinct(Connect_ID))

comp_time[,3] <- comp_time1[,2]

comp_time[,4] <- comp_time[,2] + comp_time[,3]

comp_time_combined <- comp_time[,c(1,4)]

comp_time_combined$time_frame <- factor(comp_time_combined$time_frame, levels=c("Survey Completed On or Before Date of Contact 1","Survey Completed after Contact 1, before Contact 2","Survey Completed after Contact 2, before Contact 3",
                                                                      "Survey Completed after Contact 3, before Contact 4","Survey Completed after Contact 4, before Contact 5",
                                                                      "Survey Completed after Contact 5, before Contact 6","Survey Completed after Contact 6"))
#comp_time_combined <- comp_time_combined[c(7,1:6), ]
colnames(comp_time_combined) <- c("All Reminders", "n")






reminders_ct <- UC_reminders %>% mutate(cnt_number=case_when(attempt=="1st contact" ~ "Sent reminder email Contact 1",
                                                          attempt=="2nd contact" ~ "Sent reminder email Contact 2",
                                                          attempt=="3rd contact" ~ "Sent reminder email Contact 3",
                                                          attempt=="4th contact" ~ "Sent reminder email Contact 4",
                                                          attempt=="5th contact" ~ "Sent reminder email Contact 5",
                                                          attempt=="6th contact" ~ "Sent reminder email Contact 6"))
 attempt_counts <- reminders_ct %>%
     group_by(Connect_ID, cnt_number) %>%
     slice_head() %>%  # Keep only the first row for each unique Connect_ID and contacts_number- that way the case_when doesn't eliminate participants with each case
     group_by(cnt_number) %>%
     summarise(Count = n_distinct(Connect_ID))

Sent_rows <- data.frame(Column1 = attempt_counts$cnt_number, Column2 = attempt_counts$Count)
colnames(Sent_rows) <- c("All Reminders", "n")



#Sent previous contact - people who finished
EligibleList <- c("Eligible for reminder email Contact 2","Eligible for reminder email Contact 3", "Eligible for reminder email Contact 4", "Eligible for reminder email Contact 5", "Eligible for reminder email Contact 6")
EligibleNumb <- c(length(unique(UC_reminders$Connect_ID))- (sum(comp_time_combined[1,2]) + sum(comp_time_combined[2,2])), #eligible2= all participants-those who completed before contact 2
                  Sent_rows[2,2] - sum(comp_time_combined[3,2]) , #eligible for 3= sent contact 2- completed before contact 3
                  Sent_rows[3,2] - sum(comp_time_combined[4,2]), #eligible for 4= sent contact3-completed before contact 4
                  Sent_rows[4,2] - sum(comp_time_combined[5,2]), #eligible for 5= sent contact4- completed before contact 5
                  Sent_rows[5,2] - sum(comp_time_combined[6,2])) #eligible for 6 =sent contact5-completed before contact 6


Eligible_rows <- data.frame(Column1 = EligibleList, Column2 = EligibleNumb)
colnames(Eligible_rows) <- c("All Reminders", "n")




final_notif_emails <- bind_rows(comp_time_combined, Sent_rows, Eligible_rows)
final_notif_emails <- final_notif_emails[c(8,1,2,14,9,3,15,10,4,16,11,5,17,12,6,18,13,7), ]



final_notif_emails$'%' <- c(paste(100*round(final_notif_emails[1,2]/length(unique(UC_reminders$Connect_ID)), digits=4), "%"),
                            paste(100*round(final_notif_emails[2,2]/length(unique(UC_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[3,2]/length(unique(UC_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[4,2]/length(unique(UC_reminders$Connect_ID)), digits=3), "%"), 
                            paste(100*round(final_notif_emails[5,2]/final_notif_emails[4,2], digits=3), "%"), 
                            paste(100*round(final_notif_emails[6,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[7,2]/final_notif_emails[5,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[8,2]/final_notif_emails[7,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[9,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[10,2]/final_notif_emails[8,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[11,2]/final_notif_emails[10,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[12,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[13,2]/final_notif_emails[11,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[14,2]/final_notif_emails[13,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[15,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[16,2]/final_notif_emails[14,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[17,2]/final_notif_emails[16,2], digits=3), "%"),
                            paste(100*round(final_notif_emails[18,2]/final_notif_emails[17,2], digits=3), "%")) #b12




# Specify the rows to be bolded
bold_rows <- c(1,4,5,7,8,10,11,13,14,16,17)

final_notif_emails_gt <- as_tibble(final_notif_emails)

# Create a gt table and use text_transform to apply formatting
email_reminders <- final_notif_emails_gt %>% gt(rowname_col = "row_lab") %>%
  cols_label("All Reminders"= md(" "), n = md("**n**"), "%" = md("**%**")) %>% 
   tab_header(title = md("Table 2.9 Baseline Survey Email Reminders Evaluation, \n University of Chicago Medicine")) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = "All Reminders",
      rows = bold_rows
    )) %>% 
#   tab_spanner(
#     label = "Footnote 1",
#     locations = cells_footnote(groups = "footnote1"),
#     value = "aseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted.."
#   ) %>%
#   tab_spanner(
#     label = "Footnote 2",
#     locations = cells_footnote(groups = "footnote2"),
#     value = "** Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."
#   )
# 
# email_reminders


tab_footnote(
  footnote=("Baseline survey completed means submitted Modules 1-4. Counts as 'completed' on the date the last of the four modules was submitted."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("Reminders are not sent to participants who refuse baseline survey, refuse all future activities, withdraw, are deceased or request suspended contact. This may account for small discrepancies between the number eligible for a reminder and the number sent."),
  locations = cells_column_labels(columns = "All Reminders")
)%>% 
 tab_footnote(
  footnote=("
'Eligible for reminder' is calculated as those sent the previous reminder minus those who completed the survey after the previous reminder."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
'Sent reminder' does not take into account whether email was successfully delivered or opened. A small percentage of Connect emails are undeliverable and the percent opened is unknown."),
  locations = cells_column_labels(columns = "All Reminders")
) %>% 
 tab_footnote(
  footnote=("
' Email reminder schedule: Contact 1 is sent on day of verification or next day if verified after 3pm eastern; Contact 2 on day 3 post verification; Contact 3 on day 6 post verification; Contact 4 on day 15 post verification; Contact 5 on day 24 post verification; and Contact 6 on day 39 post verification."),
  locations = cells_column_labels(columns = "All Reminders")
) 

email_reminders
  
```





```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
## Possible errors
## Need to find the people that did not receive a first contact 
# Create a data frame with all Connect_IDs
all_participants <- data.frame(Connect_ID = unique(reminders$Connect_ID))

# Create a data frame with Connect_IDs that received a "1st contact" attempt
received_1st_contact <- reminders %>%
  filter(attempt == "1st contact") %>%
  select(Connect_ID)

# Identify Connect_IDs that did not receive a "1st contact" attempt
not_received_1st_contact <- anti_join(all_participants, received_1st_contact, by = "Connect_ID")

# Print or use not_received_1st_contact as needed
not_received_1st_contact
```















































```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}





## Code I was playing around with and code for the last year's preliminary version of this report:







#####Scenarios of finishing the modules before being verified, aka completed_before=="Completed Before Contact 1"
#if all four modules are completed, and all completed before verified
#if two modules are completed then mod1 and one other completed before verified- any of three combos
#if three modules are completed then mod1 and two other completed before verified
#if only one module is completed and is completed before verified
# 
# non_repeating_rows <- !duplicated(reminders)
# reminders2 <- reminders[non_repeating_rows, ]
# 
# reminders2 <- reminders %>%
#   mutate(completed_before=
#       case_when((d_517311251 < d_914594314) & (d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (d_264644252 < d_914594314) & 
#                   All_Completed_Status=="All Surveys Completed" ~ "Completed Before Contact 1",(d_517311251 < d_914594314) & (Number_Completed=="Three") &
#                   (((d_832139544 < d_914594314) & (d_770257102 < d_914594314) ) |((d_832139544 < d_914594314) &  (d_264644252 < d_914594314)) |
#                      ((d_770257102 < d_914594314) & (d_264644252 < d_914594314))) ~ "Completed Before Contact 1",
#                 (d_517311251 < d_914594314) & (Number_Completed=="Two") &
#                   ((d_832139544 < d_914594314) | (d_770257102 < d_914594314) | (d_264644252 < d_914594314)) ~ "Completed Before Contact 1",
#                 (d_517311251 < d_914594314) & Number_Completed=="One" ~ "Completed Before Contact 1",
#                 TRUE ~ completed_before))
# 
# 
# reminders2 <- reminders2 %>%
#   mutate(completed_before2=
#       case_when((d_517311251 < d_914594314) & (d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (d_264644252 < d_914594314) & 
#                   All_Completed_Status=="All Surveys Completed" ~ "All before verified",
#                 (d_517311251 < d_914594314) & (Number_Completed=="Three") &
#                   (((d_832139544 < d_914594314) & (d_770257102 < d_914594314) ) |((d_832139544 < d_914594314) &  (d_264644252 < d_914594314)) |
#                      ((d_770257102 < d_914594314) & (d_264644252 < d_914594314))) ~ "three before verified",
#                 (d_517311251 < d_914594314) & (Number_Completed=="Two") &
#                   ((d_832139544 < d_914594314) | (d_770257102 < d_914594314) | (d_264644252 < d_914594314)) ~ "Two before verified",
#                 (d_517311251 < d_914594314) & Number_Completed=="One" ~ "One before verified",
#                 TRUE ~ "Don't count"))
# 
# reminders <- reminders %>%   
#   mutate(completed_before=
#       ifelse(((d_517311251 < d_914594314) & (d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (d_264644252 < d_914594314) & All_Completed_Status=="All Surveys Completed") | 
#        # ifelse((d_517311251 < d_914594314) & (d_832139544 < d_914594314) & 
#        #   (d_770257102 < d_914594314) & (d_264644252 < d_914594314) & All_Completed_Status=="Some Surveys Completed", 
#        #   (completed_before=="Completed Before Contact 1" & All_Completed_Status=="Some Surveys Completed"),
#          ((d_517311251 < d_914594314) & (Number_Completed=="Two") & 
#                   ((d_832139544 < d_914594314) | (d_770257102 < d_914594314) | (d_264644252 < d_914594314))) |
#                 ((d_517311251 < d_914594314) & (Number_Completed=="Three") & 
#                   (((d_832139544 < d_914594314) & (d_770257102 < d_914594314) ) |((d_832139544 < d_914594314) &  (d_264644252 < d_914594314)) |
#                      ((d_770257102 < d_914594314) & (d_264644252 < d_914594314))) & All_Completed_Status=="Some Surveys Completed") |
#                   ((d_517311251 < d_914594314) & Number_Completed=="One"), completed_before=="Completed Before Contact 1", completed_before))
# 
# #table(reminders$completed_before)

bw_contact_0 <- CID_reminders %>% 
  mutate(between = case_when((d_517311251 < d_914594314) | (d_832139544 < d_914594314) | (d_770257102 < d_914594314) | 
                               (d_264644252 < d_914594314) ~ "Completed Before Verification",
                             TRUE ~ "Exclude"),
         Number_row = case_when(between=="Exclude" ~ "Zero", 
                                (d_517311251 < d_914594314) & (d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (d_264644252 < d_914594314) ~ "Four",
                                 (d_517311251 < d_914594314) & (is.na(d_832139544) | (d_832139544 > d_914594314)) & 
                                   (is.na(d_770257102) | (d_770257102 > d_914594314)) & (is.na(d_264644252) | (d_264644252 > d_914594314)) ~ "One",
                                 (d_517311251 < d_914594314) & 
                                   (((d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (is.na(d_264644252) | (d_264644252 > d_914594314))) |
                                      ((d_832139544 < d_914594314) &  (d_264644252 < d_914594314) & (is.na(d_770257102) | (d_770257102 > d_914594314))) |
                                      ((d_770257102 < d_914594314) & (d_264644252 < d_914594314) & (is.na(d_832139544) | (d_832139544 > d_914594314)))) ~ "Three",
                                (d_517311251 < d_914594314) & 
                                  (((d_832139544 < d_914594314) & (is.na(d_770257102) | (d_770257102 > d_914594314)) & 
                                    (is.na(d_264644252) | (d_264644252 > d_914594314))) |
                                   ((d_770257102 < d_914594314) & (is.na(d_832139544) | (d_832139544 > d_914594314)) & 
                                      (is.na(d_264644252) | (d_264644252 > d_914594314))) |
                                 ((d_264644252 < d_914594314) & (is.na(d_770257102) | (d_770257102 > d_914594314)) & 
                                     (is.na(d_832139544) | (d_832139544 > d_914594314)))) ~ "Two",
                                TRUE ~ "Missing Something")) %>% 
  mutate(Number_row = factor(Number_row, levels=c("Four", "Three", "Two", "One", "Zero")))

#Before Verification
bw_contact0 <- bw_contact_0 %>%   tbl_cross(
    row = Number_row,
    col = All_Completed_Status,
    digits=c(0,1),
    percent = "row",
    label=list(Number_row="Modules",
                All_Completed_Status = "Baseline Completion Status"),
    missing="ifany",
    margin_text="Total") 
 
 
 
bw_contact0 %>%
  #bold_labels() %>%
  #italicize_levels() %>% 
  modify_header(stat_0 = "Total") %>%
  modify_caption("Table 2. Number of Modules Completed Before Verification by Baseline Completion Status") %>%
  as_kable_extra(escape = FALSE, addtl_fmt = TRUE)


####After Verification
# 
# bw_contact_0 <- bw_contact_0 %>% mutate(contacts= case_when(last_attempt_max==0 ~ "Completion After Verification, Before 1st Reminder",
#                                                             last_attempt_max==1 ~ "Completed Between Reminders"))
# after_contact0 <- bw_contact_0 %>%  filter(Number_row=="Zero") %>%  tbl_cross(
#     row = last_attempt_max,
#     col = All_Completed_Status,
#     digits=c(0,1),
#     percent = "row",
#     label=list(last_attempt_max="Contacts",
#                 All_Completed_Status = "Baseline Completion Status"),
#     missing="ifany",
#     margin_text="Total") 
# 
# after_contact0 %>%
#   #bold_labels() %>%
#   #italicize_levels() %>% 
#   modify_header(stat_0 = "Total") %>%
#   modify_caption("Table 3. Module Survey Completion Reminders by Baseline Completion Status for Participants Completing All Modules after Verification") %>%
#   as_kable_extra(escape = FALSE, addtl_fmt = TRUE)



```


\FloatBarrier
```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}

#row 1- before verified



before_ver_all <- sum(bw_contact_0$Number_row!="Zero" & bw_contact_0$All_Completed_Status=="All Surveys Completed")
before_ver_some <- sum(bw_contact_0$Number_row!="Zero" & bw_contact_0$All_Completed_Status=="Some Surveys Completed")
before_ver_none <- sum(bw_contact_0$Number_row!="Zero" & bw_contact_0$All_Completed_Status=="None Surveys Completed")

# row1 <- list(before_ver_all, before_ver_some, before_ver_none)
# 
# #row 2- between 1st and 2nd contact
# #bw_contact_0 %>% filter(attempt_number>0) %>% mutate(completion= ifelse())
# 
# 
# overall_by_email <- CID_reminders %>%  tbl_cross( 
#     row = completed_before,
#     col = All_Completed_Status,
#     digits=c(0,1),
#     percent = "row",
#     label=list(completed_before="Contact",
#                 All_Completed_Status = "Basleine Completion Status"),
#     missing="ifany",
#     margin_text="Total") 
# 
# overall_by_email%>%
#   #bold_labels() %>%
#   #italicize_levels() %>% 
#   modify_header(stat_0 = "Total") %>%
#   modify_caption("Table 2. Survey Modules Completion Time Frame by Baseline Completion Status") %>%
#   as_kable_extra(escape = FALSE, addtl_fmt = TRUE) %>% kable_styling(latex_options = "scale_down")
 


```

\FloatBarrier
```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
# surveys_completed <- as.data.frame(table(CID_reminders$Number_Completed))
# 
# # Add a summary row
# total_row_srvy <- data.frame(Var1 = "Total", Freq = sum(surveys_completed$Freq))
# 
# # Bind the summary row to the original data
# surveys_completed <- rbind(surveys_completed, total_row_srvy)
# 
# surveys_completed[1,2] <- paste(surveys_completed[1,2], " (", round(100*as.numeric(surveys_completed[1,2])/as.numeric(surveys_completed[6,2]), digits=1), "%)")
# surveys_completed[2,2] <- paste(surveys_completed[2,2], " (", round(100*as.numeric(surveys_completed[2,2])/as.numeric(surveys_completed[6,2]), digits=1), "%)")
# surveys_completed[3,2] <- paste(surveys_completed[3,2], " (", round(100*as.numeric(surveys_completed[3,2])/as.numeric(surveys_completed[6,2]), digits=1), "%)")
# surveys_completed[4,2] <- paste(surveys_completed[4,2], " (", round(100*as.numeric(surveys_completed[4,2])/as.numeric(surveys_completed[6,2]), digits=1), "%)")
# surveys_completed[5,2] <- paste(surveys_completed[5,2], " (", round(100*as.numeric(surveys_completed[5,2])/as.numeric(surveys_completed[6,2]), digits=1), "%)")
# surveys_completed[6,2] <- paste(surveys_completed[6,2], " (100%)")
# 
# #surveys_completed <- surveys_completed[c(5,2,4,3,1,6), ]
# 
# surveys_completed %>%  gt(rowname_col = "row_lab")  %>%  
#   #fmt_number(columns = "Var1", decimals = 1) %>% 
#   tab_header(title = md("Table 3. The Number of Survey Modules Completed")) %>% 
#   cols_label(Var1= md("Completed Modules"), Freq = md("**Number of Participants**")) %>% 
#     #grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T))|>
#   tab_options(
#       stub.font.weight = "bold"
#     ) %>%
#   tab_style(
#     style = list(
#       cell_text(weight = "bold")
#     ),
#     locations = cells_body(
#       columns = Var1,
#     ))


surveys_completed_Site <- CID_reminders %>%   tbl_cross(
    row = Site,
    col = Number_Completed,
    digits=c(0,1),
    percent = "row",
    label=list(Number_row="Site",
                Number_Completed = "Completed Modules"),
    missing="ifany",
    margin_text="Total") 

surveys_completed_Site %>%
  #bold_labels() %>%
  #italicize_levels() %>% 
  modify_header(stat_0 = "Total") %>%
  modify_caption("Table 3. The Number of Survey Modules Completed, by Site") %>%
  as_kable_extra(escape = FALSE, addtl_fmt = TRUE)  %>% kable_styling(latex_options = "scale_down")

  
```

\FloatBarrier

```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}


surverys_overall <- CID_reminders %>%  tbl_cross(
    row = Number_Completed,
    col = All_Completed_Status,
    digits=c(0,1),
    percent = "row",
    label=list(Number_Completed="Completed Modules",
                All_Completed_Status = "Basleine Completion Status"),
    missing="ifany",
    margin_text="Total") 

surverys_overall4 <- surverys_overall%>%
  #bold_labels() %>%
  #italicize_levels() %>% 
  modify_header(stat_0 = "Total") %>%
  modify_caption("Table 4. The Number of Survey Modules Completed by \n the Baseline Completion Status") %>%
  as_kable_extra(escape = FALSE, addtl_fmt = TRUE)  %>% kable_styling(latex_options = "scale_down")

add_footnote(surverys_overall4, "Note: These percentages are by row.", notation = "none")
 
```











```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}

# TESTING



# reminders2 <- reminders %>%
#   mutate(completed_before=
#       case_when((d_517311251 < d_914594314) & (d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (d_264644252 < d_914594314) & 
#                   All_Completed_Status=="All Surveys Completed" ~ "Completed Before Contact 1",(d_517311251 < d_914594314) & (Number_Completed=="Three") &
#                   (((d_832139544 < d_914594314) & (d_770257102 < d_914594314) ) |((d_832139544 < d_914594314) &  (d_264644252 < d_914594314)) |
#                      ((d_770257102 < d_914594314) & (d_264644252 < d_914594314))) ~ "Completed Before Contact 1",
#                 (d_517311251 < d_914594314) & (Number_Completed=="Two") &
#                   ((d_832139544 < d_914594314) | (d_770257102 < d_914594314) | (d_264644252 < d_914594314)) ~ "Completed Before Contact 1",
#                 (d_517311251 < d_914594314) & Number_Completed=="One" ~ "Completed Before Contact 1",
#                 TRUE ~ completed_before))
# 
# 
# reminders2 <- reminders2 %>%
#   mutate(completed_before2=
#       case_when((d_517311251 < d_914594314) & (d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (d_264644252 < d_914594314) & 
#                   All_Completed_Status=="All Surveys Completed" ~ "All before verified",
#                 (d_517311251 < d_914594314) & (Number_Completed=="Three") &
#                   (((d_832139544 < d_914594314) & (d_770257102 < d_914594314) ) |((d_832139544 < d_914594314) &  (d_264644252 < d_914594314)) |
#                      ((d_770257102 < d_914594314) & (d_264644252 < d_914594314))) ~ "three before verified",
#                 (d_517311251 < d_914594314) & (Number_Completed=="Two") &
#                   ((d_832139544 < d_914594314) | (d_770257102 < d_914594314) | (d_264644252 < d_914594314)) ~ "Two before verified",
#                 (d_517311251 < d_914594314) & Number_Completed=="One" ~ "One before verified",
#                 TRUE ~ "Don't count"))
# 
# reminders <- reminders %>%   
#   mutate(completed_before=
#       ifelse(((d_517311251 < d_914594314) & (d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (d_264644252 < d_914594314) & All_Completed_Status=="All Surveys Completed") | 
#        # ifelse((d_517311251 < d_914594314) & (d_832139544 < d_914594314) & 
#        #   (d_770257102 < d_914594314) & (d_264644252 < d_914594314) & All_Completed_Status=="Some Surveys Completed", 
#        #   (completed_before=="Completed Before Contact 1" & All_Completed_Status=="Some Surveys Completed"),
#          ((d_517311251 < d_914594314) & (Number_Completed=="Two") & 
#                   ((d_832139544 < d_914594314) | (d_770257102 < d_914594314) | (d_264644252 < d_914594314))) |
#                 ((d_517311251 < d_914594314) & (Number_Completed=="Three") & 
#                   (((d_832139544 < d_914594314) & (d_770257102 < d_914594314) ) |((d_832139544 < d_914594314) &  (d_264644252 < d_914594314)) |
#                      ((d_770257102 < d_914594314) & (d_264644252 < d_914594314))) & All_Completed_Status=="Some Surveys Completed") |
#                   ((d_517311251 < d_914594314) & Number_Completed=="One"), completed_before=="Completed Before Contact 1", completed_before))
# 
# #table(reminders$completed_before)
# after_emails <- CID_reminders %>% #filter(d_100767870=='353358909') %>% 
#   mutate(emails = case_when((d_517311251 < d_914594314) & (d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (d_264644252 < d_914594314) ~"Completed All Modules Before Verification",
#                             Number_Completed=="Three" & (d_517311251 < d_914594314) & (((d_832139544 < d_914594314) & (d_770257102 < d_914594314) ) |((d_832139544 < d_914594314) &  (d_264644252 < d_914594314)) |
#                                                                                          ((d_770257102 < d_914594314) & (d_264644252 < d_914594314))) ~"Completed Three Modules Before Verification",
#                             Number_Completed=="Two" & (d_517311251 < d_914594314) & ((d_832139544 < d_914594314) | (d_770257102 < d_914594314) | (d_264644252 < d_914594314)) ~"Completed Two Modules Before Verification",
#                             Number_Completed=="One" & (d_517311251 < d_914594314) ~"Completed One Modules Before Verification",
#                                                             TRUE ~"Completed No Modules Before Verification")) %>% 
#   mutate(emails = factor(emails, levels=c("Completed All Modules Before Verification", "Completed Three Modules Before Verification", "Completed Two Modules Before Verification", "Completed One Modules Before Verification", "Completed No Modules Before Verification"))) %>% select(emails, Number_Completed) %>% 
#   tbl_cross(
#     row = emails,
#     col = Number_Completed,
#     digits=c(0,1),
#     percent = "row",
#     label=list(emails=" ",
#                 Number_Completed = "Total Modules Completed"),
#     missing="ifany",
#     margin_text="Total") 


after_emails <- CID_reminders %>% filter(d_100767870=='353358909') %>% 
  mutate(emails = case_when((d_517311251 < d_914594314) & (d_832139544 < d_914594314) & (d_770257102 < d_914594314) & (d_264644252 < d_914594314) ~"Completed All Modules Before Verification",
                            (d_517311251 < d_914594314) & (((d_832139544 < d_914594314) & (d_770257102 < d_914594314) ) |((d_832139544 < d_914594314) &  (d_264644252 < d_914594314)) |
                                                                                         ((d_770257102 < d_914594314) & (d_264644252 < d_914594314))) ~"Completed Three Modules Before Verification",
                            (d_517311251 < d_914594314) & ((d_832139544 < d_914594314) | (d_770257102 < d_914594314) | (d_264644252 < d_914594314)) ~"Completed Two Modules Before Verification",
                            (d_517311251 < d_914594314) ~"Completed One Modules Before Verification",
                                                            TRUE ~"Completed No Modules Before Verification")) %>% 
  mutate(emails = factor(emails, levels=c("Completed All Modules Before Verification", "Completed Three Modules Before Verification", "Completed Two Modules Before Verification", "Completed One Modules Before Verification", "Completed No Modules Before Verification"))) %>% select(emails, Number_Completed) %>% 
  tbl_cross(
    row = emails,
    col = Number_Completed,
    digits=c(0,1),
    percent = "row",
    label=list(emails=" ",
                Number_Completed = "Total Modules Completed"),
    missing="ifany",
    margin_text="Total") 
 
 
 
after_emails %>%
  #bold_labels() %>%
  #italicize_levels() %>% 
  modify_header(stat_0 = "Total") %>%
  modify_caption("Table 7. Number of Modules Completed Before Verification by Total Number of Modules Completed") %>%
  as_kable_extra(escape = FALSE, addtl_fmt = TRUE)



```

\FloatBarrier

```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}

# #checking denominator
# email_buckets <- CID_reminders %>%  tbl_cross(
#     row = completed_before,
#     col = buckets,
#     digits=c(0,1),
#     percent = "row",
#     label=list(completed_before="Contacts",
#                 buckets = "Buckets"),
#     missing="ifany",
#     margin_text="Total") 
# 
# email_buckets%>%
#   #bold_labels() %>%
#   #italicize_levels() %>% 
#   modify_header(stat_0 = "Total") %>%
#   modify_caption("Table 8. The Distribution of Email Reminders Sent to All Participants in Four Buckets: \n All BL Modules, Some BL Modules, One Module, or No Modules") %>%
#   as_kable_extra(escape = FALSE, addtl_fmt = TRUE) %>% kable_styling(latex_options = "scale_down")



email_buckets <- CID_reminders %>%  tbl_cross(
    col = Number_Completed,
    row = buckets,
    digits=c(0,1),
    percent = "row",
    label=list(Number_Completed="Completed Modules",
                buckets = "Completion Buckets"),
    missing="ifany",
    margin_text="Total") 

email_buckets <- email_buckets %>%
  #bold_labels() %>%
  #italicize_levels() %>% 
  modify_header(stat_0 = "Total") %>%
  modify_caption("Table 7. The Distribution of Email Reminders Sent to All Participants in Four Buckets: \n All BL Modules, Some BL Modules, One Module, or No Modules") %>%
  as_kable_extra(escape = FALSE, addtl_fmt = TRUE)  %>% kable_styling(latex_options = "scale_down")

add_footnote(email_buckets, "Note: Those who complete all baseline modules before verification or have not been in the cohort long enough will have received no reminders, or 0 contacts. These percentages are by row.", notation = "none")

```



\FloatBarrier

```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}

#how many modules done after each reminder

CID_reminders$last_attempt_max <- as.numeric(CID_reminders$last_attempt_max)

dist <- CID_reminders  %>% group_by(buckets) %>%
  dplyr::summarize(#'Incentives Issued'=n(),
                   Min = min(last_attempt_max, na.rm = T),
                   Q1 = quantile(last_attempt_max, 0.25, na.rm = T),
                   Median = median(last_attempt_max, na.rm = T),
                   Mean = mean(last_attempt_max, na.rm = T),
                   SD=sd(last_attempt_max, na.rm = T),
                   Q3 = quantile(last_attempt_max, 0.75, na.rm = T),
                   Perc.90 = quantile(last_attempt_max, 0.90, na.rm = T),
                   Perc.95 = quantile(last_attempt_max, 0.95, na.rm = T),                   
                   Max = max(last_attempt_max, na.rm = T))

colnames(dist) <- c("Buckets","Min","Q1","Median","Mean","SD","Q3","Perc.90","Perc.95","Max")

knitr::kable(dist, caption='Table 8. Distrubution of Email Reminders by Bucket',row.names=FALSE, align=c("l","c","c","c","c","c","c","c","c","c","c","c"),digits=1, booktabs = TRUE)%>% kable_styling(latex_options = "scale_down")


```



```{r, echo=FALSE, warning=FALSE, message=FALSE}

#how many modules done after each reminder

#for each attempt_number:
# notification_time(attempt1) > d_517311251 & d_517311251 < notification_time (attempt2)
#Number_Completed increase or stay the same 


```


```{r, echo=FALSE, warning=FALSE, message=FALSE}

#how effective were emails for those that had only 1 mod done, 2, ect. 




# ( mod1completiontime > attempt1 & ( mod2completiontime < attempt2 | mod3completiontime < attempt2 | mod4completiontime < attempt2 ) ~ At least 1 Module done after attempt 1)
 


```



```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}

# ## How many emails sent before completion
# 
# after_emails <- reminders %>% filter(!is.na(d_517311251) & !is.na(d_832139544) & !is.na(d_770257102) & !is.na(d_264644252))
# 
# 
# after_emails <- after_emails %>%  mutate(max_emails=as.numeric(str_sub(attempt,1)))
# 
# 
# #after_emails <- after_emails %>%  mutate(compl_date = pmax(d_517311251, d_832139544, d_770257102, d_264644252, na.rm=T))
# 
# 
# after_emails <- after_emails %>%  mutate(emails = case_when(#d_100767870=='353358909' & as.Date(compl_date)==as.Date(one_email) ~"Completion the Day of Verification", --- how to count this
#                                                             d_100767870=='353358909' & max_emails==1 ~"Completion after 1 email",
#                                                             d_100767870=='353358909' & max_emails==2 ~"Completion after 2 emails",
#                                                             d_100767870=='353358909' & max_emails==3 ~"Completion after 3 emails",
#                                                             d_100767870=='353358909' & max_emails==4 ~"Completion after 4 emails",
#                                                             d_100767870=='353358909' & max_emails==5  ~"Completion after 5 emails",
#                                                             d_100767870=='353358909' & max_emails==6 ~"Completion after 6 emails",
#                                                             TRUE ~"Completion after 6 emails"))
#                                                             #d_100767870=='353358909' & as.Date(compl_date)>as.Date(ten_emails) ~"Completion after 10 emails",
#                                                             #TRUE ~ "No Completion after 10 emails"))
# 
# after_emails$emails <- factor(after_emails$emails,levels=c("Completion after 1 email", "Completion after 2 emails", "Completion after 3 emails", "Completion after 4 emails", "Completion after 5 emails", "Completion after 6 emails"))
# 
# 
# 
# dt_after_emails <- after_emails %>%  group_by(emails)  %>% dplyr::summarize(n=n(), pct=100*n/nrow(.))  %>% dplyr::ungroup() %>%  dplyr::select(emails, n, pct) 
# 
# dt_after_emails %>%  gt(rowname_col = "row_lab") %>%  
#   fmt_number(columns = "pct", decimals = 2) %>% 
#   tab_header(title = md("Baseline Module Survey Completion Response Rate")) %>%  
#   cols_label(n= md("**Number of Participants**"), emails = md("Email Reminders Sent"), pct = md("Percent of Participants")) %>% 
#     # summary_rows(
#     #   groups=F,
#     # column = c(n,pct),
#     # fns= list(
#     #   Sum= ~sum(.)
#     # ), decimals=0) %>%
#   #grand_summary_rows(fns = ~sum(c(n, pct),na.rm = T)) %>%  
#       grand_summary_rows(columns=c(n, pct),fns = ~sum(.,na.rm = T))|>
#   tab_options(
#       stub.font.weight = "bold"
#     ) %>%
#   tab_style(
#     style = list(
#       cell_text(weight = "bold")
#     ),
#     locations = cells_body(
#       columns = emails,
#     )
#   ) %>%  
#   tab_footnote(paste0("This table counts the ", sum(ptps_c$d_100767870==353358909), " participants that have currently completed all Baseline Modules. It excludes the ", sum(ptps_c$d_100767870==104430631), " participants that have not."))
# 
# 
# 
# 
# 
# 
# ####### Overall 
# #table(reminders$d_747006172)
# 
# reminders <- reminders %>%  mutate(emails = case_when( (d_821247024==197316935 & d_906417725==104430631 & d_685002411_d_994064239==104430631 & d_747006172==104430631 & d_100767870==104430631 & difftime(currentDate, as.POSIXct(ymd_hms(verif)), units="days")> 336) ~ "10 email reminders",
#                                           (d_821247024==197316935 & d_906417725==104430631 & d_685002411_d_994064239==104430631 & d_747006172==104430631 & d_100767870==104430631 & difftime(currentDate, as.POSIXct(ymd_hms(verif)), units="days")> 126)  ~ "9 email reminders",
#                                           (d_821247024==197316935 & d_906417725==104430631 & d_685002411_d_994064239==104430631 & d_747006172==104430631 & d_100767870==104430631 & difftime(currentDate, as.POSIXct(ymd_hms(reminders$verif)), units="days")> 103 )~ "8 email reminders",
#                                           (d_821247024==197316935 & d_906417725==104430631 & d_685002411_d_994064239==104430631 & d_747006172==104430631 & d_100767870==104430631 & difftime(currentDate, as.POSIXct(ymd_hms(reminders$verif)), units="days")> 86 ) ~ "7 email reminders",
#                                           (d_821247024==197316935 & d_906417725==104430631 & d_685002411_d_994064239==104430631 & d_747006172==104430631 & d_100767870==104430631 & difftime(currentDate, as.POSIXct(ymd_hms(reminders$verif)), units="days")> 39) ~ "6 email reminders",
#                                           (d_821247024==197316935 & d_906417725==104430631 & d_685002411_d_994064239==104430631 & d_747006172==104430631 & d_100767870==104430631 & difftime(currentDate, as.POSIXct(ymd_hms(reminders$verif)), units="days")> 24) ~ "5 email reminders",
#                                           (d_821247024==197316935 & d_906417725==104430631 & d_685002411_d_994064239==104430631 & d_747006172==104430631 &   d_100767870==104430631 & difftime(currentDate, as.POSIXct(ymd_hms(reminders$verif)), units="days")> 15 ) ~ "4 email reminders",
#                                           (d_821247024==197316935 & d_906417725==104430631 & d_685002411_d_994064239==104430631 & d_747006172==104430631 &   d_100767870==104430631 & difftime(currentDate, as.POSIXct(ymd_hms(reminders$verif)), units="days")> 6 ) ~ "3 email reminders",
#                                           (d_821247024==197316935 & d_906417725==104430631 & d_685002411_d_994064239==104430631 & d_747006172==104430631 & d_100767870==104430631 & difftime(currentDate, as.POSIXct(ymd_hms(reminders$verif)), units="days")>3) ~ "2 email reminders",
#                                           TRUE ~ "1 email reminder"))
# 
# #table(reminders$emails)
# reminders$emails <- factor(reminders$emails,levels=c("1 email reminder", "2 email reminders", "3 email reminders", "4 email reminders", "5 email reminders", "6 email reminders", "7 email reminders", "8 email reminders", "9 email reminders", "10 email reminders", "Doesn't Match Listed Requirements"))
# 
# #ccc4_b4_summary <- ccc4_b4 %>%  group_by(time_frame)  %>% arrange(time_frame) %>% summarize_at(c('freq', "percentage", 'freq.Active', "freq.Passive", "percentage.Active", "percentage.Passive"), sum, na.rm = TRUE)
# 
# dt_reminders <- reminders %>%  group_by(emails)  %>% dplyr::summarize(n=n(), pct=100*n/nrow(.))  %>% dplyr::ungroup() %>%  dplyr::select(emails, n, pct) 
# 
# dt_reminders %>%  gt(rowname_col = "row_lab") %>%  
#   fmt_number(columns = "pct", decimals = 2) %>% 
#   tab_header(title = md("Overall Across Participants that Haven't Completed Baseline Surveys")) %>%  
#   cols_label(n= md("**Number of Participants**"), emails = md("Email Reminders Sent"), pct = md("Percent of Participants")) %>% 
#     # summary_rows(
#     #   groups=F,
#     # column = c(n,pct),
#     # fns= list(
#     #   Sum= ~sum(.)
#     # ), decimals=0) %>%
#     grand_summary_rows(columns=c(n, pct),fns = ~sum(.,na.rm = T))|>
#   tab_options(
#       stub.font.weight = "bold"
#     ) %>%
#   tab_style(
#     style = list(
#       cell_text(weight = "bold")
#     ),
#     locations = cells_body(
#       columns = emails,
#     )
#   )
# 
# 
# 
# 
# 
# 
# 
# 
# ####### By Site
# 
# #dt_reminders <- reminders %>%  group_by(Site, emails)  %>% dplyr::summarize(n=n(), pct=100*n/nrow(.)) %>% dplyr::ungroup()  %>%  dplyr::select(Site, emails, n, pct)  #%>% dplyr::ungroup()
# 
# # dt_reminders <- reminders  %>% dplyr::summarize(n=n(), pct=100*n/nrow(.)) %>%  dplyr::select(Site, emails, n, pct) # %>% dplyr::ungroup()  %>%  dplyr::select(Site, emails, n, pct) %>%  group_by(Site, emails)
# # dt_reminders <- dt_reminders %>%  group_by(Site)  %>%  dplyr::select( emails, n, pct)
# 
# 
# dt_reminders <- reminders   %>%  dplyr::select(Site, emails) # %>% dplyr::ungroup()  %>%  dplyr::select(Site, emails, n, pct) %>%  group_by(Site, emails)
# dt_reminders <- dt_reminders %>%  group_by(Site, emails)  %>% dplyr::summarize(n=n(), pct=100*n/nrow(.)) %>%  dplyr::select( emails, n, pct)
# 
# dt_reminders %>%  gt(rowname_col = "row_lab") %>%  
#   fmt_number(columns = "pct", decimals = 2) %>% 
#   tab_header(title = md("Across Participants that Haven't Completed Baseline Surveys by Site")) %>%  
#   cols_label(n= md("**Number of Participants**"), emails = md("Email Reminders Sent"), pct = md("Percent of Participants")) %>% 
#     # summary_rows(
#     #   groups=F,
#     # column = c(n,pct),
#     # fns= list(
#     #   Sum= ~sum(.)
#     # ), decimals=0) %>%
#       grand_summary_rows(columns=c(n, pct),fns = ~sum(.,na.rm = T))|>
#   tab_options(
#       stub.font.weight = "bold"
#     ) %>%
#   tab_style(
#     style = list(
#       cell_text(weight = "bold")
#     ),
#     locations = cells_body(
#       columns = emails,
#     )
#   )
# 
# 
# 
# 
# #### Donated Any Biospecimen Training
# 
# #dt_reminders <- reminders %>%  group_by(Site, emails)  %>% dplyr::summarize(n=n(), pct=100*n/nrow(.)) %>% dplyr::ungroup()  %>%  dplyr::select(Site, emails, n, pct)  #%>% dplyr::ungroup()
# 
# anybio <- reminders %>%  filter(d_878865966 ==353358909 | d_684635302==353358909 | d_167958071==353358909)
# 
# dt_anybio <- anybio %>%  group_by(emails)  %>% dplyr::summarize(n=n(), pct=100*n/nrow(.))  %>% dplyr::ungroup() %>%  dplyr::select(emails, n, pct) 
# 
# dt_anybio %>%  gt(rowname_col = "row_lab") %>%  
#   fmt_number(columns = "pct", decimals = 2) %>% 
#   tab_header(title = md("Across Participants that Donated Baseline Biospecimen Samples but \n Haven't Completed Baseline Surveys")) %>%  
#   cols_label(n= md("**Number of Participants**"), emails = md("Email Reminders Sent"), pct = md("Percent of Participants")) %>% 
#     # summary_rows(
#     #   groups=F,
#     # column = c(n,pct),
#     # fns= list(
#     #   Sum= ~sum(.)
#     # ), decimals=0) %>%
#       grand_summary_rows(columns=c(n, pct),fns = ~sum(.,na.rm = T))|>
#   tab_options(
#       stub.font.weight = "bold"
#     ) %>%
#   tab_style(
#     style = list(
#       cell_text(weight = "bold")
#     ),
#     locations = cells_body(
#       columns = emails,
#     )
#   )
# 
# 
# 
# 
# 
# 
# 
# 
# ## How many emails sent before completion
# 
# after_emails <- ptps_c %>% filter(!is.na(d_517311251) & !is.na(d_832139544) & !is.na(d_770257102) & !is.na(d_264644252))
# 
# 
# after_emails <- after_emails %>%  mutate(one_email= as.Date(d_914594314) + 0,
#                                    two_emails= as.Date(d_914594314) + 4,
#                                    three_emails= as.Date(d_914594314) + 7,
#                                    four_emails= as.Date(d_914594314) + 16,
#                                    five_emails= as.Date(d_914594314) + 25,
#                                    six_emails= as.Date(d_914594314) + 40,
#                                    seven_emails= as.Date(d_914594314) + 87,
#                                    eight_emails= as.Date(d_914594314) + 104,
#                                    nine_emails= as.Date(d_914594314) + 127,
#                                    ten_emails= as.Date(d_914594314) + 337)
# 
# 
# 
# # after_emails <- ptps_c %>%  mutate(one_email= paste(str_sub(d_914594314,1,8), (as.numeric(str_sub(d_914594314,9,10)) + 0), str_sub(d_914594314,11,24)),
# #                                    two_emails= paste(str_sub(d_914594314,1,8), (as.numeric(str_sub(d_914594314,9,10)) + 4), str_sub(d_914594314,11,24)),
# #                                    three_emails= paste(str_sub(d_914594314,1,8), (as.numeric(str_sub(d_914594314,9,10)) + 7), str_sub(d_914594314,11,24)),
# #                                    four_emails= paste(str_sub(d_914594314,1,8), (as.numeric(str_sub(d_914594314,9,10)) + 16), str_sub(d_914594314,11,24)),
# #                                    five_emails= paste(str_sub(d_914594314,1,8), (as.numeric(str_sub(d_914594314,9,10)) + 25), str_sub(d_914594314,11,24)),
# #                                    six_emails= paste(str_sub(d_914594314,1,8), (as.numeric(str_sub(d_914594314,9,10)) + 40), str_sub(d_914594314,11,24)),
# #                                    seven_emails= paste(str_sub(d_914594314,1,8), (as.numeric(str_sub(d_914594314,9,10)) + 87), str_sub(d_914594314,11,24)),
# #                                    eight_emails= paste(str_sub(d_914594314,1,8), (as.numeric(str_sub(d_914594314,9,10)) + 104), str_sub(d_914594314,11,24)),
# #                                    nine_emails= paste(str_sub(d_914594314,1,8), (as.numeric(str_sub(d_914594314,9,10)) + 127), str_sub(d_914594314,11,24)),
# #                                    ten_emails= paste(str_sub(d_914594314,1,8), (as.numeric(str_sub(d_914594314,9,10)) + 337), str_sub(d_914594314,11,24)))
# 
# 
# after_emails <- after_emails %>%  mutate(compl_date = pmax(d_517311251, d_832139544, d_770257102, d_264644252, na.rm=T))
# 
# 
# after_emails <- after_emails %>%  mutate(emails = case_when(d_100767870=='353358909' & as.Date(compl_date)==as.Date(one_email) ~"Completion the Day of Verification",
#                                                             d_100767870=='353358909' & as.Date(two_emails)>as.Date(compl_date) & as.Date(compl_date)>as.Date(one_email) ~"Completion after 1 email",
#                                                             d_100767870=='353358909' & as.Date(three_emails)>as.Date(compl_date) & as.Date(compl_date)>as.Date(two_emails) ~"Completion after 2 emails",
#                                                             d_100767870=='353358909' & as.Date(four_emails)>as.Date(compl_date) & as.Date(compl_date)>as.Date(three_emails) ~"Completion after 3 emails",
#                                                             d_100767870=='353358909' & as.Date(five_emails)>as.Date(compl_date) & as.Date(compl_date)>as.Date(four_emails) ~"Completion after 4 emails",
#                                                             d_100767870=='353358909' & as.Date(six_emails)>as.Date(compl_date) & as.Date(compl_date)>as.Date(five_emails)  ~"Completion after 5 emails",
#                                                             d_100767870=='353358909' & as.Date(seven_emails)>as.Date(compl_date) & as.Date(compl_date)>as.Date(six_emails) ~"Completion after 6 emails",
#                                                             d_100767870=='353358909' & as.Date(eight_emails)>as.Date(compl_date) & as.Date(compl_date)>as.Date(seven_emails)  ~"Completion after 7 emails",
#                                                             d_100767870=='353358909' & as.Date(nine_emails)>as.Date(compl_date) & as.Date(compl_date)>as.Date(eight_emails) ~"Completion after 8 emails",
#                                                             d_100767870=='353358909' & as.Date(ten_emails)>as.Date(compl_date) & as.Date(compl_date)>as.Date(nine_emails) ~"Completion after 9 emails",
#                                                             TRUE ~"Completion after 10 emails"))
#                                                             #d_100767870=='353358909' & as.Date(compl_date)>as.Date(ten_emails) ~"Completion after 10 emails",
#                                                             #TRUE ~ "No Completion after 10 emails"))
# 
# after_emails$emails <- factor(after_emails$emails,levels=c("Completion the Day of Verification","Completion after 1 email", "Completion after 2 emails", "Completion after 3 emails", "Completion after 4 emails", "Completion after 5 emails", "Completion after 6 emails", "Completion after 7 emails", "Completion after 8 emails", "Completion after 9 emails", "Completion after 10 emails"))
# 
# 
# 
# dt_after_emails <- after_emails %>%  group_by(emails)  %>% dplyr::summarize(n=n(), pct=100*n/nrow(.))  %>% dplyr::ungroup() %>%  dplyr::select(emails, n, pct) 
# 
# dt_after_emails %>%  gt(rowname_col = "row_lab") %>%  
#   fmt_number(columns = "pct", decimals = 2) %>% 
#   tab_header(title = md("Baseline Module Survey Completion Response Rate")) %>%  
#   cols_label(n= md("**Number of Participants**"), emails = md("Email Reminders Sent"), pct = md("Percent of Participants")) %>% 
#     # summary_rows(
#     #   groups=F,
#     # column = c(n,pct),
#     # fns= list(
#     #   Sum= ~sum(.)
#     # ), decimals=0) %>%
#   #grand_summary_rows(fns = ~sum(c(n, pct),na.rm = T)) %>%  
#       grand_summary_rows(columns=c(n, pct),fns = ~sum(.,na.rm = T))|>
#   tab_options(
#       stub.font.weight = "bold"
#     ) %>%
#   tab_style(
#     style = list(
#       cell_text(weight = "bold")
#     ),
#     locations = cells_body(
#       columns = emails,
#     )
#   ) %>%  
#   tab_footnote(paste0("This table counts the ", sum(ptps_c$d_100767870==353358909), " participants that have currently completed all Baseline Modules. It excludes the ", sum(ptps_c$d_100767870==104430631), " participants that have not."))
# 
# 
# 

```









