---
title: "CCC Module Metrics"
author: "Kelsey Dowling"
date: "2022-10-06"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r, echo=FALSE}
## Have to manually run this section, then you can run the next section automatically
library(bigrquery)
library(dplyr)
library(gmodels)
library(epiDisplay)
library(lubridate)
bq_auth() 
1
```

```{r, echo=FALSE}
## CCC WEEKLY METRICS REPORT 



### To run the code, note questions 1,5,6,7, and 8 apply to all modules and questions 2-4 apply individually to each module. Run #1 first, then #2-4 for reach module, then #6-8


####TIME STAMP FOR REFERENCE- ADD TO THE TOP OF THE REPORT
currentTime <- Sys.time()
print(currentTime)



##Load Data from BQ

project_cc = "nih-nci-dceg-connect-prod-6d04"
billing_cc= "nih-nci-dceg-connect-prod-6d04"
queryreccc <- "SELECT  Connect_ID, d_512820379, d_821247024, d_914594314, d_832139544, 
d_949302066 , d_205553981, d_536735468 , d_976570371, d_663265240, d_265193023, d_222161762, d_770257102, d_264644252, d_265193023, d_541836531, d_386488297, 
d_452942800, d_517311251 
FROM `nih-nci-dceg-connect-prod-6d04.recruitment.recruitment1_WL` where Connect_ID IS NOT NULL"

rec_table_cc <- bq_project_query(project_cc, queryreccc)
data_c <- bq_table_download(rec_table_cc, bigint = "integer64")

#data_ccc=merge(mod1_data_cc, data_ccc, by="Connect_ID")  #tidyverse has left join

data_ccc <- data_c %>% filter(d_821247024==197316935) #must be verified
dim(data_ccc) #Number of verified participants 

active_c <- data_ccc %>% filter(d_512820379==486306141)
passive_c <- data_ccc %>% filter(d_512820379==854703046)
data_ccc <- data_ccc %>% filter(d_512820379==486306141 | d_512820379==854703046) #must be active or passive
dim(data_ccc)

```

```{r, echo = FALSE}



### Stratify by verified before all modules available in prod and verified after all modules available in prod ###

started_m1= data_ccc %>%  filter(!is.na(d_205553981) & (d_949302066==615768760 | d_949302066==231311385))  #CID 4201878434 has no start date but completed module 1....
dim(started_m1)

data_ccc_after <- data_ccc %>% filter(!is.na(d_914594314) & d_914594314>=as.Date("2022-07-05"))  #those verified AFTER all modules were available 
dim(data_ccc_after)

data_ccc_before <- data_ccc %>% filter(!is.na(d_914594314) & d_914594314<"2022-07-05") #those verified BEFORE all were available
dim(data_ccc_before)


active_c_after <- data_ccc_after %>% filter(d_512820379==486306141)
passive_c_after <- data_ccc_after %>% filter(d_512820379==854703046)

active_c_before <- data_ccc_before %>% filter(d_512820379==486306141)
passive_c_before <- data_ccc_before %>% filter(d_512820379==854703046)



####### ALL MODULES ########
####### ALL MODULES ########
#1. Survey status of verified participants: None Completed, Some Completed (Combinations), All completed. This includes impossible selections for QC check

modules <- data_ccc[,c("Connect_ID","d_512820379","d_949302066","d_536735468","d_976570371","d_663265240")] 
mods <- c("d_949302066","d_536735468","d_976570371","d_663265240")
modules$modules <- 0
modules$none <-0
for(i in 1:length(mods)){
  module <- modules[,mods[i]]
  count <- ifelse((!is.na(module) & module ==231311385), 1, 0)
  modules$modules <- count+modules$modules
  count1 <- ifelse((!is.na(module) & module==972455046), 1, 0)
  modules$none <- count1+modules$none
}

table(modules$modules)

table(modules$none)

table(modules$modules,modules$d_949302066)
CrossTable(modules$d_949302066, modules$modules,digits=4, prop.t=FALSE, prop.r=TRUE, prop.c=TRUE,prop.chisq=FALSE)

length(modules[which(modules$modules==3 & modules$d_663265240==231311385 & modules$d_536735468==231311385),])
modules1 <- modules %>% mutate(process=case_when(d_949302066 == 231311385 & modules==1 ~ "module 1 only",
                                                 d_536735468 == 231311385 & modules==1 ~ "module 2 only",
                                                 d_976570371 == 231311385 & modules==1 ~ "module 3 only",
                                                 d_663265240 == 231311385 & modules==1 ~ "module 4 only",
                                                 modules ==2 & d_949302066 == 231311385 & d_536735468 == 231311385 ~ "module 1,2" ,
                                                 modules ==2 & d_949302066 == 231311385 & d_976570371 == 231311385 ~ "module 1,3" ,
                                                 modules ==2 & d_949302066 == 231311385 & d_663265240 == 231311385 ~ "module 1,4" ,
                                                 modules ==2 & d_536735468 == 231311385 & d_976570371 == 231311385 ~ "module 2,3" ,
                                                 modules ==2 & d_536735468 == 231311385 & d_663265240 == 231311385 ~ "module 2,4" ,
                                                 modules ==2 & d_976570371 == 231311385 & d_663265240 == 231311385 ~ "module 3,4" ,
                                                 modules ==3 & d_949302066 == 231311385 & d_536735468 == 231311385 & d_976570371 == 231311385 ~ "module 1,2,3" ,
                                                 modules ==3 & d_949302066 == 231311385 & d_976570371 == 231311385 & d_663265240 == 231311385~ "module 1,3,4" ,
                                                 modules ==3 & d_949302066 == 231311385 & d_536735468 == 231311385 & d_663265240 == 231311385 ~ "module 1,2,4",
                                                 modules ==3 & d_536735468 == 231311385 & d_976570371 == 231311385 & d_663265240 == 231311385 ~ "module 2,3,4" ,
                                                 modules ==0 ~ "None",
                                                 modules ==4 ~ "All"))
table(modules1$process)
tab1(modules1$process, decimal=2,sort.group = "decreasing", cum.percent = TRUE)$output.table



############### MODULE 1 ########################################
# 2.	Completion of baseline tasks with number and % not started, started, submitted of each module (active_c, passive_c and total)

  ### BEFORE ALL MODULES AV'L
sum(active_c_before$d_949302066==972455046, na.rm=TRUE)
round((sum(active_c_before$d_949302066==972455046, na.rm=TRUE)/length(active_c_before$d_949302066))*100, digits=2) #not started
sum(active_c_before$d_949302066==615768760, na.rm=TRUE)
round((sum(active_c_before$d_949302066==615768760, na.rm=TRUE)/length(active_c_before$d_949302066))*100, digits=2)#started
sum(active_c_before$d_949302066==231311385, na.rm=TRUE)
round((sum(active_c_before$d_949302066==231311385, na.rm=TRUE)/length(active_c_before$d_949302066))*100, digits=2)#submitted

sum(passive_c_before$d_949302066==972455046, na.rm=TRUE)
round((sum(passive_c_before$d_949302066==972455046, na.rm=TRUE)/length(passive_c_before$d_949302066))*100, digits=2) #not started
sum(passive_c_before$d_949302066==615768760, na.rm=TRUE)
round((sum(passive_c_before$d_949302066==615768760, na.rm=TRUE)/length(passive_c_before$d_949302066))*100, digits=2)#started
sum(passive_c_before$d_949302066==231311385, na.rm=TRUE)
round((sum(passive_c_before$d_949302066==231311385, na.rm=TRUE)/length(passive_c_before$d_949302066))*100, digits=2)#submitted

sum(data_ccc_before$d_949302066==972455046, na.rm=TRUE)
round((sum(data_ccc_before$d_949302066==972455046, na.rm=TRUE)/length(data_ccc_before$d_949302066))*100, digits=2) #not started
sum(data_ccc_before$d_949302066==615768760, na.rm=TRUE)
round((sum(data_ccc_before$d_949302066==615768760, na.rm=TRUE)/length(data_ccc_before$d_949302066))*100, digits=2) #started
sum(data_ccc_before$d_949302066==231311385, na.rm=TRUE)
round((sum(data_ccc_before$d_949302066==231311385, na.rm=TRUE)/length(data_ccc_before$d_949302066))*100, digits=2) #submitted


  ### AFTER ALL MODULES AV'L 
sum(active_c_after$d_949302066==972455046, na.rm=TRUE)
round((sum(active_c_after$d_949302066==972455046, na.rm=TRUE)/length(active_c_after$d_949302066))*100, digits=2) #not started
sum(active_c_after$d_949302066==615768760, na.rm=TRUE)
round((sum(active_c_after$d_949302066==615768760, na.rm=TRUE)/length(active_c_after$d_949302066))*100, digits=2)#started
sum(active_c_after$d_949302066==231311385, na.rm=TRUE)
round((sum(active_c_after$d_949302066==231311385, na.rm=TRUE)/length(active_c_after$d_949302066))*100, digits=2)#submitted

sum(passive_c_after$d_949302066==972455046, na.rm=TRUE)
round((sum(passive_c_after$d_949302066==972455046, na.rm=TRUE)/length(passive_c_after$d_949302066))*100, digits=2) #not started
sum(passive_c_after$d_949302066==615768760, na.rm=TRUE)
round((sum(passive_c_after$d_949302066==615768760, na.rm=TRUE)/length(passive_c_after$d_949302066))*100, digits=2)#started
sum(passive_c_after$d_949302066==231311385, na.rm=TRUE)
round((sum(passive_c_after$d_949302066==231311385, na.rm=TRUE)/length(passive_c_after$d_949302066))*100, digits=2)#submitted

sum(data_ccc_after$d_949302066==972455046, na.rm=TRUE)
round((sum(data_ccc_after$d_949302066==972455046, na.rm=TRUE)/length(data_ccc_after$d_949302066))*100, digits=2) #not started
sum(data_ccc_after$d_949302066==615768760, na.rm=TRUE)
round((sum(data_ccc_after$d_949302066==615768760, na.rm=TRUE)/length(data_ccc_after$d_949302066))*100, digits=2) #started
sum(data_ccc_after$d_949302066==231311385, na.rm=TRUE)
round((sum(data_ccc_after$d_949302066==231311385, na.rm=TRUE)/length(data_ccc_after$d_949302066))*100, digits=2) #submitted


# 3.	Time from verification to completion of each module- Hours 25, 50, 75 percentile (active_c, passive_c and total)  
#d_914594314 verified
#d_517311251 Mod1 completion time stamp

time.var1 <- c("d_914594314","d_517311251")

###BEFORE
#All verified participant totals that have completed mod1
act_before= active_c_before %>% filter(d_949302066==231311385)
dim(act_before)
pas_before= passive_c_before %>% filter(d_949302066==231311385)
dim(pas_before)
mer_before= data_ccc_before %>% filter(d_949302066==231311385)
dim(mer_before)


#Active
act_before_time<- act_before[complete.cases(act_before[ , time.var1]), ]


tmp1A <- act_before_time[,c("Connect_ID","d_914594314","d_517311251")]
tmp1A$d_914594314 <- as.POSIXct(ymd_hms(tmp1A$d_914594314))
tmp1A$d_517311251 <- as.POSIXct(ymd_hms(tmp1A$d_517311251))


tmp1A$Mod1completionA <- difftime(tmp1A$d_517311251, tmp1A$d_914594314, units="mins")
summary(as.numeric(tmp1A$Mod1completionA)) #normal for some of these to be negative, active parts. can get verified later on


#Passive
pas_before_time<- pas_before[complete.cases(pas_before[ , time.var1]), ]


tmp1P <- pas_before_time[,c("Connect_ID","d_914594314","d_517311251")]
tmp1P$d_914594314 <- as.POSIXct(ymd_hms(tmp1P$d_914594314))
tmp1P$d_517311251 <- as.POSIXct(ymd_hms(tmp1P$d_517311251))


tmp1P$Mod1completionP <- difftime(tmp1P$d_517311251, tmp1P$d_914594314, units="mins")
summary(as.numeric(tmp1P$Mod1completionP)) #good that these are all positive, passives NEED to be verified first 


#Total
mer_before_time<- mer_before[complete.cases(mer_before[ , time.var1]), ]


tmp1T <- mer_before_time[,c("Connect_ID","d_914594314","d_517311251")]
tmp1T$d_914594314 <- as.POSIXct(ymd_hms(tmp1T$d_914594314))
tmp1T$d_517311251 <- as.POSIXct(ymd_hms(tmp1T$d_517311251))


tmp1T$Mod1completionT <- difftime(tmp1T$d_517311251, tmp1T$d_914594314, units="mins")
summary(as.numeric(tmp1T$Mod1completionT))



###AFTER
#All verified participant totals that have completed mod1
act_after= active_c_after %>% filter(d_949302066==231311385)
dim(act_after)
pas_after= passive_c_after %>% filter(d_949302066==231311385)
dim(pas_after)
mer_after= data_ccc_after %>% filter(d_949302066==231311385)
dim(mer_after)


#Active
act_after_time<- act_after[complete.cases(act_after[ , time.var1]), ]


tmp1A <- act_after_time[,c("Connect_ID","d_914594314","d_517311251")]
tmp1A$d_914594314 <- as.POSIXct(ymd_hms(tmp1A$d_914594314))
tmp1A$d_517311251 <- as.POSIXct(ymd_hms(tmp1A$d_517311251))


tmp1A$Mod1completionA <- difftime(tmp1A$d_517311251, tmp1A$d_914594314, units="mins")
summary(as.numeric(tmp1A$Mod1completionA)) #normal for some of these to be negative, active parts. can get verified later on

#Passive
pas_after_time<- pas_after[complete.cases(pas_after[ , time.var1]), ]


tmp1P <- pas_after_time[,c("Connect_ID","d_914594314","d_517311251")]
tmp1P$d_914594314 <- as.POSIXct(ymd_hms(tmp1P$d_914594314))
tmp1P$d_517311251 <- as.POSIXct(ymd_hms(tmp1P$d_517311251))


tmp1P$Mod1completionP <- difftime(tmp1P$d_517311251, tmp1P$d_914594314, units="mins")
summary(as.numeric(tmp1P$Mod1completionP)) #good that these are all positive, passsive NEED to be verified first 


#Total
mer_after_time<- mer_after[complete.cases(mer_after[ , time.var1]), ]


tmp1T <- mer_after_time[,c("Connect_ID","d_914594314","d_517311251")]
tmp1T$d_914594314 <- as.POSIXct(ymd_hms(tmp1T$d_914594314))
tmp1T$d_517311251 <- as.POSIXct(ymd_hms(tmp1T$d_517311251))


tmp1T$Mod1completionT <- difftime(tmp1T$d_517311251, tmp1T$d_914594314, units="mins")
summary(as.numeric(tmp1T$Mod1completionT))




#4.	Duration from start to submitted for each module (active_c, passive_c and total)  <<rows 44-48 in ltd file
#d_205553981 time stamp started
#d_517311251 time stamp finished 

time.var.1 <- c("d_205553981","d_517311251")


##BEFORE
#All participant totals, active_c total and passive_c total
sum(active_c_before$d_949302066==231311385, na.rm=TRUE)
sum(passive_c_before$d_949302066==231311385, na.rm=TRUE)
sum(data_ccc_before$d_949302066==231311385, na.rm=TRUE)

#active_c
act1= active_c_before %>% filter(active_c_before$d_949302066==231311385)
#act1_time <- act1[complete.cases(time.var.1)]
act1_time<- act1[complete.cases(act1[ , time.var.1]), ]


Atmp1 <- act1_time[,c("Connect_ID","d_205553981","d_517311251")]
Atmp1$d_205553981 <- as.POSIXct(ymd_hms(Atmp1$d_205553981))
Atmp1$d_517311251 <- as.POSIXct(ymd_hms(Atmp1$d_517311251))


Atmp1$Mod1completionA <- difftime(Atmp1$d_517311251, Atmp1$d_205553981, units="mins")
summary(as.numeric(Atmp1$Mod1completionA))

sum((1/3)>Atmp1$Mod1completionA & Atmp1$Mod1completionA>(1/6))/sum(active_c_before$d_949302066==231311385, na.rm=TRUE)
sum((1/2)>Atmp1$Mod1completionA & Atmp1$Mod1completionA>(1/3))/sum(active_c_before$d_949302066==231311385, na.rm=TRUE)
sum(Atmp1$Mod1completionA>(2/3))/sum(active_c$d_949302066==231311385, na.rm=TRUE)

#passive_c
pas1= passive_c_before %>% filter(passive_c_before$d_949302066==231311385)
#pas1_time <- pas1[complete.cases(time.var.1)]
pas1_time<- pas1[complete.cases(pas1[ , time.var.1]), ]


Ptmp1 <- pas1_time[,c("Connect_ID","d_205553981","d_517311251")]
Ptmp1$d_205553981 <- as.POSIXct(ymd_hms(Ptmp1$d_205553981))
Ptmp1$d_517311251 <- as.POSIXct(ymd_hms(Ptmp1$d_517311251))


Ptmp1$Mod1completionP <- difftime(Ptmp1$d_517311251, Ptmp1$d_205553981, units="mins")
Ptmp1$Mod1completionP <- as.numeric(Ptmp1$Mod1completionP)
summary(Ptmp1$Mod1completionP)

sum((1/3)>Ptmp1$Mod1completionP & Ptmp1$Mod1completionP>(1/6), na.rm=TRUE)/sum(passive_c_before$d_949302066==231311385, na.rm=TRUE)
sum((1/2)>Ptmp1$Mod1completionP & Ptmp1$Mod1completionP>(1/3), na.rm=TRUE)/sum(passive_c_before$d_949302066==231311385, na.rm=TRUE)
sum(Ptmp1$Mod1completionP>(2/3), na.rm=TRUE)/sum(passive_c$d_949302066==231311385, na.rm=TRUE)


#Total
mer1= data_ccc_before %>% filter(data_ccc_before$d_949302066==231311385)
#mer1_time <- mer1[complete.cases(time.var.1)]
mer1_time<- mer1[complete.cases(mer1[ , time.var.1]), ]


Ttmp1 <- mer1_time[,c("Connect_ID","d_205553981","d_517311251")]
Ttmp1$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1$d_205553981))
Ttmp1$d_517311251 <- as.POSIXct(ymd_hms(Ttmp1$d_517311251))


Ttmp1$Mod1completionT <- difftime(Ttmp1$d_517311251, Ttmp1$d_205553981, units="mins")
summary(as.numeric(Ttmp1$Mod1completionT))

sum((1/3)>Ttmp1$Mod1completionT & Ttmp1$Mod1completionT>(1/6), na.rm=TRUE)/sum(data_ccc_before$d_949302066==231311385, na.rm=TRUE)
sum((1/2)>Ttmp1$Mod1completionT & Ttmp1$Mod1completionT>(1/3), na.rm=TRUE)/sum(data_ccc_before$d_949302066==231311385, na.rm=TRUE)
sum(Ttmp1$Mod1completionT>(2/3), na.rm=TRUE)/sum(data_ccc$d_949302066==231311385, na.rm=TRUE)



##AFTER
#All participant totals, active_c total and passive_c total
sum(active_c_after$d_949302066==231311385, na.rm=TRUE)
sum(passive_c_after$d_949302066==231311385, na.rm=TRUE)
sum(data_ccc_after$d_949302066==231311385, na.rm=TRUE)

#active_c
act1= active_c_after %>% filter(active_c_after$d_949302066==231311385)
#act1_time <- act1[complete.cases(time.var.1)]
act1_time<- act1[complete.cases(act1[ , time.var.1]), ]


Atmp1 <- act1_time[,c("Connect_ID","d_205553981","d_517311251")]
Atmp1$d_205553981 <- as.POSIXct(ymd_hms(Atmp1$d_205553981))
Atmp1$d_517311251 <- as.POSIXct(ymd_hms(Atmp1$d_517311251))


Atmp1$Mod1completionA <- difftime(Atmp1$d_517311251, Atmp1$d_205553981, units="mins")
summary(as.numeric(Atmp1$Mod1completionA))

sum((1/3)>Atmp1$Mod1completionA & Atmp1$Mod1completionA>(1/6))/sum(active_c_after$d_949302066==231311385, na.rm=TRUE)
sum((1/2)>Atmp1$Mod1completionA & Atmp1$Mod1completionA>(1/3))/sum(active_c_after$d_949302066==231311385, na.rm=TRUE)
sum(Atmp1$Mod1completionA>(2/3))/sum(active_c$d_949302066==231311385, na.rm=TRUE)

#passive_c
pas1= passive_c_after %>% filter(passive_c_after$d_949302066==231311385)
#pas1_time <- pas1[complete.cases(time.var.1)]
pas1_time<- pas1[complete.cases(pas1[ , time.var.1]), ]


Ptmp1 <- pas1_time[,c("Connect_ID","d_205553981","d_517311251")]
Ptmp1$d_205553981 <- as.POSIXct(ymd_hms(Ptmp1$d_205553981))
Ptmp1$d_517311251 <- as.POSIXct(ymd_hms(Ptmp1$d_517311251))


Ptmp1$Mod1completionP <- difftime(Ptmp1$d_517311251, Ptmp1$d_205553981, units="mins")
Ptmp1$Mod1completionP <- as.numeric(Ptmp1$Mod1completionP)
summary(Ptmp1$Mod1completionP)

sum((1/3)>Ptmp1$Mod1completionP & Ptmp1$Mod1completionP>(1/6), na.rm=TRUE)/sum(passive_c_after$d_949302066==231311385, na.rm=TRUE)
sum((1/2)>Ptmp1$Mod1completionP & Ptmp1$Mod1completionP>(1/3), na.rm=TRUE)/sum(passive_c_after$d_949302066==231311385, na.rm=TRUE)
sum(Ptmp1$Mod1completionP>(2/3), na.rm=TRUE)/sum(passive_c$d_949302066==231311385, na.rm=TRUE)


#Total
mer1= data_ccc_after %>% filter(data_ccc_after$d_949302066==231311385)
#mer1_time <- mer1[complete.cases(time.var.1)]
mer1_time<- mer1[complete.cases(mer1[ , time.var.1]), ]


Ttmp1 <- mer1_time[,c("Connect_ID","d_205553981","d_517311251")]
Ttmp1$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1$d_205553981))
Ttmp1$d_517311251 <- as.POSIXct(ymd_hms(Ttmp1$d_517311251))


Ttmp1$Mod1completionT <- difftime(Ttmp1$d_517311251, Ttmp1$d_205553981, units="mins")
summary(as.numeric(Ttmp1$Mod1completionT))

sum((1/3)>Ttmp1$Mod1completionT & Ttmp1$Mod1completionT>(1/6), na.rm=TRUE)/sum(data_ccc_after$d_949302066==231311385, na.rm=TRUE)
sum((1/2)>Ttmp1$Mod1completionT & Ttmp1$Mod1completionT>(1/3), na.rm=TRUE)/sum(data_ccc_after$d_949302066==231311385, na.rm=TRUE)
sum(Ttmp1$Mod1completionT>(2/3), na.rm=TRUE)/sum(data_ccc$d_949302066==231311385, na.rm=TRUE)

#viewing streamlining participants and those taking an unusually long time to finish 
data_ccc$Connect_ID[which.max(Ttmp1$Mod1completionT)]
data_ccc$Connect_ID[which.min(Ttmp1$Mod1completionT)]



############### MODULE 2 ########################################


#2. Completion of baseline tasks with number and % not started, started, submitted of each module (active_c, passive_c and total)  

### BEFORE ALL MODULES AV'L
sum(active_c_before$d_536735468==972455046, na.rm=TRUE)
round((sum(active_c_before$d_536735468==972455046, na.rm=TRUE)/length(active_c_before$d_536735468))*100, digits=2) #not started
sum(active_c_before$d_536735468==615768760, na.rm=TRUE)
round((sum(active_c_before$d_536735468==615768760, na.rm=TRUE)/length(active_c_before$d_536735468))*100, digits=2)#started
sum(active_c_before$d_536735468==231311385, na.rm=TRUE)
round((sum(active_c_before$d_536735468==231311385, na.rm=TRUE)/length(active_c_before$d_536735468))*100, digits=2)#submitted

sum(passive_c_before$d_536735468==972455046, na.rm=TRUE)
round((sum(passive_c_before$d_536735468==972455046, na.rm=TRUE)/length(passive_c_before$d_536735468))*100, digits=2) #not started
sum(passive_c_before$d_536735468==615768760, na.rm=TRUE)
round((sum(passive_c_before$d_536735468==615768760, na.rm=TRUE)/length(passive_c_before$d_536735468))*100, digits=2)#started
sum(passive_c_before$d_536735468==231311385, na.rm=TRUE)
round((sum(passive_c_before$d_536735468==231311385, na.rm=TRUE)/length(passive_c_before$d_536735468))*100, digits=2)#submitted

sum(data_ccc_before$d_536735468==972455046, na.rm=TRUE)
round((sum(data_ccc_before$d_536735468==972455046, na.rm=TRUE)/length(data_ccc_before$d_536735468))*100, digits=2) #not started
sum(data_ccc_before$d_536735468==615768760, na.rm=TRUE)
round((sum(data_ccc_before$d_536735468==615768760, na.rm=TRUE)/length(data_ccc_before$d_536735468))*100, digits=2) #started
sum(data_ccc_before$d_536735468==231311385, na.rm=TRUE)
round((sum(data_ccc_before$d_536735468==231311385, na.rm=TRUE)/length(data_ccc_before$d_536735468))*100, digits=2) #submitted


### AFTER ALL MODULES AV'L 
sum(active_c_after$d_536735468==972455046, na.rm=TRUE)
round((sum(active_c_after$d_536735468==972455046, na.rm=TRUE)/length(active_c_after$d_536735468))*100, digits=2) #not started
sum(active_c_after$d_536735468==615768760, na.rm=TRUE)
round((sum(active_c_after$d_536735468==615768760, na.rm=TRUE)/length(active_c_after$d_536735468))*100, digits=2)#started
sum(active_c_after$d_536735468==231311385, na.rm=TRUE)
round((sum(active_c_after$d_536735468==231311385, na.rm=TRUE)/length(active_c_after$d_536735468))*100, digits=2)#submitted

sum(passive_c_after$d_536735468==972455046, na.rm=TRUE)
round((sum(passive_c_after$d_536735468==972455046, na.rm=TRUE)/length(passive_c_after$d_536735468))*100, digits=2) #not started
sum(passive_c_after$d_536735468==615768760, na.rm=TRUE)
round((sum(passive_c_after$d_536735468==615768760, na.rm=TRUE)/length(passive_c_after$d_536735468))*100, digits=2)#started
sum(passive_c_after$d_536735468==231311385, na.rm=TRUE)
round((sum(passive_c_after$d_536735468==231311385, na.rm=TRUE)/length(passive_c_after$d_536735468))*100, digits=2)#submitted

sum(data_ccc_after$d_536735468==972455046, na.rm=TRUE)
round((sum(data_ccc_after$d_536735468==972455046, na.rm=TRUE)/length(data_ccc_after$d_536735468))*100, digits=2) #not started
sum(data_ccc_after$d_536735468==615768760, na.rm=TRUE)
round((sum(data_ccc_after$d_536735468==615768760, na.rm=TRUE)/length(data_ccc_after$d_536735468))*100, digits=2) #started
sum(data_ccc_after$d_536735468==231311385, na.rm=TRUE)
round((sum(data_ccc_after$d_536735468==231311385, na.rm=TRUE)/length(data_ccc_after$d_536735468))*100, digits=2) #submitted

sum(active_c$d_536735468==972455046, na.rm=TRUE)
round((sum(active_c$d_536735468==972455046, na.rm=TRUE)/length(active_c$d_536735468))*100, digits=2) #not started
sum(active_c$d_536735468==615768760, na.rm=TRUE)
round((sum(active_c$d_536735468==615768760, na.rm=TRUE)/length(active_c$d_536735468))*100, digits=2) #started
sum(active_c$d_536735468==231311385, na.rm=TRUE)
round((sum(active_c$d_536735468==231311385, na.rm=TRUE)/length(active_c$d_536735468))*100, digits=2) #submitted


# 3.	Time from verification to completion of each module (active, passive and total) 
time.var2 <- c("d_914594314","d_832139544")


##AFTER
#All verified participant totals, verified active total and verified passive total
act2 <- active_c_after %>%  filter(d_536735468==231311385)
dim(act2)
pas2 <- passive_c_after %>% filter(d_536735468==231311385)
dim(pas2)
mer2 <- data_ccc_after %>% filter(d_536735468==231311385)
dim(mer2)

#Active
act2_time<- act2[complete.cases(act2[ , time.var2]), ]

tmpA <- act2_time[,c("Connect_ID","d_914594314","d_832139544")]
tmpA$d_914594314 <- as.POSIXct(ymd_hms(tmpA$d_914594314))
tmpA$d_832139544 <- as.POSIXct(ymd_hms(tmpA$d_832139544))


tmpA$Mod2completionA <- difftime(tmpA$d_832139544, tmpA$d_914594314, units="mins")
summary(as.numeric(tmpA$Mod2completionA))   #normal for some of these to be negative, active parts. can get verified later on



#Passive
pas2_time<- pas2[complete.cases(pas2[ , time.var2]), ]


tmp2P <- pas2_time[,c("Connect_ID","d_914594314","d_832139544")]
tmp2P$d_914594314 <- as.POSIXct(ymd_hms(tmp2P$d_914594314))
tmp2P$d_832139544 <- as.POSIXct(ymd_hms(tmp2P$d_832139544))


tmp2P$Mod2completionP <- difftime(tmp2P$d_832139544, tmp2P$d_914594314, units="mins")
summary(as.numeric(tmp2P$Mod2completionP)) #good that these are all positive, passives NEED to be verified first 

#Total
mer2_time<- mer2[complete.cases(mer2[ , time.var2]), ]


tmp2T <- mer2_time[,c("Connect_ID","d_914594314","d_832139544")]
tmp2T$d_914594314 <- as.POSIXct(ymd_hms(tmp2T$d_914594314))
tmp2T$d_832139544 <- as.POSIXct(ymd_hms(tmp2T$d_832139544))


tmp2T$Mod2completionT <- difftime(tmp2T$d_832139544, tmp2T$d_914594314, units="mins")
summary(as.numeric(tmp2T$Mod2completionT))


# 4.	Duration from start to submitted for each module (active, passive and total)  <<rows 44-48 in ltd file  

time.var.2 <- c("d_541836531","d_832139544")

##BEFORE
#All participant totals, active total and passive total
sum(active_c_before$d_536735468==231311385, na.rm=TRUE)
sum(passive_c_before$d_536735468==231311385, na.rm=TRUE)
sum(data_ccc_before$d_536735468==231311385, na.rm=TRUE)


#Active
actm2= active_c_before %>% filter(active_c_before$d_536735468==231311385)
#actm2_time <- actm2[complete.cases(time.var.2)]
actm2_time<- actm2[complete.cases(actm2[ , time.var.2]), ]


tmp <- actm2_time[,c("Connect_ID","d_541836531","d_832139544")]
tmp$d_541836531 <- as.POSIXct(ymd_hms(tmp$d_541836531))
tmp$d_832139544 <- as.POSIXct(ymd_hms(tmp$d_832139544))


tmp$Mod2completionA <- difftime(tmp$d_832139544, tmp$d_541836531, units="mins")
summary(as.numeric(tmp$Mod2completionA))

sum((1/3)>tmp$Mod2completionA & tmp$Mod2completionA>(1/6), na.rm=TRUE)/sum(active_c_before$d_536735468==231311385, na.rm=TRUE)
sum((1/2)>tmp$Mod2completionA & tmp$Mod2completionA>(1/3), na.rm=TRUE)/sum(active_c_before$d_536735468==231311385, na.rm=TRUE)
sum(tmp$Mod2completionA>(2/3), na.rm=TRUE)/sum(active_c$d_536735468==231311385, na.rm=TRUE)

#Passive
pasm2= passive_c_before %>% filter(passive_c_before$d_536735468==231311385)
#pasm2_time <- pasm2[complete.cases(time.var.2)]
pasm2_time<- pasm2[complete.cases(pasm2[ , time.var.2]), ]


ptmp <- pasm2_time[,c("Connect_ID","d_541836531","d_832139544")]
ptmp$d_541836531 <- as.POSIXct(ymd_hms(ptmp$d_541836531))
ptmp$d_832139544 <- as.POSIXct(ymd_hms(ptmp$d_832139544))


ptmp$Mod2completionP <- difftime(ptmp$d_832139544, ptmp$d_541836531, units="mins")
summary(as.numeric(ptmp$Mod2completionP))

sum((1/3)>ptmp$Mod2completionP & ptmp$Mod2completionP>(1/6), na.rm=TRUE)/sum(passive_c_before$d_536735468==231311385, na.rm=TRUE)
sum((1/2)>ptmp$Mod2completionP & ptmp$Mod2completionP>(1/3), na.rm=TRUE)/sum(passive_c_before$d_536735468==231311385, na.rm=TRUE)
sum(ptmp$Mod2completionP>(2/3), na.rm=TRUE)/sum(passive_c$d_536735468==231311385, na.rm=TRUE)

#Total
merm2= data_ccc_before %>% filter(data_ccc_before$d_536735468==231311385)
#merm2_time <- merm2[complete.cases(time.var.2)]
merm2_time<- merm2[complete.cases(merm2[ , time.var.2]), ]


Ttmp <- merm2_time[,c("Connect_ID","d_541836531","d_832139544")]
Ttmp$d_541836531 <- as.POSIXct(ymd_hms(Ttmp$d_541836531))
Ttmp$d_832139544 <- as.POSIXct(ymd_hms(Ttmp$d_832139544))


Ttmp$Mod2completionT <- difftime(Ttmp$d_832139544, Ttmp$d_541836531, units="mins")
summary(as.numeric(Ttmp$Mod2completionT))

sum((1/3)>Ttmp$Mod2completionT & Ttmp$Mod2completionT>(1/6), na.rm=TRUE)/sum(data_ccc_before$d_536735468==231311385, na.rm=TRUE)
sum((1/2)>Ttmp$Mod2completionT & Ttmp$Mod2completionT>(1/3), na.rm=TRUE)/sum(data_ccc_before$d_536735468==231311385, na.rm=TRUE)
sum(Ttmp$Mod2completionT>(2/3), na.rm=TRUE)/sum(data_ccc$d_536735468==231311385, na.rm=TRUE)


##AFTER
#All participant totals, active total and passive total
sum(active_c_after$d_536735468==231311385, na.rm=TRUE)
sum(passive_c_after$d_536735468==231311385, na.rm=TRUE)
sum(data_ccc_after$d_536735468==231311385, na.rm=TRUE)


#Active
actm2= active_c_after %>% filter(active_c_after$d_536735468==231311385)
#actm2_time <- actm2[complete.cases(time.var.2)]
actm2_time<- actm2[complete.cases(actm2[ , time.var.2]), ]


tmp <- actm2_time[,c("Connect_ID","d_541836531","d_832139544")]
tmp$d_541836531 <- as.POSIXct(ymd_hms(tmp$d_541836531))
tmp$d_832139544 <- as.POSIXct(ymd_hms(tmp$d_832139544))


tmp$Mod2completionA <- difftime(tmp$d_832139544, tmp$d_541836531, units="mins")
summary(as.numeric(tmp$Mod2completionA))

sum((1/3)>tmp$Mod2completionA & tmp$Mod2completionA>(1/6), na.rm=TRUE)/sum(active_c_after$d_536735468==231311385, na.rm=TRUE)
sum((1/2)>tmp$Mod2completionA & tmp$Mod2completionA>(1/3), na.rm=TRUE)/sum(active_c_after$d_536735468==231311385, na.rm=TRUE)
sum(tmp$Mod2completionA>(2/3), na.rm=TRUE)/sum(active_c$d_536735468==231311385, na.rm=TRUE)

#Passive
pasm2= passive_c_after %>% filter(passive_c_after$d_536735468==231311385)
#pasm2_time <- pasm2[complete.cases(time.var.2)]
pasm2_time<- pasm2[complete.cases(pasm2[ , time.var.2]), ]


ptmp <- pasm2_time[,c("Connect_ID","d_541836531","d_832139544")]
ptmp$d_541836531 <- as.POSIXct(ymd_hms(ptmp$d_541836531))
ptmp$d_832139544 <- as.POSIXct(ymd_hms(ptmp$d_832139544))


ptmp$Mod2completionP <- difftime(ptmp$d_832139544, ptmp$d_541836531, units="mins")
summary(as.numeric(ptmp$Mod2completionP))

sum((1/3)>ptmp$Mod2completionP & ptmp$Mod2completionP>(1/6), na.rm=TRUE)/sum(passive_c_after$d_536735468==231311385, na.rm=TRUE)
sum((1/2)>ptmp$Mod2completionP & ptmp$Mod2completionP>(1/3), na.rm=TRUE)/sum(passive_c_after$d_536735468==231311385, na.rm=TRUE)
sum(ptmp$Mod2completionP>(2/3), na.rm=TRUE)/sum(passive_c$d_536735468==231311385, na.rm=TRUE)

#Total
merm2= data_ccc_after %>% filter(data_ccc_after$d_536735468==231311385)
#merm2_time <- merm2[complete.cases(time.var.2)]
merm2_time<- merm2[complete.cases(merm2[ , time.var.2]), ]


Ttmp <- merm2_time[,c("Connect_ID","d_541836531","d_832139544")]
Ttmp$d_541836531 <- as.POSIXct(ymd_hms(Ttmp$d_541836531))
Ttmp$d_832139544 <- as.POSIXct(ymd_hms(Ttmp$d_832139544))


Ttmp$Mod2completionT <- difftime(Ttmp$d_832139544, Ttmp$d_541836531, units="mins")
summary(as.numeric(Ttmp$Mod2completionT))

sum((1/3)>Ttmp$Mod2completionT & Ttmp$Mod2completionT>(1/6), na.rm=TRUE)/sum(data_ccc_after$d_536735468==231311385, na.rm=TRUE)
sum((1/2)>Ttmp$Mod2completionT & Ttmp$Mod2completionT>(1/3), na.rm=TRUE)/sum(data_ccc_after$d_536735468==231311385, na.rm=TRUE)
sum(Ttmp$Mod2completionT>(2/3), na.rm=TRUE)/sum(data_ccc$d_536735468==231311385, na.rm=TRUE)

#viewing streamlining participants and those taking an unusually long time to finish 
data_ccc$Connect_ID[which.max(Ttmp$Mod2completionT)]
data_ccc$Connect_ID[which.min(Ttmp$Mod2completionT)]


############### MODULE 3 ########################################

# 2.	Completion of baseline tasks with number and % not started, started, submitted of each module (active_c, passive_c and total) 

### BEFORE ALL MODULES AV'L
sum(active_c_before$d_976570371==972455046, na.rm=TRUE)
round((sum(active_c_before$d_976570371==972455046, na.rm=TRUE)/length(active_c_before$d_976570371))*100, digits=2) #not started
sum(active_c_before$d_976570371==615768760, na.rm=TRUE)
round((sum(active_c_before$d_976570371==615768760, na.rm=TRUE)/length(active_c_before$d_976570371))*100, digits=2)#started
sum(active_c_before$d_976570371==231311385, na.rm=TRUE)
round((sum(active_c_before$d_976570371==231311385, na.rm=TRUE)/length(active_c_before$d_976570371))*100, digits=2)#submitted

sum(passive_c_before$d_976570371==972455046, na.rm=TRUE)
round((sum(passive_c_before$d_976570371==972455046, na.rm=TRUE)/length(passive_c_before$d_976570371))*100, digits=2) #not started
sum(passive_c_before$d_976570371==615768760, na.rm=TRUE)
round((sum(passive_c_before$d_976570371==615768760, na.rm=TRUE)/length(passive_c_before$d_976570371))*100, digits=2)#started
sum(passive_c_before$d_976570371==231311385, na.rm=TRUE)
round((sum(passive_c_before$d_976570371==231311385, na.rm=TRUE)/length(passive_c_before$d_976570371))*100, digits=2)#submitted

sum(data_ccc_before$d_976570371==972455046, na.rm=TRUE)
round((sum(data_ccc_before$d_976570371==972455046, na.rm=TRUE)/length(data_ccc_before$d_976570371))*100, digits=2) #not started
sum(data_ccc_before$d_976570371==615768760, na.rm=TRUE)
round((sum(data_ccc_before$d_976570371==615768760, na.rm=TRUE)/length(data_ccc_before$d_976570371))*100, digits=2) #started
sum(data_ccc_before$d_976570371==231311385, na.rm=TRUE)
round((sum(data_ccc_before$d_976570371==231311385, na.rm=TRUE)/length(data_ccc_before$d_976570371))*100, digits=2) #submitted


### AFTER ALL MODULES AV'L 
sum(active_c_after$d_976570371==972455046, na.rm=TRUE)
round((sum(active_c_after$d_976570371==972455046, na.rm=TRUE)/length(active_c_after$d_976570371))*100, digits=2) #not started
sum(active_c_after$d_976570371==615768760, na.rm=TRUE)
round((sum(active_c_after$d_976570371==615768760, na.rm=TRUE)/length(active_c_after$d_976570371))*100, digits=2)#started
sum(active_c_after$d_976570371==231311385, na.rm=TRUE)
round((sum(active_c_after$d_976570371==231311385, na.rm=TRUE)/length(active_c_after$d_976570371))*100, digits=2)#submitted

sum(passive_c_after$d_976570371==972455046, na.rm=TRUE)
round((sum(passive_c_after$d_976570371==972455046, na.rm=TRUE)/length(passive_c_after$d_976570371))*100, digits=2) #not started
sum(passive_c_after$d_976570371==615768760, na.rm=TRUE)
round((sum(passive_c_after$d_976570371==615768760, na.rm=TRUE)/length(passive_c_after$d_976570371))*100, digits=2)#started
sum(passive_c_after$d_976570371==231311385, na.rm=TRUE)
round((sum(passive_c_after$d_976570371==231311385, na.rm=TRUE)/length(passive_c_after$d_976570371))*100, digits=2)#submitted

sum(data_ccc_after$d_976570371==972455046, na.rm=TRUE)
round((sum(data_ccc_after$d_976570371==972455046, na.rm=TRUE)/length(data_ccc_after$d_976570371))*100, digits=2) #not started
sum(data_ccc_after$d_976570371==615768760, na.rm=TRUE)
round((sum(data_ccc_after$d_976570371==615768760, na.rm=TRUE)/length(data_ccc_after$d_976570371))*100, digits=2) #started
sum(data_ccc_after$d_976570371==231311385, na.rm=TRUE)
round((sum(data_ccc_after$d_976570371==231311385, na.rm=TRUE)/length(data_ccc_after$d_976570371))*100, digits=2) #submitted



# 3.	Time from verification to completion of each module (active, passive and total) 
#d_770257102 completed
time.var3 <- c("d_914594314","d_770257102")


#All verified participant totals, verified active total and verified passive total
act3 <- active_c_after %>% filter(d_976570371==231311385)
dim(act3)
pas3 <- passive_c_after %>% filter(d_976570371==231311385)
dim(pas3)
mer3 <- data_ccc_after %>% filter(d_976570371==231311385)
dim(mer3)

#Active
#act3_time <- act3[complete.cases(time.var3)]
act3_time<- act3[complete.cases(act3[ , time.var3]), ]


tmp3A <- act3_time[,c("Connect_ID","d_914594314","d_770257102")]
tmp3A$d_914594314 <- as.POSIXct(ymd_hms(tmp3A$d_914594314))
tmp3A$d_770257102 <- as.POSIXct(ymd_hms(tmp3A$d_770257102))


tmp3A$Mod3completionA <- difftime(tmp3A$d_770257102, tmp3A$d_914594314, units="mins")
summary(as.numeric(tmp3A$Mod3completionA))


#Passive
#pas3_time <- pas3[complete.cases(time.var3)]
pas3_time<- pas3[complete.cases(pas3[ , time.var3]), ]


Ptmp3A <- pas3_time[,c("Connect_ID","d_914594314","d_770257102")]
Ptmp3A$d_914594314 <- as.POSIXct(ymd_hms(Ptmp3A$d_914594314))
Ptmp3A$d_770257102 <- as.POSIXct(ymd_hms(Ptmp3A$d_770257102))


Ptmp3A$Mod3completionP <- difftime(Ptmp3A$d_770257102, Ptmp3A$d_914594314, units="mins")
summary(as.numeric(Ptmp3A$Mod3completionP))


#Total
#mer3_time <- mer3[complete.cases(time.var3)]
mer3_time<- mer3[complete.cases(mer3[ , time.var3]), ]


Ttmp3T <- mer3_time[,c("Connect_ID","d_914594314","d_770257102")]
Ttmp3T$d_914594314 <- as.POSIXct(ymd_hms(Ttmp3T$d_914594314))
Ttmp3T$d_770257102 <- as.POSIXct(ymd_hms(Ttmp3T$d_770257102))


Ttmp3T$Mod3completionT <- difftime(Ttmp3T$d_770257102, Ttmp3T$d_914594314, units="mins")
summary(as.numeric(Ttmp3T$Mod3completionT))

data_ccc$Connect_ID[which.max(Ttmp3T$Mod3completionT)]
data_ccc$Connect_ID[which.min(Ttmp3T$Mod3completionT)]


# 4.	Duration from start to submitted for each module (active, passive and total)  
#d_770257102 completed
#d_386488297 start 

time.var.3 <- c("d_386488297","d_770257102")

##BEFORE
#All particiapnt totals, active total and passive total
sum(active_c_before$d_976570371==231311385, na.rm=TRUE)
sum(passive_c_before$d_976570371==231311385, na.rm=TRUE)
sum(data_ccc_before$d_976570371==231311385, na.rm=TRUE)


#Active
actm3= active_c_before %>% filter(active_c_before$d_976570371==231311385)
#actm3_time <- actm3[complete.cases(time.var.3)]
actm3_time<- actm3[complete.cases(actm3[ , time.var.3]), ]


tmp.3A <- actm3_time[,c("Connect_ID","d_386488297","d_770257102")]
tmp.3A$d_386488297 <- as.POSIXct(ymd_hms(tmp.3A$d_386488297))
tmp.3A$d_770257102 <- as.POSIXct(ymd_hms(tmp.3A$d_770257102))


tmp.3A$Mod3completionA <- difftime(tmp.3A$d_770257102, tmp.3A$d_386488297, units="mins")
summary(as.numeric(tmp.3A$Mod3completionA))

sum((1/3)>tmp.3A$Mod3completionA & tmp.3A$Mod3completionA>(1/6), na.rm=TRUE)/sum(active_c_before$d_976570371==231311385, na.rm=TRUE)
sum((1/2)>tmp.3A$Mod3completionA & tmp.3A$Mod3completionA>(1/3), na.rm=TRUE)/sum(active_c_before$d_976570371==231311385, na.rm=TRUE)
sum(tmp.3A$Mod3completionA>(2/3), na.rm=TRUE)/sum(active_c$d_976570371==231311385, na.rm=TRUE)

#Passive
pasm3= passive_c_before %>% filter(passive_c_before$d_976570371==231311385)
#pasm3_time <- pasm3[complete.cases(time.var.3)]
pasm3_time<- pasm3[complete.cases(pasm3[ , time.var.3]), ]


ptmp3 <- pasm3_time[,c("Connect_ID","d_386488297","d_770257102")]
ptmp3$d_386488297 <- as.POSIXct(ymd_hms(ptmp3$d_386488297))
ptmp3$d_770257102 <- as.POSIXct(ymd_hms(ptmp3$d_770257102))


ptmp3$Mod3completionP <- difftime(ptmp3$d_770257102, ptmp3$d_386488297, units="mins")
summary(as.numeric(ptmp3$Mod3completionP))

sum((1/3)>ptmp3$Mod3completionP & ptmp3$Mod3completionP>(1/6), na.rm=TRUE)/sum(passive_c_before$d_976570371==231311385, na.rm=TRUE)
sum((1/2)>ptmp3$Mod3completionP & ptmp3$Mod3completionP>(1/3), na.rm=TRUE)/sum(passive_c_before$d_976570371==231311385, na.rm=TRUE)
sum(ptmp3$Mod3completionP>(2/3), na.rm=TRUE)/sum(passive_c$d_976570371==231311385, na.rm=TRUE)

#Total
merm3= data_ccc_before %>% filter(data_ccc_before$d_976570371==231311385)
#merm3_time <- merm3[complete.cases(time.var.3)]
merm3_time<- merm3[complete.cases(merm3[ , time.var.3]), ]


Ttmp3 <- merm3_time[,c("Connect_ID","d_386488297","d_770257102")]
Ttmp3$d_386488297 <- as.POSIXct(ymd_hms(Ttmp3$d_386488297))
Ttmp3$d_770257102 <- as.POSIXct(ymd_hms(Ttmp3$d_770257102))


Ttmp3$Mod3completionT <- difftime(Ttmp3$d_770257102, Ttmp3$d_386488297, units="mins")
summary(as.numeric(Ttmp3$Mod3completionT))

sum((1/3)>Ttmp3$Mod3completionT & Ttmp3$Mod3completionT>(1/6), na.rm=TRUE)/sum(data_ccc_before$d_976570371==231311385, na.rm=TRUE)
sum((1/2)>Ttmp3$Mod3completionT & Ttmp3$Mod3completionT>(1/3), na.rm=TRUE)/sum(data_ccc_before$d_976570371==231311385, na.rm=TRUE)
sum(Ttmp3$Mod3completionT>(2/3), na.rm=TRUE)/sum(data_ccc$d_976570371==231311385, na.rm=TRUE)

#viewing streamlining participants and those taking an unusually long time to finish 
data_ccc$Connect_ID[which.max(Ttmp3$Mod3completionT)]
data_ccc$Connect_ID[which.min(Ttmp3$Mod3completionT)]


##AFTER
#All participant totals, active total and passive total
sum(active_c_after$d_976570371==231311385, na.rm=TRUE)
sum(passive_c_after$d_976570371==231311385, na.rm=TRUE)
sum(data_ccc_after$d_976570371==231311385, na.rm=TRUE)


#Active
actm3= active_c_after %>% filter(active_c_after$d_976570371==231311385)
#actm3_time <- actm3[complete.cases(time.var.3)]
actm3_time<- actm3[complete.cases(actm3[ , time.var.3]), ]


tmp.3A <- actm3_time[,c("Connect_ID","d_386488297","d_770257102")]
tmp.3A$d_386488297 <- as.POSIXct(ymd_hms(tmp.3A$d_386488297))
tmp.3A$d_770257102 <- as.POSIXct(ymd_hms(tmp.3A$d_770257102))


tmp.3A$Mod3completionA <- difftime(tmp.3A$d_770257102, tmp.3A$d_386488297, units="mins")
summary(as.numeric(tmp.3A$Mod3completionA))

sum((1/3)>tmp.3A$Mod3completionA & tmp.3A$Mod3completionA>(1/6), na.rm=TRUE)/sum(active_c_after$d_976570371==231311385, na.rm=TRUE)
sum((1/2)>tmp.3A$Mod3completionA & tmp.3A$Mod3completionA>(1/3), na.rm=TRUE)/sum(active_c_after$d_976570371==231311385, na.rm=TRUE)
sum(tmp.3A$Mod3completionA>(2/3), na.rm=TRUE)/sum(active_c$d_976570371==231311385, na.rm=TRUE)

#Passive
pasm3= passive_c_after %>% filter(passive_c_after$d_976570371==231311385)
#pasm3_time <- pasm3[complete.cases(time.var.3)]
pasm3_time<- pasm3[complete.cases(pasm3[ , time.var.3]), ]


ptmp3 <- pasm3_time[,c("Connect_ID","d_386488297","d_770257102")]
ptmp3$d_386488297 <- as.POSIXct(ymd_hms(ptmp3$d_386488297))
ptmp3$d_770257102 <- as.POSIXct(ymd_hms(ptmp3$d_770257102))


ptmp3$Mod3completionP <- difftime(ptmp3$d_770257102, ptmp3$d_386488297, units="mins")
summary(as.numeric(ptmp3$Mod3completionP))

sum((1/3)>ptmp3$Mod3completionP & ptmp3$Mod3completionP>(1/6), na.rm=TRUE)/sum(passive_c_after$d_976570371==231311385, na.rm=TRUE)
sum((1/2)>ptmp3$Mod3completionP & ptmp3$Mod3completionP>(1/3), na.rm=TRUE)/sum(passive_c_after$d_976570371==231311385, na.rm=TRUE)
sum(ptmp3$Mod3completionP>(2/3), na.rm=TRUE)/sum(passive_c$d_976570371==231311385, na.rm=TRUE)

#Total
merm3= data_ccc_after %>% filter(data_ccc_after$d_976570371==231311385)
#merm3_time <- merm3[complete.cases(time.var.3)]
merm3_time<- merm3[complete.cases(merm3[ , time.var.3]), ]


Ttmp3 <- merm3_time[,c("Connect_ID","d_386488297","d_770257102")]
Ttmp3$d_386488297 <- as.POSIXct(ymd_hms(Ttmp3$d_386488297))
Ttmp3$d_770257102 <- as.POSIXct(ymd_hms(Ttmp3$d_770257102))


Ttmp3$Mod3completionT <- difftime(Ttmp3$d_770257102, Ttmp3$d_386488297, units="mins")
summary(as.numeric(Ttmp3$Mod3completionT))

sum((1/3)>Ttmp3$Mod3completionT & Ttmp3$Mod3completionT>(1/6), na.rm=TRUE)/sum(data_ccc_after$d_976570371==231311385, na.rm=TRUE)
sum((1/2)>Ttmp3$Mod3completionT & Ttmp3$Mod3completionT>(1/3), na.rm=TRUE)/sum(data_ccc_after$d_976570371==231311385, na.rm=TRUE)
sum(Ttmp3$Mod3completionT>(2/3), na.rm=TRUE)/sum(data_ccc$d_976570371==231311385, na.rm=TRUE)



############### MODULE 4 ########################################


# 2.	Completion of baseline tasks with number and % not started, started, submitted of each module (active_c, passive_c and total)  

###BEFORE ALL MODULES AV'L
sum(active_c_before$d_663265240==972455046, na.rm=TRUE)
round((sum(active_c_before$d_663265240==972455046, na.rm=TRUE)/length(active_c_before$d_663265240))*100, digits=2) #not started
sum(active_c_before$d_663265240==615768760, na.rm=TRUE)
round((sum(active_c_before$d_663265240==615768760, na.rm=TRUE)/length(active_c_before$d_663265240))*100, digits=2)#started
sum(active_c_before$d_663265240==231311385, na.rm=TRUE)
round((sum(active_c_before$d_663265240==231311385, na.rm=TRUE)/length(active_c_before$d_663265240))*100, digits=2)#submitted

sum(passive_c_before$d_663265240==972455046, na.rm=TRUE)
round((sum(passive_c_before$d_663265240==972455046, na.rm=TRUE)/length(passive_c_before$d_663265240))*100, digits=2) #not started
sum(passive_c_before$d_663265240==615768760, na.rm=TRUE)
round((sum(passive_c_before$d_663265240==615768760, na.rm=TRUE)/length(passive_c_before$d_663265240))*100, digits=2)#started
sum(passive_c_before$d_663265240==231311385, na.rm=TRUE)
round((sum(passive_c_before$d_663265240==231311385, na.rm=TRUE)/length(passive_c_before$d_663265240))*100, digits=2)#submitted

sum(data_ccc_before$d_663265240==972455046, na.rm=TRUE)
round((sum(data_ccc_before$d_663265240==972455046, na.rm=TRUE)/length(data_ccc_before$d_663265240))*100, digits=2) #not started
sum(data_ccc_before$d_663265240==615768760, na.rm=TRUE)
round((sum(data_ccc_before$d_663265240==615768760, na.rm=TRUE)/length(data_ccc_before$d_663265240))*100, digits=2) #started
sum(data_ccc_before$d_663265240==231311385, na.rm=TRUE)
round((sum(data_ccc_before$d_663265240==231311385, na.rm=TRUE)/length(data_ccc_before$d_663265240))*100, digits=2) #submitted


### AFTER ALL MODULES AV'L 
sum(active_c_after$d_663265240==972455046, na.rm=TRUE)
round((sum(active_c_after$d_663265240==972455046, na.rm=TRUE)/length(active_c_after$d_663265240))*100, digits=2) #not started
sum(active_c_after$d_663265240==615768760, na.rm=TRUE)
round((sum(active_c_after$d_663265240==615768760, na.rm=TRUE)/length(active_c_after$d_663265240))*100, digits=2)#started
sum(active_c_after$d_663265240==231311385, na.rm=TRUE)
round((sum(active_c_after$d_663265240==231311385, na.rm=TRUE)/length(active_c_after$d_663265240))*100, digits=2)#submitted

sum(passive_c_after$d_663265240==972455046, na.rm=TRUE)
round((sum(passive_c_after$d_663265240==972455046, na.rm=TRUE)/length(passive_c_after$d_663265240))*100, digits=2) #not started
sum(passive_c_after$d_663265240==615768760, na.rm=TRUE)
round((sum(passive_c_after$d_663265240==615768760, na.rm=TRUE)/length(passive_c_after$d_663265240))*100, digits=2)#started
sum(passive_c_after$d_663265240==231311385, na.rm=TRUE)
round((sum(passive_c_after$d_663265240==231311385, na.rm=TRUE)/length(passive_c_after$d_663265240))*100, digits=2)#submitted

sum(data_ccc_after$d_663265240==972455046, na.rm=TRUE)
round((sum(data_ccc_after$d_663265240==972455046, na.rm=TRUE)/length(data_ccc_after$d_663265240))*100, digits=2) #not started
sum(data_ccc_after$d_663265240==615768760, na.rm=TRUE)
round((sum(data_ccc_after$d_663265240==615768760, na.rm=TRUE)/length(data_ccc_after$d_663265240))*100, digits=2) #started
sum(data_ccc_after$d_663265240==231311385, na.rm=TRUE)
round((sum(data_ccc_after$d_663265240==231311385, na.rm=TRUE)/length(data_ccc_after$d_663265240))*100, digits=2) #submitted


# 3.	Time from verification to completion of each module (active, passive and total)  
#264644252 completion

time.var4 <- c("d_914594314","d_264644252")

#All verified participant totals, verified active total and verified passive total
act4 <- active_c_after %>%   filter(d_663265240==231311385)
dim(act4)
pas4 <- passive_c_after  %>% filter(d_663265240==231311385)
dim(pas4)
mer4 <- data_ccc_after %>% filter(d_663265240==231311385)
dim(mer4)


#Active
#act4_time <- act4[complete.cases(time.var4)]
act4_time<- act4[complete.cases(act4[ , time.var4]), ]


tmp4A <- act4_time[,c("Connect_ID","d_914594314","d_264644252")]
tmp4A$d_914594314 <- as.POSIXct(ymd_hms(tmp4A$d_914594314))
tmp4A$d_264644252 <- as.POSIXct(ymd_hms(tmp4A$d_264644252))


tmp4A$Mod4completionA <- difftime(tmp4A$d_264644252, tmp4A$d_914594314, units="mins")
summary(as.numeric(tmp4A$Mod4completionA))

#Passive
#pas4_time <- pas4[complete.cases(time.var4)]
pas4_time<- pas4[complete.cases(pas4[ , time.var4]), ]

Ptmp4A <- pas4_time[,c("Connect_ID","d_914594314","d_264644252")]
Ptmp4A$d_914594314 <- as.POSIXct(ymd_hms(Ptmp4A$d_914594314))
Ptmp4A$d_264644252 <- as.POSIXct(ymd_hms(Ptmp4A$d_264644252))


Ptmp4A$Mod4completionP <- difftime(Ptmp4A$d_264644252, Ptmp4A$d_914594314, units="mins")
summary(as.numeric(Ptmp4A$Mod4completionP))

#Total
#mer4_time <- mer4[complete.cases(time.var4)]
mer4_time<- mer4[complete.cases(mer4[ , time.var4]), ]


Ttmp4 <- mer4_time[,c("Connect_ID","d_914594314","d_264644252")]
Ttmp4$d_914594314 <- as.POSIXct(ymd_hms(Ttmp4$d_914594314))
Ttmp4$d_264644252 <- as.POSIXct(ymd_hms(Ttmp4$d_264644252))


Ttmp4$Mod4completionT <- difftime(Ttmp4$d_264644252, Ttmp4$d_914594314, units="mins")
summary(as.numeric(Ttmp4$Mod4completionT))


# 4.	Duration from start to submitted for each module (active, passive and total) 
#264644252 completion
#452942800 start 
time.var.4 <- c("d_452942800","d_264644252")


##BEFORE
#All participant totals, active total and passive total
sum(active_c_before$d_663265240==231311385, na.rm=TRUE)
sum(passive_c_before$d_663265240==231311385, na.rm=TRUE)
sum(data_ccc_before$d_663265240==231311385, na.rm=TRUE)

#Active
actm4= active_c_before %>% filter(active_c_before$d_663265240==231311385)
#actm4_time <- actm4[complete.cases(time.var.4)]
actm4_time<- actm4[complete.cases(actm4[ , time.var.4]), ]


tmp.4 <- actm4_time[,c("Connect_ID","d_452942800","d_264644252")]
tmp.4$d_452942800 <- as.POSIXct(ymd_hms(tmp.4$d_452942800))
tmp.4$d_264644252 <- as.POSIXct(ymd_hms(tmp.4$d_264644252))


tmp.4$Mod4completionA <- difftime(tmp.4$d_264644252, tmp.4$d_452942800, units="mins")
summary(as.numeric(tmp.4$Mod4completionA))


sum((1/3)>tmp.4$Mod4completionA & tmp.4$Mod4completionA>(1/6), na.rm=TRUE)/sum(active_c_before$d_663265240==231311385, na.rm=TRUE)
sum((1/2)>tmp.4$Mod4completionA & tmp.4$Mod4completionA>(1/3), na.rm=TRUE)/sum(active_c_before$d_663265240==231311385, na.rm=TRUE)
sum(tmp.4$Mod4completionA>(2/3), na.rm=TRUE)/sum(active_c$d_663265240==231311385, na.rm=TRUE)


#Passive
pasm4= passive_c_before %>% filter(passive_c_before$d_663265240==231311385)
#pasm4_time <- pasm4[complete.cases(time.var.4)]
pasm4_time<- pasm4[complete.cases(pasm4[ , time.var.4]), ]


ptmp4 <- pasm4_time[,c("Connect_ID","d_452942800","d_264644252")]
ptmp4$d_452942800 <- as.POSIXct(ymd_hms(ptmp4$d_452942800))
ptmp4$d_264644252 <- as.POSIXct(ymd_hms(ptmp4$d_264644252))


ptmp4$Mod4completionP <- difftime(ptmp4$d_264644252, ptmp4$d_452942800, units="mins")
summary(as.numeric(ptmp4$Mod4completionP))

sum((1/3)>ptmp4$Mod4completionP & ptmp4$Mod4completionP>(1/6), na.rm=TRUE)/sum(passive_c_before$d_663265240==231311385, na.rm=TRUE)
sum((1/2)>ptmp4$Mod4completionP & ptmp4$Mod4completionP>(1/3), na.rm=TRUE)/sum(passive_c_before$d_663265240==231311385, na.rm=TRUE)
sum(ptmp4$Mod4completionP>(2/3), na.rm=TRUE)/sum(passive_c$d_663265240==231311385, na.rm=TRUE)

#Total
merm4= data_ccc_before %>% filter(data_ccc_before$d_663265240==231311385)
#merm4_time <- merm4[complete.cases(time.var.4)]
merm4_time<- merm4[complete.cases(merm4[ , time.var.4]), ]


Ttmp.4 <- merm4_time[,c("Connect_ID","d_452942800","d_264644252")]
Ttmp.4$d_452942800 <- as.POSIXct(ymd_hms(Ttmp.4$d_452942800))
Ttmp.4$d_264644252 <- as.POSIXct(ymd_hms(Ttmp.4$d_264644252))


Ttmp.4$Mod4completionT <- difftime(Ttmp.4$d_264644252, Ttmp.4$d_452942800, units="mins")
summary(as.numeric(Ttmp.4$Mod4completionT))

sum((1/3)>Ttmp.4$Mod4completionT & Ttmp.4$Mod4completionT>(1/6), na.rm=TRUE)/sum(data_ccc_before$d_663265240==231311385, na.rm=TRUE)
sum((1/2)>Ttmp.4$Mod4completionT & Ttmp.4$Mod4completionT>(1/3), na.rm=TRUE)/sum(data_ccc_before$d_663265240==231311385, na.rm=TRUE)
sum(Ttmp.4$Mod4completionT>(2/3), na.rm=TRUE)/sum(data_ccc$d_663265240==231311385, na.rm=TRUE)

data_ccc$Connect_ID[which.max(Ttmp.4$Mod4completionT)]
data_ccc$Connect_ID[which.min(Ttmp.4$Mod4completionT)]


##AFTER
#All participant totals, active total and passive total
sum(active_c_after$d_663265240==231311385, na.rm=TRUE)
sum(passive_c_after$d_663265240==231311385, na.rm=TRUE)
sum(data_ccc_after$d_663265240==231311385, na.rm=TRUE)

#Active
actm4= active_c_after %>% filter(active_c_after$d_663265240==231311385)
#actm4_time <- actm4[complete.cases(time.var.4)]
actm4_time<- actm4[complete.cases(actm4[ , time.var.4]), ]


tmp.4 <- actm4_time[,c("Connect_ID","d_452942800","d_264644252")]
tmp.4$d_452942800 <- as.POSIXct(ymd_hms(tmp.4$d_452942800))
tmp.4$d_264644252 <- as.POSIXct(ymd_hms(tmp.4$d_264644252))


tmp.4$Mod4completionA <- difftime(tmp.4$d_264644252, tmp.4$d_452942800, units="mins")
summary(as.numeric(tmp.4$Mod4completionA))


sum((1/3)>tmp.4$Mod4completionA & tmp.4$Mod4completionA>(1/6), na.rm=TRUE)/sum(active_c_after$d_663265240==231311385, na.rm=TRUE)
sum((1/2)>tmp.4$Mod4completionA & tmp.4$Mod4completionA>(1/3), na.rm=TRUE)/sum(active_c_after$d_663265240==231311385, na.rm=TRUE)
sum(tmp.4$Mod4completionA>(2/3), na.rm=TRUE)/sum(active_c$d_663265240==231311385, na.rm=TRUE)


#Passive
pasm4= passive_c_after %>% filter(passive_c_after$d_663265240==231311385)
#pasm4_time <- pasm4[complete.cases(time.var.4)]
pasm4_time<- pasm4[complete.cases(pasm4[ , time.var.4]), ]


ptmp4 <- pasm4_time[,c("Connect_ID","d_452942800","d_264644252")]
ptmp4$d_452942800 <- as.POSIXct(ymd_hms(ptmp4$d_452942800))
ptmp4$d_264644252 <- as.POSIXct(ymd_hms(ptmp4$d_264644252))


ptmp4$Mod4completionP <- difftime(ptmp4$d_264644252, ptmp4$d_452942800, units="mins")
summary(as.numeric(ptmp4$Mod4completionP))

sum((1/3)>ptmp4$Mod4completionP & ptmp4$Mod4completionP>(1/6), na.rm=TRUE)/sum(passive_c_after$d_663265240==231311385, na.rm=TRUE)
sum((1/2)>ptmp4$Mod4completionP & ptmp4$Mod4completionP>(1/3), na.rm=TRUE)/sum(passive_c_after$d_663265240==231311385, na.rm=TRUE)
sum(ptmp4$Mod4completionP>(2/3), na.rm=TRUE)/sum(passive_c$d_663265240==231311385, na.rm=TRUE)

#Total
merm4= data_ccc_after %>% filter(data_ccc_after$d_663265240==231311385)
#merm4_time <- merm4[complete.cases(time.var.4)]
merm4_time<- merm4[complete.cases(merm4[ , time.var.4]), ]


Ttmp.4 <- merm4_time[,c("Connect_ID","d_452942800","d_264644252")]
Ttmp.4$d_452942800 <- as.POSIXct(ymd_hms(Ttmp.4$d_452942800))
Ttmp.4$d_264644252 <- as.POSIXct(ymd_hms(Ttmp.4$d_264644252))


Ttmp.4$Mod4completionT <- difftime(Ttmp.4$d_264644252, Ttmp.4$d_452942800, units="mins")
summary(as.numeric(Ttmp.4$Mod4completionT))

sum((1/3)>Ttmp.4$Mod4completionT & Ttmp.4$Mod4completionT>(1/6), na.rm=TRUE)/sum(data_ccc_after$d_663265240==231311385, na.rm=TRUE)
sum((1/2)>Ttmp.4$Mod4completionT & Ttmp.4$Mod4completionT>(1/3), na.rm=TRUE)/sum(data_ccc_after$d_663265240==231311385, na.rm=TRUE)
sum(Ttmp.4$Mod4completionT>(2/3), na.rm=TRUE)/sum(data_ccc$d_663265240==231311385, na.rm=TRUE)




#######################################################################################################
##### ALL MODULES #####  
dim(data_ccc)


# 5.	% Submission of surveys modules by active recruits who cannot be verified   
#d_512820379==486306141 <-- active

cannot_verify <- data_c %>% filter(d_821247024==219863910& d_512820379==486306141) #active
dim(cannot_verify)

cannot_verify_all <- data_c %>% filter(d_821247024==219863910) #all
dim(cannot_verify_all)
#Only 1 active_c participant that cannot be verified

#>No survey modules submitted
active_c_NV_NS <- data_c %>% filter(d_821247024==219863910 & d_512820379==486306141 & (d_949302066==972455046 | d_949302066==615768760) & (d_536735468==972455046 | d_536735468==615768760) &
                                      (d_976570371==972455046 | d_976570371==615768760) & (d_663265240==972455046| d_663265240==615768760))
dim(active_c_NV_NS)

#>Any survey modules submitted
active_c_NV_SB <- data_c %>% filter(d_821247024==219863910 & d_512820379==486306141 & (d_949302066==231311385 | d_536735468==231311385 | d_976570371==231311385 | d_663265240==231311385))
dim(active_c_NV_SB)




#6.	Time from start of Module 1 to completion of most recent module (in hours) to get overall averages --- review this code! Might have swapped all mod1 completions status with Mod 4, and Mod3 with Mod1

time.var.1_1 <- c("d_205553981","d_832139544")
mer1_1= data_ccc_after %>% filter(data_ccc_after$d_663265240==231311385)
#mer1_2_time <- mer1_2[complete.cases(time.var.1_2)]
mer1_1_time<- mer1_1[complete.cases(mer1_1[ , time.var.1_1]), ]


Ttmp1_1 <- mer1_1_time[,c("Connect_ID","d_205553981","d_832139544")]
Ttmp1_1$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1_1$d_205553981))
Ttmp1_1$d_832139544 <- as.POSIXct(ymd_hms(Ttmp1_1$d_832139544))


Ttmp1_1$Mod2completionT <- difftime(Ttmp1_1$d_832139544, Ttmp1_1$d_205553981, units="mins")
summary(as.numeric(Ttmp1_1$Mod2completionT))


#mod 1 and 2
time.var.1_2 <- c("d_205553981","d_832139544")
mer1_2= data_ccc_after %>% filter(data_ccc_after$d_536735468==231311385 & data_ccc_after$d_663265240!=231311385 & data_ccc_after$d_663265240!=231311385)
#mer1_2_time <- mer1_2[complete.cases(time.var.1_2)]
mer1_2_time<- mer1_2[complete.cases(mer1_2[ , time.var.1_2]), ]


Ttmp1_2 <- mer1_2_time[,c("Connect_ID","d_205553981","d_832139544")]
Ttmp1_2$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1_2$d_205553981))
Ttmp1_2$d_832139544 <- as.POSIXct(ymd_hms(Ttmp1_2$d_832139544))


Ttmp1_2$Mod2completionT <- difftime(Ttmp1_2$d_832139544, Ttmp1_2$d_205553981, units="mins")
summary(as.numeric(Ttmp1_2$Mod2completionT))



#mod 1 & 3
time.var.1_3 <- c("d_205553981","d_770257102")
merm1_3= data_ccc_after %>% filter(data_ccc_after$d_536735468!=231311385 & data_ccc_after$d_663265240==231311385 & data_ccc_after$d_663265240!=231311385)
#merm1_3_time <- merm1_3[complete.cases(time.var.1_3)]
merm1_3_time<- merm1_3[complete.cases(merm1_3[ , time.var.1_3]), ]


Ttmp1_3 <- merm1_3_time[,c("Connect_ID","d_205553981","d_770257102")]
Ttmp1_3$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1_3$d_205553981))
Ttmp1_3$d_770257102 <- as.POSIXct(ymd_hms(Ttmp1_3$d_770257102))


Ttmp1_3$Mod1_3completionT <- difftime(Ttmp1_3$d_770257102, Ttmp1_3$d_205553981, units="mins")
summary(as.numeric(Ttmp1_3$Mod1_3completionT))

#mod 1 & 4
time.var.1_4 <- c("d_205553981","d_264644252")
merm1_4= data_ccc_after %>% filter(data_ccc_after$d_536735468!=231311385 & data_ccc_after$d_663265240!=231311385 & data_ccc_after$d_663265240==231311385)
#merm1_4_time <- merm1_4[complete.cases(time.var.1_4)]
merm1_4_time<- merm1_4[complete.cases(merm1_4[ , time.var.1_4]), ]


Ttmp.1_4 <- merm1_4_time[,c("Connect_ID","d_205553981","d_264644252")]
Ttmp.1_4$d_205553981 <- as.POSIXct(ymd_hms(Ttmp.1_4$d_205553981))
Ttmp.1_4$d_264644252 <- as.POSIXct(ymd_hms(Ttmp.1_4$d_264644252))


Ttmp.1_4$Mod1_4completionT <- difftime(Ttmp.1_4$d_264644252, Ttmp.1_4$d_205553981, units="mins")
summary(as.numeric(Ttmp.1_4$Mod1_4completionT))


#mod 1, 2 & 3   
time.var.1_2_3 <- c("d_205553981","d_770257102")
merm1_2_3= data_ccc_after %>% filter(data_ccc_after$d_536735468==231311385 & data_ccc_after$d_663265240==231311385 & data_ccc_after$d_663265240!=231311385 & d_832139544 < d_770257102)
#merm1_2_3_time <- merm1_2_3[complete.cases(time.var.1_2_3)]
merm1_2_3_time<- merm1_2_3[complete.cases(merm1_2_3[ , time.var.1_2_3]), ]


Ttmp1_2_3 <- merm1_2_3_time[,c("Connect_ID","d_205553981","d_770257102")]
Ttmp1_2_3$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1_2_3$d_205553981))
Ttmp1_2_3$d_770257102 <- as.POSIXct(ymd_hms(Ttmp1_2_3$d_770257102))


Ttmp1_2_3$Mod1_2_3completionT <- difftime(Ttmp1_2_3$d_770257102, Ttmp1_2_3$d_205553981, units="mins")
summary(as.numeric(Ttmp1_2_3$Mod1_2_3completionT))

#mod 1, 3 & 2 (answering mod 3 before mod2)   
time.var.1_3_2 <- c("d_205553981","d_832139544")
merm1_3_2= data_ccc_after %>% filter(data_ccc_after$d_536735468==231311385 & data_ccc_after$d_663265240==231311385 & data_ccc_after$d_663265240!=231311385 & d_770257102 < d_832139544)
#merm1_3_2_time <- merm1_3_2[complete.cases(time.var.1_3_2)]
merm1_3_2_time<- merm1_3_2[complete.cases(merm1_3_2[ , time.var.1_3_2]), ]


Ttmp1_3_2 <- merm1_3_2_time[,c("Connect_ID","d_205553981","d_832139544")]
Ttmp1_3_2$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1_3_2$d_205553981))
Ttmp1_3_2$d_832139544 <- as.POSIXct(ymd_hms(Ttmp1_3_2$d_832139544))


Ttmp1_3_2$Mod1_3_2completionT <- difftime(Ttmp1_3_2$d_832139544, Ttmp1_3_2$d_205553981, units="mins")
summary(as.numeric(Ttmp1_3_2$Mod1_3_2completionT))


#mod 1, 2 & 4   
time.var.1_2_4 <- c("d_205553981","d_264644252")
merm1_2_4= data_ccc_after %>% filter(data_ccc_after$d_536735468==231311385 & data_ccc_after$d_663265240!=231311385 & data_ccc_after$d_663265240==231311385 & d_832139544 < d_264644252)
#merm1_2_4_time <- merm1_2_4[complete.cases(time.var.1_2_4)]
merm1_2_4_time<- merm1_2_4[complete.cases(merm1_2_4[ , time.var.1_2_4]), ]


Ttmp1_2_4 <- merm1_2_4_time[,c("Connect_ID","d_205553981","d_264644252")]
Ttmp1_2_4$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1_2_4$d_205553981))
Ttmp1_2_4$d_264644252 <- as.POSIXct(ymd_hms(Ttmp1_2_4$d_264644252))


Ttmp1_2_4$Mod1_2_4completionT <- difftime(Ttmp1_2_4$d_264644252, Ttmp1_2_4$d_205553981, units="mins")
summary(as.numeric(Ttmp1_2_4$Mod1_2_4completionT))

#mod 1, 4 & 2 (answering 2 before four )   
time.var.1_4_2 <- c("d_205553981","d_832139544")
merm1_4_2= data_ccc_after %>% filter(data_ccc_after$d_536735468==231311385 & data_ccc_after$d_663265240!=231311385 & data_ccc_after$d_663265240==231311385 & d_264644252 < d_832139544)
#merm1_4_2_time <- merm1_4_2[complete.cases(time.var.1_4_2)]
merm1_4_2_time<- merm1_4_2[complete.cases(merm1_4_2[ , time.var.1_4_2]), ]


Ttmp1_4_2 <- merm1_4_2_time[,c("Connect_ID","d_205553981","d_832139544")]
Ttmp1_4_2$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1_4_2$d_205553981))
Ttmp1_4_2$d_832139544 <- as.POSIXct(ymd_hms(Ttmp1_4_2$d_832139544))


Ttmp1_4_2$Mod1_4_2completionT <- difftime(Ttmp1_4_2$d_832139544, Ttmp1_4_2$d_205553981, units="mins")
summary(as.numeric(Ttmp1_4_2$Mod1_4_2completionT))

#mod 1, 3 & 4 
time.var.1_3_4 <- c("d_205553981","d_264644252")
merm1_3_4= data_ccc_after %>% filter(data_ccc_after$d_536735468!=231311385 & data_ccc_after$d_663265240==231311385 & data_ccc_after$d_663265240==231311385 & d_770257102 < d_264644252)
#merm1_3_4_time <- merm1_3_4[complete.cases(time.var.1_3_4)]
merm1_3_4_time<- merm1_3_4[complete.cases(merm1_3_4[ , time.var.1_3_4]), ]


Ttmp1_3_4 <- merm1_3_4_time[,c("Connect_ID","d_205553981","d_264644252")]
Ttmp1_3_4$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1_3_4$d_205553981))
Ttmp1_3_4$d_264644252 <- as.POSIXct(ymd_hms(Ttmp1_3_4$d_264644252))


Ttmp1_3_4$Mod1_3_4completionT <- difftime(Ttmp1_3_4$d_264644252, Ttmp1_3_4$d_205553981, units="mins")
summary(as.numeric(Ttmp1_3_4$Mod1_3_4completionT))

#mod 1, 4 & 3 
time.var.1_4_3 <- c("d_205553981","d_770257102")
merm1_4_3= data_ccc_after %>% filter(data_ccc_after$d_536735468!=231311385 & data_ccc_after$d_663265240==231311385 & data_ccc_after$d_663265240==231311385 & d_264644252 < d_770257102)
#merm1_4_3_time <- merm1_4_3[complete.cases(time.var.1_4_3)]
merm1_4_3_time<- merm1_4_3[complete.cases(merm1_4_3[ , time.var.1_4_3]), ]


Ttmp1_4_3 <- merm1_4_3_time[,c("Connect_ID","d_205553981","d_770257102")]
Ttmp1_4_3$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1_4_3$d_205553981))
Ttmp1_4_3$d_7702571022 <- as.POSIXct(ymd_hms(Ttmp1_4_3$d_770257102))


Ttmp1_4_3$Mod1_4_3completionT <- difftime(Ttmp1_4_3$d_770257102, Ttmp1_4_3$d_205553981, units="mins")
summary(as.numeric(Ttmp1_4_3$Mod1_4_3completionT))


#mod 1, 2, 3 & 4   ----- assuming in order
time.var.1_2_3_4 <- c("d_205553981","d_264644252")
merm1_2_3_4= data_ccc_after %>% filter(data_ccc_after$d_536735468==231311385 & data_ccc_after$d_663265240==231311385 & data_ccc_after$d_663265240==231311385 & 
                                   d_517311251 < d_832139544 & d_832139544 < d_770257102 & d_770257102 < d_264644252)
#merm1_2_3_4_time <- merm1_2_3_4[complete.cases(time.var.1_2_3_4)]
merm1_2_3_4_time<- merm1_2_3_4[complete.cases(merm1_2_3_4[ , time.var.1_2_3_4]), ]


Ttmp1_2_3_4 <- merm1_2_3_4_time[,c("Connect_ID","d_205553981","d_264644252")]
Ttmp1_2_3_4$d_205553981 <- as.POSIXct(ymd_hms(Ttmp1_2_3_4$d_205553981))
Ttmp1_2_3_4$d_264644252 <- as.POSIXct(ymd_hms(Ttmp1_2_3_4$d_264644252))


Ttmp1_2_3_4$Mod1_2_3_4completionT <- difftime(Ttmp1_2_3_4$d_264644252, Ttmp1_2_3_4$d_205553981, units="mins")
summary(as.numeric(Ttmp1_2_3_4$Mod1_2_3_4completionT))


#####################################################################################


#7. Survey completion flag and survey completion time stamp 

#M1
sum(data_ccc$d_949302066==231311385)
sum(!is.na(data_ccc$d_205553981))
sum(!is.na(data_ccc$d_517311251))

#M2
sum(data_ccc$d_536735468==231311385)
sum(!is.na(data_ccc$d_541836531))
sum(!is.na(data_ccc$d_832139544))

#M3
sum(data_ccc$d_976570371==231311385)
sum(!is.na(data_ccc$d_386488297))
sum(!is.na(data_ccc$d_770257102))

#M4
sum(data_ccc$d_663265240==231311385)
sum(!is.na(data_ccc$d_452942800))
sum(!is.na(data_ccc$d_264644252))

#Bio
sum(data_ccc$d_265193023==231311385)
sum(!is.na(data_ccc$d_822499427))
sum(!is.na(data_ccc$d_222161762))


#8. Connect_IDs of those who completed the menstrual cycle survey---need to convert to SQL code since d_459098666 and D_299215535.D_112151599 are in participants table and aren't flattened

mens_ccc <- "SELECT Connect_ID,  d_265193023,  d_459098666
 FROM `nih-nci-dceg-connect-prod-6d04.Connect.participants` 
 where D_299215535.D_112151599='353358909' and
 d_265193023=231311385 "

mens_table_cc <- bq_project_query(project_cc, mens_ccc)
mens_data_ccc <- bq_table_download(mens_table_cc, bigint = "integer64")

menstrual <- mens_data_ccc
dim(menstrual)

mens_complete <- mens_data_ccc  %>%  filter(d_459098666==231311385 )
dim(mens_complete)
mens_complete

dim(mens_complete)[[1]]/dim(menstrual)[[1]]

mens_complete$Connect_ID





```
