---
title: "Module 2 Custom QC Rules"
author: "Kelsey Sanchez"
date: "`r Sys.Date()`"
output: pdf_document
---



```{r libraries, include=FALSE}
#rm(list = ls())


#update.packages("tinytex")
#require(devtools)
#install_version("ggplot2", version = "0.9.1", repos = "http://cran.us.r-project.org")
#tinytex::install_tinytex(version = "2020.10")
#tinytex::reinstall_tinytex(repository = "illinois")



library(bigrquery)
library(foreach)
library(stringr)
#library(plyr)
#library(expss) ###to add labels
library(epiDisplay) ##recommended applied here crosstable, tab1
library(gmodels) ##recommended
library(magrittr)
library(arsenal)
library(gtsummary)
library(rio)



library(ggplot2)
library(gridExtra)
library(scales)
library(gt)
#install(tinytex)
library(tinytex)
library(data.table) ###to write or read and data management 
library(tidyverse) ###for data management
library(dplyr) ###data management
library(reshape)  ###to work on transition from long to wide or wide to long data
library(listr) ###to work on a list of vector, files or..
library(sqldf) ##sql
library(lubridate) ###date time
library(stringr) ###to work on patterns, characters

options(tinytex.verbose = TRUE)

bq_auth()
```



```{r merge1, include=FALSE, warning=FALSE}


#Data Dictionary for column names
dictionary <- rio::import("https://episphere.github.io/conceptGithubActions/aggregate.json",format = "json")
dd <- dplyr::bind_rows(dictionary,.id="CID")
dd <-rbindlist(dictionary,fill=TRUE,use.names=TRUE,idcol="CID")
dd$`Variable Label`[is.na(dd$`Variable Label`)] <- replace_na(dd$'Variable Name')
dd <- as.data.frame.matrix(do.call("rbind",dictionary)) 
dd$CID <- rownames(dd)
#https://shaivyakodan.medium.com/7-useful-r-packages-for-analysis-7f60d28dca98
devtools::install_github("tidyverse/reprex")





## BQ Pull from the participants table just to use for versioning
project <- "nih-nci-dceg-connect-prod-6d04"
billing <- "nih-nci-dceg-connect-prod-6d04" 
recr_M1 <- bq_project_query(project, query="SELECT token,Connect_ID, d_821247024, d_914594314,  d_827220437,d_512820379,
                            d_949302066 , d_517311251  FROM  `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` WHERE  d_821247024='197316935' and d_949302066 ='231311385'")
recr_m1 <- bq_table_download(recr_M1,bigint = "integer64")
cnames <- names(recr_m1)
# Check that it doesn't match any non-number
numbers_only <- function(x) !grepl("\\D", x)
# to check variables in recr_noinact_wl1
for (i in 1: length(cnames)){
  varname <- cnames[i]
  var<-pull(recr_m1,varname)
  recr_m1[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
}




#### Handling participants that somehow completed both Mod1 version 1 and Mod1 version 2

sql_M1_1 <- bq_project_query(project, query = "SELECT Connect_ID, D_407056417, D_750420077_D_108025529, D_750420077_D_434651539, D_750420077_D_505282171, D_750420077_D_578416151, D_750420077_D_846483618, D_289664241_D_289664241, D_613744428 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.module1_v1_JP` WHERE Connect_ID IS NOT NULL")
sql_M1_2 <- bq_project_query(project, query = "SELECT Connect_ID, D_407056417, D_750420077_D_108025529, D_750420077_D_434651539, D_750420077_D_505282171, D_750420077_D_578416151, D_750420077_D_582784267, D_750420077_D_700100953, D_750420077_D_751402477, D_750420077_D_846483618, D_289664241_D_918409306, D_613744428 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.module1_v2_JP` WHERE Connect_ID IS NOT NULL")

M1_V1 <- bq_table_download(sql_M1_1, bigint = "integer64")
M1_V2 <- bq_table_download(sql_M1_2, bigint = "integer64")

# Select matching column names
M1_V1_vars <- colnames(M1_V1)
M1_V2_vars <- colnames(M1_V2)
common_vars <- intersect(M1_V1_vars, M1_V2_vars)

# Subset to common columns
M1_V1_common <- M1_V1[, common_vars]
M1_V2_common <- M1_V2[, common_vars]

# Add version indicator
M1_V1_common$version <- 1
M1_V2_common$version <- 2

# Identify columns with mismatched types
mismatched_cols <- names(M1_V1_common)[sapply(names(M1_V1_common), function(col) {
  class(M1_V1_common[[col]]) != class(M1_V2_common[[col]])
})]

# Convert mismatched columns to character for consistency
M1_V1_common <- M1_V1_common %>%
  mutate(across(all_of(mismatched_cols), as.character))
M1_V2_common <- M1_V2_common %>%
  mutate(across(all_of(mismatched_cols), as.character))

# Combine both versions for participants who completed both
M1_common <- bind_rows(M1_V1_common, M1_V2_common) %>%
  arrange(Connect_ID, desc(version))

# For columns unique to each version
V1_only_vars <- setdiff(M1_V1_vars, common_vars)
V2_only_vars <- setdiff(M1_V2_vars, common_vars)

# Subset each version for unique columns and add version indicator
m1_v1_only <- M1_V1[, c("Connect_ID", V1_only_vars)] %>%
  mutate(version = 1)
m1_v2_only <- M1_V2[, c("Connect_ID", V2_only_vars)] %>%
  mutate(version = 2)

# Combine the unique and common data
m1_common_v1 <- left_join(M1_common, m1_v1_only, by = c("Connect_ID", "version"))
m1_combined_v1v2 <- left_join(m1_common_v1, m1_v2_only, by = c("Connect_ID", "version"))

# Filter for complete cases where specific completion criteria are met
m1_complete <- m1_combined_v1v2 %>%
  filter(Connect_ID %in% recr_m1$Connect_ID[recr_m1$d_949302066 == 231311385]) %>%
  arrange(desc(version))

# Remove duplicates, keeping only the most recent version for each Connect_ID
m1_complete_nodup <- m1_complete[!duplicated(m1_complete$Connect_ID),]

m1_complete_nodup$Connect_ID <- as.numeric(m1_complete_nodup$Connect_ID)


## Define requirements of the data: active or passive,  user profile done, consented, mod1 done, verified
parts <- "SELECT Connect_ID, token, state_d_934298480, d_536735468, d_663265240,d_976570371, d_949302066, d_832139544
FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` 
where Connect_ID IS NOT NULL and (d_512820379='486306141' OR d_512820379='854703046') and d_919254129='353358909' and d_699625233='353358909' and 
d_536735468 = '231311385'  and d_821247024='197316935'" 

parts_table <- bq_project_query(project, parts)
parts_data <- bq_table_download(parts_table, bigint = "integer64",n_max = Inf, page_size = 10000)

parts_data$Connect_ID <- as.numeric(parts_data$Connect_ID)


merged= left_join(parts_data,m1_complete_nodup, by="Connect_ID") #%>% 
dim(merged)


data_tib_base <- as_tibble(merged)

knitr::opts_chunk$set(comment = NA)

```





```{r merge2, include=FALSE}

recr_m2 <- bq_project_query(project, query="SELECT token,Connect_ID, d_821247024, d_914594314,  d_827220437,d_512820379, 
                            d_536735468 , d_517311251  FROM  `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` WHERE  d_821247024='197316935'")
recr_m2 <- bq_table_download(recr_m2,bigint = "integer64",n_max = Inf, page_size = 10000)
cnames <- names(recr_m2)
# Check that it doesn't match any non-number
numbers_only <- function(x) !grepl("\\D", x)
# to check variables in recr_noinact_wl1
for (i in 1: length(cnames)){
  varname <- cnames[i]
  var<-pull(recr_m2,varname)
  recr_m2[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
}



### Deal with Mod2 duplicates (took both version 1 and vesion 2, and only select version 2 data)
sql_M2_1 <- bq_project_query(project, query = "SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.module2_v1_JP` WHERE Connect_ID IS NOT NULL")
sql_M2_2 <- bq_project_query(project, query = "SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.module2_v2_JP` WHERE Connect_ID IS NOT NULL")

M2_V1 <- bq_table_download(sql_M2_1, bigint = "integer64")
M2_V2 <- bq_table_download(sql_M2_2, bigint = "integer64")

# Select matching column names
M2_V1_vars <- colnames(M2_V1)
M2_V2_vars <- colnames(M2_V2)
common_vars <- intersect(M2_V1_vars, M2_V2_vars)

# Subset to common columns
M2_V1_common <- M2_V1[, common_vars]
M2_V2_common <- M2_V2[, common_vars]

# Add version indicator
M2_V1_common$version <- 1
M2_V2_common$version <- 2

# Identify columns with mismatched types
mismatched_cols <- names(M2_V1_common)[sapply(names(M2_V1_common), function(col) {
  class(M2_V1_common[[col]]) != class(M2_V2_common[[col]])
})]

# Convert mismatched columns to character for consistency
M2_V1_common <- M2_V1_common %>%
  mutate(across(all_of(mismatched_cols), as.character))
M2_V2_common <- M2_V2_common %>%
  mutate(across(all_of(mismatched_cols), as.character))

# Combine both versions for participants who completed both
M2_common <- bind_rows(M2_V1_common, M2_V2_common) %>%
  arrange(Connect_ID, desc(version))

# For columns unique to each version
V1_only_vars <- setdiff(M2_V1_vars, common_vars)
V2_only_vars <- setdiff(M2_V2_vars, common_vars)

# Subset each version for unique columns and add version indicator
m2_v1_only <- M2_V1[, c("Connect_ID", V1_only_vars)] %>%
  mutate(version = 1)
m2_v2_only <- M2_V2[, c("Connect_ID", V2_only_vars)] %>%
  mutate(version = 2)

# Combine the unique and common data
M2_common_v1 <- left_join(M2_common, m2_v1_only, by = c("Connect_ID", "version"))
M2_combined_v1v2 <- left_join(M2_common_v1, m2_v2_only, by = c("Connect_ID", "version"))

# Filter for complete cases where specific completion criteria are met
M2_complete <- M2_combined_v1v2 %>%
  filter(Connect_ID %in% recr_m2$Connect_ID[recr_m2$d_536735468 == 231311385]) %>%
  arrange(desc(version))

# Remove duplicates, keeping only the most recent version for each Connect_ID
M2_complete_nodup <- M2_complete[!duplicated(M2_complete$Connect_ID),]
table(M2_complete_nodup$version)


M2_complete_nodup$Connect_ID <- as.numeric(M2_complete_nodup$Connect_ID)


module2= left_join(merged, M2_complete_nodup, by="Connect_ID")


data_tib_m2 <- as_tibble(module2)


data_tib_m2$d_832139544 <- as.Date(data_tib_m2$d_832139544)

```



## If MENSHISA is less than 0 or null, MENSHIS2_1 must be null.
```{r, warning=FALSE, echo=FALSE,  message=FALSE}

error1 <- data_tib_m2 %>%  filter((as.numeric(D_496539718_D_969451837)<0  | is.na(D_496539718_D_969451837)) & 
                                    !is.na(D_167997205)) %>% 
  select(Connect_ID, D_496539718_D_969451837, D_167997205, d_832139544) %>% 
  arrange(desc(d_832139544))

colnames(error1) <- c("Connect ID", "MENSHISA", "MENSHIS2_1", "Date_M2_Completed")
if (nrow(error1) == 0) {
  cat("No errors")
} else {
  knitr::kable(error1)
}

```


## If MENSHISA is less than 0 or null, MENSHIS5 must be null.
```{r, warning=FALSE, echo=FALSE,  message=FALSE}

error2 <- data_tib_m2 %>%  filter((as.numeric(D_496539718_D_969451837)<0  | is.na(D_496539718_D_969451837)) & 
                                    !is.na(D_164595895)) %>% 
  select(Connect_ID, D_496539718_D_969451837, D_164595895, d_832139544)%>% 
  arrange(desc(d_832139544))

colnames(error2) <- c("Connect ID", "MENSHISA", "MENSHIS5", "Date_M2_Completed")
if (nrow(error2) == 0) {
  cat("No errors")
} else {
  knitr::kable(error2)
}

```


## If TESTTHER2 = "Slow release implant (testosterone pellets)" ONLY (no other response selected), then TESTTHER4 must be null.
```{r, warning=FALSE, echo=FALSE,  message=FALSE}

error3 <- data_tib_m2 %>%  filter(D_946849196_D_108104748==0 & D_946849196_D_158214723==0 & D_946849196_D_717308596==0 & D_946849196_D_729863969==0 & D_946849196_D_746788766==0 &
                                  D_946849196_D_658810736==1 &  !is.na(D_984514646)) %>% 
  select(Connect_ID, D_946849196_D_108104748, D_984514646, d_832139544)%>% 
  arrange(desc(d_832139544))

colnames(error3) <- c("Connect ID", "TESTTHER2", "TESTTHER4", "Date_M2_Completed")
if (nrow(error3) == 0) {
  cat("No errors")
} else {
  knitr::kable(error3)
}

```
