---
title: "Rectruitment Derived Variable QC"
author: "Kelsey Sanchez"
date: "`r Sys.Date()`"
header-includes:  
    \usepackage{placeins}


output:
  pdf_document:
    extra_dependencies: ["float"]
    toc: false
    keep_tex: yes
    fig_caption: true
---





```{r library, include=FALSE}
#rm(list = ls())


#update.packages("tinytex")
#require(devtools)
#install_version("ggplot2", version = "0.9.1", repos = "http://cran.us.r-project.org")
#tinytex::install_tinytex(version = "2020.10")
#tinytex::reinstall_tinytex(repository = "illinois")



library(bigrquery)
library(foreach)
library(stringr)
#library(plyr)
library(expss) ###to add labels
library(epiDisplay) ##recommended applied here crosstable, tab1
library(gmodels) ##recommended
library(magrittr)
library(arsenal)
library(gtsummary)
library(rio)


library(stringr)
library(ggplot2)
library(gridExtra)
library(scales)
library(gt)
#install(tinytex)
library(tinytex)
library(data.table) ###to write or read and data management 
library(tidyverse) ###for data management
library(dplyr) ###data management
library(reshape)  ###to work on transition from long to wide or wide to long data
library(listr) ###to work on a list of vector, files or..
library(sqldf) ##sql
library(lubridate) ###date time
library(stringr) ###to work on patterns, characters
library(kableExtra)

options(tinytex.verbose = TRUE)

bq_auth()
```


```{r BQ_Pull, include=FALSE}

project <- "nih-nci-dceg-connect-prod-6d04"

partsbq <- "SELECT Connect_ID, token, D_512820379, D_471593703, state_d_934298480, D_230663853,
D_335767902, D_982402227, D_919254129, D_699625233, D_564964481, D_795827569, D_544150384, d_827220437,
D_371067537, D_430551721, D_821247024, D_914594314,  state_d_725929722, d_126331570, d_536735468, 
d_663265240, d_878865966, d_684635302, d_167958071,d_371067537, d_130371375_d_266600170_d_731498909, d_130371375_d_266600170_d_222373868, d_130371375_d_266600170_d_787567527,
d_949302066 , D_517311251, D_205553981, D_117249500, d_976570371, d_914639140, d_311580100 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` 
where Connect_ID IS NOT NULL"
partsbq_table <- bq_project_query(project, partsbq)
partsbq <- bq_table_download(partsbq_table, bigint = "integer64")


biobq <- "SELECT Connect_ID, token, d_299553921_d_593843561, d_299553921_d_883732523, d_703954371_d_593843561, d_703954371_d_883732523, d_838567176_d_593843561, d_838567176_d_883732523, d_454453939_d_593843561, d_454453939_d_883732523, d_652357376_d_593843561, d_652357376_d_883732523, d_505347689_d_593843561, d_505347689_d_883732523 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.biospecimen_JP` 
where Connect_ID IS NOT NULL"
biobq_table <- bq_project_query(project, biobq)
biobq <- bq_table_download(biobq_table, bigint = "integer64")

partsbq$Connect_ID <- as.numeric(partsbq$Connect_ID)
biobq$Connect_ID <- as.numeric(biobq$Connect_ID)


base_vars= left_join(partsbq, biobq, by="Connect_ID")

base_vars <-
  base_vars %>%  mutate(
    Site = case_when(
      d_827220437 == 125001209 ~ "Kaiser Permanente Colorado",
      d_827220437 == 181769837 ~ "Other",
      d_827220437 == 300267574 ~ "Kaiser Permanente Hawaii",
      d_827220437 == 303349821 ~ "Marshfield Clinic Health System",
      d_827220437 == 327912200 ~ "Kaiser Permanente Georgia",
      d_827220437 == 452412599 ~ "Kaiser Permanente Northwest",
      d_827220437 == 517700004 ~ "National Cancer Institute",
      d_827220437 == 531629870 ~ "HealthPartners",
      d_827220437 == 548392715 ~ "Henry Ford Health System",
      d_827220437 == 657167265 ~ "Sanford Health",
      d_827220437 == 809703864 ~ "University of Chicago Medicine"
    )
  )

```




### If all BL Modules are completed and the participant has a baseline research collection where the tube is collected and the reason tube wasn't collected wasn't refusal, then SMPaym_TmPaymEligBL_v1r0 must be populated.

```{r Incentive_Rule2, echo=FALSE, warning=FALSE, message=FALSE}




incentive2 <- base_vars %>%  filter(d_949302066 == '231311385' & d_536735468 == '231311385' & d_976570371 == '231311385' & d_663265240 == '231311385' & 
                                      ((d_299553921_d_593843561==353358909 & d_299553921_d_883732523 != 681745422) |
                                         (d_703954371_d_593843561==353358909 & d_703954371_d_883732523 != 681745422) |
                                         (d_838567176_d_593843561==353358909 & d_838567176_d_883732523 != 681745422) |
                                         (d_454453939_d_593843561==353358909 & d_454453939_d_883732523 != 681745422) |
                                         (d_652357376_d_593843561==353358909 & d_652357376_d_883732523 != 681745422) |
                                         (d_505347689_d_593843561==353358909 & d_505347689_d_883732523 != 681745422)) &
  (d_130371375_d_266600170_d_731498909!=353358909 | d_130371375_d_266600170_d_222373868!=353358909 | is.na(d_130371375_d_266600170_d_787567527)))




incentive2 <- incentive2  %>% select(Site, Connect_ID, d_130371375_d_266600170_d_731498909, d_130371375_d_266600170_d_222373868, d_130371375_d_266600170_d_787567527)  %>%  sort_by(Site)


colnames(incentive2) <- c("Site", "Connect ID", "SMPaym_PaymEligBL", "SMPaym_NORCPaymEligBL", "SMPaym_TmPaymEligBL")
knitr::kable(incentive2)  %>% kable_styling(latex_options = "scale_down")
```

\FloatBarrier

### If either the BUM Survey or the BU Survey was completed with SrvBlU_MENST60_v2r0 answered yes, then SrvMC_MenstSrvElig_v1r0 must be yes. 

```{r Menstrual_Eligibility, echo=FALSE, warning=FALSE, message=FALSE}


mens_ccc <- "WITH combined_survey AS (
  SELECT Connect_ID
  FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.bioSurvey_v1_JP`
  WHERE d_112151599 = '353358909'

  UNION DISTINCT

  SELECT Connect_ID
  FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.clinicalBioSurvey_v1_JP`
  WHERE d_112151599 = '353358909'
)

SELECT p.Connect_ID, p.d_827220437, p.d_459098666, p.d_253883960, p.d_265193023, p.d_289750687
FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` p
JOIN combined_survey c ON p.Connect_ID = c.Connect_ID
WHERE (p.d_253883960 = '231311385' OR p.d_265193023 = '231311385')"

mens_table <- bq_project_query(project, mens_ccc)
mens <- bq_table_download(mens_table, bigint = "integer64")


mens <-
  mens %>%  mutate(
    Site = case_when(
      d_827220437 == 125001209 ~ "Kaiser Permanente Colorado",
      d_827220437 == 181769837 ~ "Other",
      d_827220437 == 300267574 ~ "Kaiser Permanente Hawaii",
      d_827220437 == 303349821 ~ "Marshfield Clinic Health System",
      d_827220437 == 327912200 ~ "Kaiser Permanente Georgia",
      d_827220437 == 452412599 ~ "Kaiser Permanente Northwest",
      d_827220437 == 517700004 ~ "National Cancer Institute",
      d_827220437 == 531629870 ~ "HealthPartners",
      d_827220437 == 548392715 ~ "Henry Ford Health System",
      d_827220437 == 657167265 ~ "Sanford Health",
      d_827220437 == 809703864 ~ "University of Chicago Medicine"
    )
  )

#d_112151599=='353358909' & (d_253883960=='231311385' | d_265193023 =='231311385') & 
mens_elg <- mens %>%  filter(is.na(d_289750687)) %>%  select(Site, Connect_ID, d_289750687)  %>%  sort_by(Site)

colnames(mens_elg) <- c("Site", "Connect ID", "SrvMC_MenstSrvElig_v1r0")
#knitr::kable(mens_elg) 

mens_elg %>% gt()

```




